--WC_FF_ENTITY_DATA
IF EXISTS (SELECT 1 FROM WC_FF_ENTITY_DATA WHERE ENTITY='PT08')							
DELETE FROM WC_FF_ENTITY_DATA WHERE ENTITY='PT08'	

INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'TARGET_ACCNT_BU',	'String',	0,	'1',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'TARGET_ACCNT_NAME',	'String',	0,	'2',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'AGR_BU',	'String',	0,	'3',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'AGR_AGREE_NUM',	'String',	0,	'4',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_TYPE0',	'String',	0,	'5',	'30',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_NAME',	'String',	0,	'6',	'30',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_X_TXN_DT',	'Date',	0,	'7',	'10',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_X_TXN_PTS',	'Number',	0,	'8',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'PROD_CODE',	'String',	0,	'9',	'30',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'PROD_BU',	'String',	0,	'10',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_X_TXN_QTY',	'Number',	0,	'11',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_X_TXN_STAT_CD',	'String',	0,	'12',	'30',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_NOSALE_RES_CD',	'String',	0,	'13',	'30',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'APPROVED_BY',	'String',	0,	'14',	'50',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'CON_PERSON_UID',	'String',	0,	'15',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_TXN_SRC_CD',	'String',	0,	'16',	'50',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'LN_NUM',	'Number',	0,	'17',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'LN_NUM2',	'Number',	0,	'18',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'PTS_TXN_ACCNT',	'String',	0,	'19',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_COMMENTS',	'String',	0,	'20',	'250',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_PERIOD_CD',	'String',	0,	'21',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_SUBMISSION_DT',	'Date',	0,	'22',	'10',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_SUBMITTED_BY',	'String',	0,	'23',	'30',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_CANCELLATION_DT',	'Date',	0,	'24',	'10',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT	'PT08',	'X_CANCELLED_BY',	'String',	0,	'25',	'30',	0





--WC_FF_ENTITY_DETAILS
IF EXISTS (SELECT 1 FROM WC_FF_ENTITY_DETAILS WHERE ENTITY='PT08')
DELETE FROM WC_FF_ENTITY_DETAILS WHERE ENTITY='PT08'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Austria',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Korea',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'CzechRepublic',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Germany',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Taiwan',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Kazakhstan',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Canada',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Romania',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'United_Kingdom',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'France',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Portugal',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Netherlands',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Italy',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Serbia',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Greece',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Canary_Islands',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Malaysia',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Slovakia',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Poland',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'WWDF',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Switzerland',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Russia',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Belgium',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Spain',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Sweden',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Ukraine',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'United_States',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Hungary',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PT08',	'OLTP',	'PT',	'Ireland',	'Y'

--WC_FF_ENTITY_PARAM
IF EXISTS (SELECT 1 FROM WC_FF_ENTITY_PARAM WHERE ENTITY_CODE='PT08')
DELETE FROM WC_FF_ENTITY_PARAM WHERE ENTITY_CODE='PT08'
INSERT INTO WC_FF_ENTITY_PARAM (ENTITY_CODE,DATABASE_TYPE,VERSION,ACTIVE,DESCRIPTION,TARGET_TABLE)	SELECT	'PT08 ',	'OLTP',	'1',	'Y',	'NULL',	'NULL'