IF  EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[WC_ASSORTMENT_SCD]'))
DROP VIEW [dbo].[WC_ASSORTMENT_SCD]
GO 

CREATE VIEW  [dbo].[WC_ASSORTMENT_SCD]
  (
        ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
  )
AS
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_IT
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_ES
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_NL
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_BE
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_FR
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_UA
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_WW
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_GEN
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_CH
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_RU

UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_KR

UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_MY
UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_TW


UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_CA


UNION ALL
SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_RO

UNION ALL

SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_IE

UNION ALL

SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_SR

UNION ALL

SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_GE

UNION ALL

SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_AT


UNION ALL

SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_PT

UNION ALL

SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_SK

UNION ALL

SELECT  ROW_WID,
        ETL_PROC_WID,
        INTEGRATION_ID,
        DATASOURCE_NUM_ID,
        SCD_START_DT_WID,
        SCD_END_DT_WID,
        NAME,
        ACCOUNT_WID,
        PRODUCT_WID,
        TYPE_CD,
        TYPE_CD_I,
        LOC_TYPE_CD,
        LOC_TYPE_CD_I,
        LOC_SUBTYPE_CD,
        LOC_SUBTYPE_CD_I,
        BU_ID,
        ASSORTMENT_START_DT,
        ASSORTMENT_END_DT,
        ASSORTMENT_ID,
        PERIOD_NAME,
        ORG_NAME,
        CTLG_NAME
FROM WC_ASSORTMENT_SCD_HU




GO


