--WC_FF_ENTITY_DATA 
-->CHv7
IF NOT EXISTS (SELECT * FROM WC_FF_ENTITY_DATA WHERE ENTITY='CH07')
BEGIN
	INSERT INTO WC_FF_ENTITY_DATA
	SELECT 'CH07' , FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2
	FROM  WC_FF_ENTITY_DATA
	WHERE ENTITY ='CH06';
END
GO


IF NOT EXISTS (SELECT * FROM WC_FF_ENTITY_DATA WHERE ENTITY='CH07' AND FIELD = 'X_LEGAL_ENTITY_NAME')  BEGIN  INSERT INTO WC_FF_ENTITY_DATA  VALUES ('CH07','X_LEGAL_ENTITY_NAME','String',0,83,'100',0); END 

-->CIv14
IF NOT EXISTS (SELECT * FROM WC_FF_ENTITY_DATA WHERE ENTITY='CI14')
BEGIN
	INSERT INTO WC_FF_ENTITY_DATA
	SELECT 'CI14' , FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2
	FROM  WC_FF_ENTITY_DATA
	WHERE ENTITY ='CI13';
END
GO


IF NOT EXISTS (SELECT * FROM WC_FF_ENTITY_DATA WHERE ENTITY='CI14' AND FIELD = 'X_TARGET_NUM')  BEGIN  INSERT INTO WC_FF_ENTITY_DATA  VALUES ('CI14','X_TARGET_NUM','Number',0,51,'22,7',0); END 



--WC_FF_ENTITY_DETAILS
-->CHv7
IF NOT EXISTS (SELECT * FROM WC_FF_ENTITY_DETAILS where ENTITY='CH07')
BEGIN 
	INSERT INTO WC_FF_ENTITY_DETAILS
	SELECT 'CH07' , ENTITY_TYPE, 'CH07',COUNTRY,'Y'
	FROM  WC_FF_ENTITY_DETAILS
	WHERE ENTITY ='CH06';
END
GO

-->CIv14
IF NOT EXISTS (SELECT * FROM WC_FF_ENTITY_DETAILS where ENTITY='CI14')
BEGIN 
	INSERT INTO WC_FF_ENTITY_DETAILS
	SELECT 'CI14' , ENTITY_TYPE, 'CI14',COUNTRY,'Y'
	FROM  WC_FF_ENTITY_DETAILS
	WHERE ENTITY ='CI13';
END
GO



--WC_FF_ENTITY_PARAM
-->CHv7
IF NOT EXISTS (SELECT * FROM WC_FF_ENTITY_PARAM WHERE ENTITY_CODE='CH' AND VERSION='07')
	INSERT INTO WC_FF_ENTITY_PARAM (ENTITY_CODE,DATABASE_TYPE,VERSION,ACTIVE,DESCRIPTION,TARGET_TABLE) 
	SELECT 'CH', 'OLTP', '07', 'Y', 'FDE_INT_CONTRACT_NEW_PRE_GENERIC', 'PRE_EIM_AGREEMENT_NEW';
GO

-->CIv14
IF NOT EXISTS (SELECT * FROM WC_FF_ENTITY_PARAM WHERE ENTITY_CODE='CI' AND VERSION='14')
	INSERT INTO WC_FF_ENTITY_PARAM (ENTITY_CODE,DATABASE_TYPE,VERSION,ACTIVE,DESCRIPTION,TARGET_TABLE) 
	SELECT 'CI', 'OLTP', '14', 'Y', 'FDE_INT_CONTRACT_ITEMS_PRE_GENERIC', 'PRE_EIM_AGREE_ITEM';
GO



select * from WC_FF_ENTITY_DATA where ENTITY ='CH07' order by COLUMN_NO
select * from WC_FF_ENTITY_DATA where ENTITY ='CI14' order by COLUMN_NO


select * from WC_FF_ENTITY_DETAILS where ENTITY='CH07'
select * from WC_FF_ENTITY_DETAILS where ENTITY='CI14'

select * from WC_FF_ENTITY_PARAM where ENTITY_CODE='CH' AND VERSION='07'
select * from WC_FF_ENTITY_PARAM where ENTITY_CODE='CI' AND VERSION='14'