SELECT 
AGREE_NUM, 
TMPL.NAME, 
ACC.NAME  AS ACCOUNT_NAME, 
ITM.X_PAYMENT_SEQ_NUM,--X_PAYMENT_SEQ_NUM, --CHG228033
SSP.PAY_STAT_CD,--X_PAID_TYPE_CD, --CHG228033
--X_PAY_PERC_NUM, --CHG228033
--X_EXP_PAY_DT, --CHG228033
SSP.ACTL_PAY_DT, -- X_OBSERVATION_DT, --CHG228033
SSP.PAY_AMT, --X_ACT_AMT, --CHG228033
LAST_NAME, 
FST_NAME, 
CASE WHEN D.CON_PER_ID IS NULL	THEN 'N' ELSE 'Y' END AS PR_CONTACT_FLG, --ACC.PR_CON_ID changed as per CHG229045 
X_GIFT_CARD_NUM, --'Dummy',
C.X_ATTRIB_3,
D.NAME    AGR_NAME, 
/*B.NAME    TARGET_ACCNT_BU, 
ACC.LOC   TARGET_ACCNT_LOC, 
ACC.NAME  TARGET_ACCNT_NAME, 
D.REV_NUM AGR_REV_NUM, 
B1.NAME   AGR_BU, 
ITM.TYPE  TYPE, 
ITM.NAME,
ITM.ROW_ID,*/ --CHG228033
CON_X.ATTRIB_38, --C.X_ATTRIB_2 changed as per INC2226195 
--ITM.X_PAY_AMOUNT_NUM, --CHG090663 --removed as per CHG228033
ISNULL(SSP.X_PLAN_AMT_NUM, ITM.X_PAY_AMOUNT_NUM) X_PLAN_AMT_NUM, --CHG228033
--CHG161158
C.CELL_PH_NUM,
C.X_ATTRIB_14_CD,
CON_X.ATTRIB_37,
SSP.ROW_ID,----CHG228033
SSP.PAYMENT_REQ_NUM, ----CHG228033
SSP.TYPE_CD ----CHG228033
FROM  S_DOC_AGREE D 
LEFT OUTER JOIN S_ORG_EXT ACC ON D.TARGET_OU_ID = ACC.PAR_ROW_ID 
LEFT OUTER JOIN S_PAYMENT_PLAN TMPL ON D.X_PAYMENT_PLAN_TEMP_ID = TMPL.ROW_ID 
--LEFT OUTER JOIN CX_AGR_PL_ITEM ITM ON ITM.PAR_ROW_ID = D.ROW_ID --removed as per CHG228033
LEFT OUTER JOIN S_SRC_PAYMENT SSP ON SSP.CONTRACT_ID = D.ROW_ID --CHG228033
LEFT OUTER JOIN CX_AGR_PL_ITEM ITM ON ITM.ROW_ID = SSP.X_PAY_PLAN_ID --CHG228033
--LEFT OUTER JOIN S_CONTACT C ON ACC.PR_CON_ID = C.ROW_ID 
LEFT OUTER JOIN S_CONTACT C ON D.CON_PER_ID = C.ROW_ID --CHG229045
LEFT OUTER JOIN S_CONTACT_X CON_X ON C.ROW_ID = CON_X.ROW_ID --INC2226195
LEFT OUTER JOIN S_BU B ON B.ROW_ID = ACC.BU_ID
LEFT OUTER JOIN S_BU B1 ON B1.ROW_ID=D.BU_ID
--LEFT OUTER JOIN S_PER_PAY_PRFL PPP ON PPP.ROW_ID = C.PR_PER_PAY_PRFL_ID
LEFT OUTER JOIN S_PTY_PAY_PRFL PRFL   ON PRFL.ROW_ID = C.PR_PER_PAY_PRFL_ID
WHERE SSP.PAY_STAT_CD = 'To be Paid' --ITM.X_PAID_TYPE_CD='To be Paid' --CHG228033
AND B.NAME ='Kazakhstan, KZ'

SELECT * FROM S_BU 
select SSP.PAY_AMT, SSP.PAY_STAT_CD, SSP.ACTL_PAY_DT, SSP.X_PLAN_AMT_NUM, * from S_SRC_PAYMENT SSP where PAY_STAT_CD = 'To be Paid'

UPDATE S_SRC_PAYMENT
SET PAY_STAT_CD='To be Paid'
WHERE ROW_ID IN ('1-OAPDP','1-RCHLB','1-RCHLG','1-PFZGH')

UPDATE S_SRC_PAYMENT
SET ACTL_PAY_DT= '2015-07-16 12:58:25.000'
WHERE ROW_ID IN ('1-OAPDP','1-RCHLB','1-RCHLG','1-PFZGH')

UPDATE S_SRC_PAYMENT
SET X_PAY_PLAN_ID = '1-4S79J'
WHERE ROW_ID IN ('1-PFZGH')--('1-OAPDP','1-RCHLB','1-RCHLG','1-PFZGH')

select  SSP.PAY_AMT, SSP.PAY_STAT_CD, SSP.ACTL_PAY_DT, SSP.X_PLAN_AMT_NUM, SSP.* from S_SRC_PAYMENT SSP inner join S_DOC_AGREE D on SSP.CONTRACT_ID = D.ROW_ID
WHERE D.BU_ID = '1-5T6SH' AND SSP.PAY_STAT_CD = 'To be Paid'




SELECT * FROM S_SRC_PAYMENT SSP INNER JOIN 
CX_AGR_PL_ITEM ITM ON ITM.ROW_ID = SSP.X_PAY_PLAN_ID 

SELECT TOP 10 * FROM CX_AGR_PL_ITEM WHERE ROW_ID NOT IN (SELECT SSP.X_PAY_PLAN_ID  FROM S_SRC_PAYMENT SSP INNER JOIN 
CX_AGR_PL_ITEM ITM ON ITM.ROW_ID = SSP.X_PAY_PLAN_ID )


SELECT IF_ROW_STAT, * FROM EIM_PAYMENT WHERE IF_ROW_BATCH_NUM BETWEEN 17000 AND 17999

DELETE FROM EIM_PAYMENT WHERE ROW_ID ='1-4S796'

SELECT PAY_STAT_CD FROM S_SRC_PAYMENT
WHERE ROW_ID IN ('1-OAPDP','1-RCHLB','1-RCHLG','1-PFZGH')