IF NOT EXISTS (
		SELECT 1
		FROM INFORMATION_SCHEMA.COLUMNS
		WHERE TABLE_NAME = 'WC_ORG_HISTORY_D'
			AND COLUMN_NAME = 'POSITION_NAME'
		)
BEGIN
	ALTER TABLE WC_ORG_HISTORY_D ADD POSITION_NAME NVARCHAR(100)
END
	GO

