IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MERGE_WC_ACTIVITY_F' AND COLUMN_NAME = 'X_EVT_STAT_FLG')
BEGIN
   ALTER TABLE MERGE_WC_ACTIVITY_F ADD [X_EVT_STAT_FLG] NVARCHAR(1) NULL
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'MERGE_WC_ASSESS_D' AND COLUMN_NAME = 'X_EVT_STAT_FLG')
BEGIN
   ALTER TABLE MERGE_WC_ASSESS_D ADD [X_EVT_STAT_FLG] NVARCHAR(1) NULL
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WC_ACTIVITY_F' AND COLUMN_NAME = 'X_EVT_STAT_FLG')
BEGIN
   ALTER TABLE WC_ACTIVITY_F ADD [X_EVT_STAT_FLG] NVARCHAR(1) NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WC_LAST_ACTIVITY_F' AND COLUMN_NAME = 'X_EVT_STAT_FLG')
BEGIN
   ALTER TABLE WC_LAST_ACTIVITY_F ADD [X_EVT_STAT_FLG] NVARCHAR(1) NULL
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WC_ACTIVITY_FS' AND COLUMN_NAME = 'X_EVT_STAT_FLG')
BEGIN
   ALTER TABLE WC_ACTIVITY_FS ADD [X_EVT_STAT_FLG] NVARCHAR(1) NULL
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WC_ASSESS_D' AND COLUMN_NAME = 'X_EVT_STAT_FLG')
BEGIN
   ALTER TABLE WC_ASSESS_D ADD [X_EVT_STAT_FLG] NVARCHAR(1) NULL
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WC_ASSESS_D_DS' AND COLUMN_NAME = 'X_EVT_STAT_FLG')
BEGIN
   ALTER TABLE WC_ASSESS_D_DS ADD [X_EVT_STAT_FLG] NVARCHAR(1) NULL
END
GO

