SELECT S_EVT_ACT.ROW_ID, 
S_EVT_ACT.CREATED ,
S_EVT_ACT.ACD_CALL_DURATION, 
S_EVT_ACT.ASSOCIATED_COST, 
S_EVT_ACT.COST_CURCY_CD, 
S_EVT_ACT.COST_EXCH_DT, 
S_EVT_ACT.EVT_PRIORITY_CD, 
S_EVT_ACT.EVT_STAT_CD, 
S_EVT_ACT.OWNER_PER_ID, 
S_EVT_ACT.SRA_TYPE_CD, 
S_EVT_ACT.TARGET_OU_ID, 
CASE WHEN S_EVT_ACT.TODO_CD='Retail Assessment - Sign' THEN EVTX.X_SIGNED_BY_ID  ELSE S_EVT_ACT.TARGET_PER_ID END, --CHG098293
S_EVT_ACT.TODO_ACTL_START_DT,
CASE WHEN S_EVT_ACT.TODO_CD = 'Mobile Materials Audit' THEN 'Permanent Material Audit'
ELSE S_EVT_ACT.TODO_CD
END AS TODO_CD, 
S_EVT_ACT.TODO_PLAN_END_DT,
S_EVT_ACT.TODO_PLAN_START_DT,
S_EVT_ACT.SRA_RESOLUTION_CD,
S_EVT_ACT.SRV_REGN_ID,
S_EVT_ACT.TRAVEL_TM_MIN,
S_CONTACT.PR_HELD_POSTN_ID,
S_EVT_ACT.REQUIRED_FLG,
S_EVT_ACT.NAME,
S_EVT_ACT.PAR_EVT_ID,
S_EVT_ACT.PRDPROMO_ID,
S_EVT_ACT.PR_PRDINT_ID,
S_EVT_ACT.X_PERIOD_ID,
ISNULL(S_EVT_ACT.X_NON_WORKING_FLG,'N'),
ISNULL(S_EVT_ACT.X_SELLING_TIME_FLG,'N'),
S_EVT_ACT.APPT_DURATION_MIN,
S_EVT_ACT.X_NO_OF_VISITS_NUM,
S_EVT_ACT.COMMENTS_LONG,
S_EVT_ACT.NOSALE_RES_CD,
PAR_EVT.TODO_CD,
S_TMPL_PLANITEM.NAME,
--S_SRC.ROW_ID, Commented as per Defect 189
S_EVT_ACT.X_VISIT_REQUIRED_FLG,
S_EVT_ACT.X_BU_ID,
ISNULL(S_EVT_ACT.TODO_ACTL_START_DT,(ISNULL(PAR_EVT.TODO_ACTL_START_DT,(ISNULL(PAR_EVT.TODO_PLAN_START_DT,S_EVT_ACT.TODO_PLAN_START_DT)))))X_START_DT,
ISNULL( S_EVT_ACT.TODO_ACTL_END_DT,(ISNULL(PAR_EVT.TODO_ACTL_END_DT ,( ISNULL(PAR_EVT.TODO_PLAN_END_DT,S_EVT_ACT.TODO_PLAN_END_DT)))))X_END_DT,
PAR_EVT.EVT_STAT_CD EVENT_STATUS,
PAR_EVT.TODO_PLAN_START_DT,
PAR_EVT.TODO_PLAN_END_DT,
ISNULL(S_EVT_ACT.CEM_TOTAL_TIME,0.0),
S_EVT_ACT.LAST_UPD,
S_ASSET.PROD_ID,
S_EVT_ACT.SRC_ID,
S_EVT_ACT.OPTY_ID,
S_POSTN.OU_ID OWNER_OU_ID,
POSCRTDBY.OU_ID CRTDBY_OU_ID,
S_EVT_ACT.SRA_SR_ID,
S_EVT_ACT.AGREEMENT_ID,
ENT_SR.PAR_AGREE_ID SR_PAR_AGREE_ID,
ENT_ACT.PAR_AGREE_ID ACT_PAR_AGREE_ID,
S_SRV_REQ.AGREE_ID SR_ENTITLEMENT_ID,
S_SRV_ACT.ENTLMNT_ID ACT_ENTLMNT_ID,
S_EVT_ACT.ASSET_ID,
S_EVT_ACT.INSCLM_ELMNT_ID,
S_EVT_ACT.INSCLM_ID,
S_EVT_ACT.TODO_ACTL_END_DT,
S_SRV_ACT.CURCY_CD,
S_SRV_ACT.EXCH_DT,
--S_EVT_ACT.X_ASSESS_ID as ASSESS_TMPL_ID, Defect 725
S_EVT_ACT.ACTIVITY_UID,
PAR_EVT.REQUIRED_FLG,
PAR_EVT.TODO_ACTL_START_DT,
PAR_EVT.TODO_ACTL_END_DT,
S_TMPL_PLANITEM.TYPE_CD,
S_EVT_ACT.X_APPT_DURATION_MIN,
S_EVT_ACT.CREATOR_LOGIN,
S_EVT_ACT.ALARM_FLAG,
S_EVT_ACT.CAL_DISP_FLG,
S_EVT_ACT_CSX.ROUTINE_FLG,
S_EVT_ACT.PERFRM_BY_PER_ID,
S_EVT_ACT.X_REAL_END_DT,
S_EVT_ACT.ACD_LOG_ENTRY_DT,
S_EVT_ACT.X_SUBTODO_CD,
S_EVT_ACT.PARTICIPANT_NUM,
S_EVT_ACT.APPT_START_DT,
S_EVT_ACT.X_RESOURCES_NUM,
S_EVT_ACT.AGREEMENT_ID,
CASE
WHEN SUBSTRING(S_EVT_ACT.ROW_ID,CHARINDEX('-',S_EVT_ACT.ROW_ID),1)+''+SUBSTRING(S_EVT_ACT.ROW_ID,CHARINDEX('-',S_EVT_ACT.ROW_ID,CHARINDEX('-',S_EVT_ACT.ROW_ID)+1),1) ='--' THEN 'N'
ELSE 'Y'
END AS ASGN_MANL_FLG,
S_EVT_ACT.X_END_KM_NUM,
S_EVT_ACT.X_START_KM_NUM,
S_EVT_ACT.X_LICENSE_PLATE_TEXT,
CASE WHEN S_EVT_ACT.TODO_CD='In Store Visit' THEN PERF_BY_EMP.X_FIX_COST_NUM
ELSE S_EVT_ACT.X_ACTIVITY_COST_NUM
END AS X_ACTIVITY_COST_NUM,
QUOTE.NAME AS X_ORDER_TMPL_NAME,
ISNULL (PAR_EVT.X_RETRO_FLG,S_EVT_ACT.X_RETRO_FLG) AS X_RETRO_FLG,
ISNULL (PAR_EVT.X_RETRO_DT,S_EVT_ACT.X_RETRO_DT)  AS VISIT_INPUT_DT,
S_EVT_ACT.X_STAFF_TRAINING,
S_EVT_ACT.X_FIXED_FLAG,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_01,'N')AS  X_ATTRIB_01,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_02,'N')AS  X_ATTRIB_02,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_03,'N')AS  X_ATTRIB_03,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_04,'N')AS  X_ATTRIB_04,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_05,'N')AS  X_ATTRIB_05,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_06,'N')AS  X_ATTRIB_06,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_07,'N')AS  X_ATTRIB_07,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_08,'N')AS  X_ATTRIB_08,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_09,'N')AS  X_ATTRIB_09,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_10,'N')AS  X_ATTRIB_10,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_11,'N')AS  X_ATTRIB_11,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_12,'N')AS  X_ATTRIB_12,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_13,'N')AS  X_ATTRIB_13,
ISNULL (CX_EVT_ACT_X.X_ATTRIB_14,'N')AS  X_ATTRIB_14,
CX_EVT_ACT_X.X_ATTRIB_15,
CX_EVT_ACT_X.X_ATTRIB_16,
CX_EVT_ACT_X.X_ATTRIB_17,
CX_EVT_ACT_X.X_ATTRIB_18,
CX_EVT_ACT_X.X_ATTRIB_19,
CX_EVT_ACT_X.X_ATTRIB_20,
CX_EVT_ACT_X.X_ATTRIB_21,
CX_EVT_ACT_X.X_ATTRIB_22,
CX_EVT_ACT_X.X_ATTRIB_23,
CX_EVT_ACT_X.X_ATTRIB_24,
CX_EVT_ACT_X.X_ATTRIB_25,
CX_EVT_ACT_X.X_ATTRIB_26,
CX_EVT_ACT_X.X_ATTRIB_27,
CX_EVT_ACT_X.X_ATTRIB_28,
CX_EVT_ACT_X.X_ATTRIB_31,
S_EVT_ACT.SRA_SR_ID AS SRA_SR_ID,
S_SRV_REQ.ASSET_ID,
PERF_BYUSER.LOGIN,
S_EVT_ACT.X_PREVIOUS_VISIT_DT,
OBJ.X_MC_ID,
S_CONTACT.ROW_ID --Added as per INC0625649
,CX_EVT_ACT_X.X_ATTRIB_30
--CHG038681
,PAR_EVTX.ATTRIB_14
,PAR_EVTX.ATTRIB_46
,OBJ.NAME           --as per CHG038707
,LAST_UPD_USR.LOGIN  --as per CHG038473
,EVTX.X_AUDIT_FLG
, EVTX.X_AUDIT_COMMENTS_TEXT 
,EVTX. X_OUT_OF_HRS_FLG
,S_EVT_ACT.APPT_REPT_TYPE  --as per INC652113
,S_EVT_ACT.APPT_ALARM_TM_MIN   --as per INC0652113
,OBJ.PROG_START_DT
,OBJ.PROG_END_DT
,OBJ_CON.ROW_ID AS CON_ROW_ID
,EVTX.X_LATITUDE
,EVTX.X_LONGITUDE
,S_EVT_ACT.OWNER_LOGIN AS ASSIGNED_TO
,PAR_EVT.OWNER_LOGIN AS PAR_ASSIGNED_TO
,PAR_PERF_BYUSER.LOGIN AS PAR_PERFORMED_BY
--CHG053118
,S_EVT_ACT.X_RESCH_PLANNED_START_DT
,S_EVT_ACT.X_RESCH_PLANNED_END_DT
,S_EVT_ACT.X_PLANNED_FLG
,S_ACCNTRT.NAME AS RT_CYCLE_NAME
--CHG062271
,S_EVT_ACT.X_CANCELLED_BY
,PAR_EVT.X_CANCELLED_BY AS X_PAR_CANCELLED_BY
--CHG063457
,S_EVT_ACT.X_START_KMS_FIRST_NUM
, S_EVT_ACT.X_END_KMS_LAST_NUM
,S_EVT_ACT.X_PARKING_FEES_NUM,
CASE
WHEN SUBSTRING(PAR_EVT.ROW_ID,CHARINDEX('-',PAR_EVT.ROW_ID),1)+''+SUBSTRING(PAR_EVT.ROW_ID,CHARINDEX('-',PAR_EVT.ROW_ID,CHARINDEX('-',PAR_EVT.ROW_ID)+1),1) ='--' THEN 'N'
ELSE 'Y'
END AS PAR_MANL_CREATED_FLG
--CHG061084
,S_ORDER.ORDER_NUM
--CHG062266
,EVTX.X_TODO_TYPE_CD 
,EVTX.X_TODO_SUBTYPE_CD
,S_EVT_ACT.COMMENTS
,USR_LOGIN.LOGIN AS CLOSED_BY
,S_EVT_ACT.CG_SRC_PAYMENT_ID
--CHG061752
,S_EVT_ACT.X_SIGN_STATE_FLG AS STATE
,SIG.FST_NAME AS FST_NAME
,SIG.LAST_NAME AS LAST_NAME
,SIG.EMAIL_ADDR AS EMAIL_ADDR
,EVTX.X_SIGNATURE_DT AS SIG_DT
,S_EVT_ACT.X_TR_CYCLE_ID --CHG062361
,S_EVT_ACT.X_TR_REROUTE_ID -- CHG069117,CHG069482
,S_ACCNTRT.NAME AS ROUTING_NAME  --CHG069117
,REROUTING.NAME AS REROUTING_NAME --CHG069117
,S_EVT_ACT.X_START_TIME_DELAY_CD -- CHG069482
,S_EVT_ACT.X_TR_APPOINT_TYPE_CD -- INC1498940
,S_EVT_ACT.X_TR_FIXED_FLG -- INC1498940
,S_EVT_ACT.X_TR_PUBLIC_FLG -- INC1498940
,ISNULL(OBJ_PERIOD.NAME ,'Unspecified') --CHG090388
,S_EVT_ACT.X_VISIT_CREATION_REASON_CD --CHG090137
,CX_EVT_ACT_X.X_ATTRIB_31_CD --CHG099095
,CX_EVT_ACT_X.X_ATTRIB_32_CD --CHG099095
,EVTX.X_RA_RAL_LINK_ID --CHG107551
,CX_EVT_ACT_X.X_VISIT_LOV_ATTRIB_X_CD--CHG117366
,CX_EVT_ACT_X.X_VISIT_LOV_ATTRIB_Y_CD--CHG117366
,EVTX.ATTRIB_14--CHG117366
,EVTX.ATTRIB_15--CHG117366
,EVTX.ATTRIB_16--CHG117366
,EVTX.X_ACT_CREATION_REASON_CD--CHG117167
,EVTX.X_LOCAL_ATTRIB_1_CD--CHG117403
,S_EVT_ACT.X_TRADE_RETURN_START_DT  --CHG117391
,S_EVT_ACT.X_TRADE_RETURN_END_DT  --CHG117391
,EVTX.X_LOCAL_ATTRIB_2_CD  --CHG117391
,S_EVT_ACT.X_NO_OF_BOXES  --CHG117391
,S_EVT_ACT.X_NO_OF_STICKS  --CHG117391
,EVTX.X_BOOT_INFO_NUM  --CHG117391
,EVTX.X_BOOT_RTN_INFO_NUM  --CHG117391
,EVTX.X_STICKS_ISSUED_NUM --CHG117391
,EVTX.X_RARAL_DT --CHG124131 
,S_EVT_ACT.X_CAR_HIRE_FLG -- INC2370602
--CHG176441
,EVTX.X_ATTRIB_50
,EVTX.X_ATTRIB_51
,EVTX.X_ATTRIB_52
,EVTX.ATTRIB_34
,EVTX.ATTRIB_35
,EVTX.X_DOCUMENTATION_TYPE_CD --CHG201045
,EVTX.X_MESSAGE_STATUS --CHG201045
, CASE 
		WHEN RC.LAST_NAME IS NULL
			AND RC.FST_NAME IS NULL
			THEN NULL
		ELSE ISNULL(RC.LAST_NAME, '.') + ', ' + ISNULL(RC.FST_NAME, '.')
		END X_RECIPIENT_ID --CHG201045
, PREV_ACT.X_OBJ_ACT_FLG
, S_EVT_ACT.X_EVT_STAT_FLG 
, PREV_ACT.X_EVT_STAT_FLG
FROM
V_EVT_ACT S_EVT_ACT (NOLOCK)
LEFT OUTER JOIN S_ASSET (NOLOCK) ON S_EVT_ACT.ASSET_ID = S_ASSET.ROW_ID
LEFT OUTER JOIN S_USER(NOLOCK) ON S_EVT_ACT.OWNER_LOGIN =S_USER.LOGIN----Added as per Defect 1,590  from Jaime
--LEFT OUTER JOIN S_CONTACT (NOLOCK) ON S_EVT_ACT.OWNER_PER_ID = S_CONTACT.ROW_ID --Commented as per Defect 1,590  from Jaime
LEFT OUTER JOIN S_CONTACT (NOLOCK) ON S_USER.ROW_ID = S_CONTACT.ROW_ID--Added as per Defect 1,590  from Jaime
LEFT OUTER JOIN S_POSTN (NOLOCK) ON S_CONTACT.PR_HELD_POSTN_ID = S_POSTN.ROW_ID
LEFT OUTER JOIN S_CONTACT CRTDBY (NOLOCK) ON S_EVT_ACT.CREATED_BY = CRTDBY.ROW_ID
LEFT OUTER JOIN S_POSTN POSCRTDBY (NOLOCK) ON CRTDBY.PR_HELD_POSTN_ID = POSCRTDBY.ROW_ID
LEFT OUTER JOIN S_SRV_REQ  (NOLOCK) ON S_EVT_ACT.SRA_SR_ID = S_SRV_REQ.ROW_ID
LEFT OUTER JOIN S_OPTY  (NOLOCK) ON  S_EVT_ACT.OPTY_ID = S_OPTY.ROW_ID
LEFT OUTER JOIN S_SRV_ACT (NOLOCK) ON  S_EVT_ACT.ROW_ID = S_SRV_ACT.PAR_ROW_ID
LEFT OUTER JOIN S_ENTLMNT ENT_SR (NOLOCK) ON S_SRV_REQ.AGREE_ID = ENT_SR.ROW_ID
LEFT OUTER JOIN S_ENTLMNT ENT_ACT (NOLOCK) ON S_SRV_ACT.ENTLMNT_ID = ENT_ACT.ROW_ID
LEFT OUTER JOIN S_TMPL_PLANITEM (NOLOCK) ON  S_TMPL_PLANITEM.ROW_ID = S_EVT_ACT.ASSESS_TMPL_ID
LEFT OUTER JOIN S_EVT_ACT_CSX (NOLOCK) ON S_EVT_ACT_CSX.PAR_ROW_ID = S_EVT_ACT.ROW_ID
LEFT OUTER JOIN S_ACT_EMP (NOLOCK) ON S_EVT_ACT.ROW_ID= S_ACT_EMP.ACTIVITY_ID AND  S_EVT_ACT.OWNER_PER_ID = S_ACT_EMP.EMP_ID
LEFT OUTER JOIN S_EVT_ACT PAR_EVT (NOLOCK) ON S_EVT_ACT.PAR_EVT_ID = PAR_EVT.ROW_ID
--LEFT OUTER JOIN S_SRC (NOLOCK) ON ISNULL(S_EVT_ACT.X_PROMO_PROG_ID ,S_EVT_ACT.X_MERCH_PROGR_ID)=S_SRC.TMPL_ID AND S_EVT_ACT.TARGET_OU_ID = S_SRC.PR_ACCNT_ID 
--AND S_SRC.X_STATUS_CD in ('Active','Draft') -- Condition remove as per CHG078529 and commented as per Defect 189
LEFT OUTER JOIN S_CONTACT PERF_BY (NOLOCK) ON S_EVT_ACT.PERFRM_BY_PER_ID = PERF_BY.ROW_ID
LEFT OUTER JOIN S_POSTN POS_PERF_BY (NOLOCK) ON PERF_BY.PR_HELD_POSTN_ID = POS_PERF_BY.ROW_ID
LEFT OUTER JOIN S_EMP_PER PERF_BY_EMP (NOLOCK) ON PERF_BY.ROW_ID =PERF_BY_EMP.ROW_ID
LEFT OUTER JOIN S_DOC_QUOTE QUOTE (NOLOCK) ON QUOTE.ROW_ID = S_EVT_ACT.X_PROD_TEMP_ID 
LEFT OUTER JOIN CX_EVT_ACT_X WITH (FORCESEEK, INDEX(CX_EVT_ACT_X_P1)) ON CX_EVT_ACT_X.ROW_ID=S_EVT_ACT.ROW_ID
LEFT OUTER JOIN S_USER PERF_BYUSER (NOLOCK) ON PERF_BY.ROW_ID=PERF_BYUSER.ROW_ID
LEFT OUTER JOIN S_SRC OBJ (NOLOCK) ON OBJ.ROW_ID=S_EVT_ACT.PRDPROMO_ID --INC1055646 (Reverted)
LEFT OUTER JOIN S_EVT_ACT_X EVTX (NOLOCK) ON EVTX.ROW_ID=S_EVT_ACT.ROW_ID
LEFT OUTER JOIN S_USER LAST_UPD_USR(NOLOCK) ON LAST_UPD_USR.ROW_ID =S_EVT_ACT.LAST_UPD_BY
LEFT OUTER JOIN S_EVT_ACT_X PAR_EVTX (NOLOCK) ON PAR_EVTX.ROW_ID=PAR_EVT.ROW_ID --CHG038681/Defect 358
LEFT OUTER JOIN S_USER USR_OBJ(NOLOCK) ON OBJ.CREATED_BY =USR_OBJ.ROW_ID
LEFT OUTER JOIN S_CONTACT OBJ_CON ON OBJ_CON.ROW_ID =USR_OBJ.ROW_ID
LEFT OUTER JOIN S_USER PAR_PERF_BYUSER (NOLOCK) ON PAR_EVT.PERFRM_BY_PER_ID=PAR_PERF_BYUSER.ROW_ID
LEFT OUTER JOIN S_ACCNTRT (NOLOCK) ON    S_ACCNTRT.ROW_ID=S_EVT_ACT.X_TR_CYCLE_ID--CHG061084
LEFT OUTER JOIN S_ORDER (NOLOCK) ON S_ORDER.ROW_ID = S_EVT_ACT.ACT_TMPL_ID--CHG062266
LEFT OUTER JOIN S_USER USR_LOGIN (NOLOCK) ON USR_LOGIN.ROW_ID = S_EVT_ACT.PERFRM_BY_PER_ID --CHG061752
LEFT OUTER JOIN S_CONTACT SIG (NOLOCK)ON SIG.ROW_ID =EVTX.X_SIGNED_BY_ID
LEFT OUTER JOIN S_ACCNTRT REROUTING(NOLOCK) ON REROUTING.ROW_ID = S_EVT_ACT.X_TR_REROUTE_ID--CHG069117
LEFT OUTER JOIN S_PERIOD OBJ_PERIOD (NOLOCK) ON OBJ.PERIOD_ID =OBJ_PERIOD.ROW_ID -- CHG090388
LEFT JOIN S_CONTACT RC ON RC.ROW_ID = EVTX.X_RECIPIENT_ID
LEFT OUTER JOIN S_EVT_ACT PREV_ACT (NOLOCK) ON S_EVT_ACT.PREV_ACT_ID = PREV_ACT.ROW_ID
WHERE
 S_EVT_ACT.TEMPLATE_FLG <> 'Y'
AND
 S_EVT_ACT.TEMPLATE_FLG <> 'P'
--CHG053027
 AND 
-- CHG094865
--S_EVT_ACT.TODO_CD <> 'Update - Bank Account Info'
S_EVT_ACT.TODO_CD NOT IN ('Update - Bank Account Info','Fixed Appointment')