--WC_FF_ENTITY_DATA
IF EXISTS (SELECT 1 FROM WC_FF_ENTITY_DATA WHERE ENTITY='PO05')
DELETE FROM WC_FF_ENTITY_DATA WHERE ENTITY='PO05'
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'ACCOUNT_CODE',	'String',	0,	'18',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'CURCY_CD',	'String',	0,	'2',	'20',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'EFF_END_DT',	'Date',	0,	'4',	'10',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'EFF_START_DT',	'Date',	3,	'3',	'10',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'EXTD_PRI_AMT',	'Number',	0,	'10', '22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'NAME',	'String',	1,	'1',	'50',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'PL_DESC_TEXT',	'String',	0,	'6',	'255',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'PROD_BU',	'String',	8,	'8',	'100',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'PROD_CODE',	'String',	7,	'7',	'30',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'STD_PRI_UNIT',	'Number',	0,	'9',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'TAX_VAL1',	'Number',	0,	'11',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_AWARD_POINTS',	'Number',	0,	'19',	'10,0',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_FIX_TAX_AMOUNT',	'Number',	0,	'14',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_FREE_GOODS_VALUE',	'Number',	0,	'12',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_SUB_TYPE_CD',	'String',	0,	'5',	'30',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_TAX_BATCH',	'String',	0,	'13',	'50',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_TAX_CA_1',	'Number',	0,	'15',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_TAX_CA_2',	'Number',	0,	'16',	'2,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_TAX_CA_3',	'Number',	0,	'17',	'22,7',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_JTI_PRICELIST_CATEGORY_CD',	'String',	0,	'20',	'30',	0
INSERT INTO WC_FF_ENTITY_DATA (ENTITY, FIELD, DATATYPE,INTEGRATION_ID,COLUMN_NO,MAX_LENGTH, INTEGRATION_ID2) SELECT 'PO05',	'X_JTI_PRICELIST_DISTRIBUTOR_TEXT',	'String',	0,	'21',	'100',	0


--WC_FF_ENTITY_DETAILS
IF EXISTS (SELECT 1 FROM WC_FF_ENTITY_DETAILS WHERE ENTITY='PO05')
DELETE FROM WC_FF_ENTITY_DETAILS WHERE ENTITY='PO05'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Austria',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Korea',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'CzechRepublic',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Germany',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Taiwan',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Kazakhstan',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Canada',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Romania',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'United_Kingdom',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'France',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Portugal',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Netherlands',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO',	'Italy',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Serbia',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Greece',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Canary_Islands',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Malaysia',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Slovakia',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Poland',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'WWDF',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Switzerland',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Russia',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Belgium',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Spain',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Sweden',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Ukraine',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'United_States',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Hungary',	'Y'
INSERT INTO WC_FF_ENTITY_DETAILS (ENTITY, ENTITY_TYPE, INTEGRATION_KEY,COUNTRY,ACTIVE_FLAG)	SELECT	'PO05',	'OLTP',	'PO05',	'Ireland',	'Y'

--WC_FF_ENTITY_PARAM
IF EXISTS (SELECT 1 FROM WC_FF_ENTITY_PARAM WHERE ENTITY_CODE='PO05')
DELETE FROM WC_FF_ENTITY_PARAM WHERE ENTITY_CODE='PO05'
INSERT INTO WC_FF_ENTITY_PARAM (ENTITY_CODE,DATABASE_TYPE,VERSION,ACTIVE,DESCRIPTION,TARGET_TABLE)	SELECT	'PO05 ',	'OLTP',	'1',	'Y',	'NULL',	'NULL'