

----------- BEGIN CREATE TABLE [dbo].[MERGE_WC_RTLAUDIT_F_SK]--------------------------

PRINT 'CREATE TABLE [MERGE_WC_RTLAUDIT_F_SK]'
GO

------------------------- END CREATE TABLE [dbo].[MERGE_WC_RTLAUDIT_F_SK] --------------------------



WITH
(
DATA_COMPRESSION = PAGE
)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'') AND name = N'')

GO



IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_M_A_BRAND_US_SWAPOUT]') AND name = N'CCSI-dbo-WC_SALES_M_A_BRAND_US_SWAPOUT-2077053910')
CREATE CLUSTERED COLUMNSTORE INDEX [CCSI-dbo-WC_SALES_M_A_BRAND_US_SWAPOUT-2077053910] ON [dbo].[WC_SALES_M_A_BRAND_US_SWAPOUT] WITH (DROP_EXISTING = OFF, DATA_COMPRESSION = COLUMNSTORE) ON [ps_SALES_TYPE_WID_US]([SALES_TYPE_WID])
GO