--[BU_ID] = '1-7Q8NB3'

SELECT * FROM MERGE_WCV_RTLAUDIT_F_MASTER WHERE [X_BU_ID] = '1-7Q8NB3' --SK & HU have been excluded in this view 
GO

SELECT * FROM WCV_LAST_RTLAUDIT_BRAND_A_MASTER WHERE [X_BU_ID] = '1-7Q8NB3'
GO

SELECT * FROM WCV_LAST_RTLAUDIT_F_MASTER WHERE [X_BU_ID] = '1-7Q8NB3' --SK & HU have been excluded in this view 
GO

SELECT * FROM WCV_RTLAUDIT_BRAND_A_MASTER WHERE [X_BU_ID] = '1-7Q8NB3'
GO

SELECT * FROM WCV_RTLAUDIT_F_MASTER WHERE [X_BU_ID] = '1-7Q8NB3' --SK & HU have been excluded in this view 
GO

SELECT * FROM MERGE_WCV_RTLAUDIT_F_CEU WHERE [X_BU_ID] = '1-7Q8NB3'
GO

SELECT * FROM MERGE_WCV_RTLAUDIT_F_CEU WHERE [X_BU_ID] = '1-7Q8NB3'
GO

SELECT * FROM WCV_LAST_RTLAUDIT_BRAND_A_CEU WHERE [X_BU_ID] = '1-7Q8NB3'
GO

SELECT * FROM WCV_LAST_RTLAUDIT_F_CEU WHERE [X_BU_ID] = '1-7Q8NB3'
GO

SELECT * FROM WCV_RTLAUDIT_BRAND_A_CEU WHERE [X_BU_ID] = '1-7Q8NB3'
GO

SELECT * FROM WCV_RTLAUDIT_F_CEU WHERE [X_BU_ID] = '1-7Q8NB3'
GO




