Step 1

---------------------------X_CONTRACTED_FLG-------------------------------------

SELECT 'IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS'+CHAR(10)+
'WHERE TABLE_NAME = '''+name+''' AND COLUMN_NAME = ''X_CONTRACTED_FLG'')'+CHAR(10)+
'BEGIN
   ALTER TABLE '+name+' ADD [X_CONTRACTED_FLG] NVARCHAR(1) NULL'+CHAR(10)+
'END'+CHAR(10)+
'GO'
FROM sys.tables 
WHERE name 
in ('WC_ASSET_DS',
'WC_ASSET_D'
)


Step 2

------------------Execute output from Step 1------------------------------------
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WC_ASSET_D' AND COLUMN_NAME = 'X_CONTRACTED_FLG')
BEGIN
   ALTER TABLE WC_ASSET_D ADD [X_CONTRACTED_FLG] NVARCHAR(1) NULL
END
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'WC_ASSET_DS' AND COLUMN_NAME = 'X_CONTRACTED_FLG')
BEGIN
   ALTER TABLE WC_ASSET_DS ADD [X_CONTRACTED_FLG] NVARCHAR(1) NULL
END
GO
