select * FROM S_LST_OF_VAL where TYPE = 'JTI_PROD_CAT' and LANG_ID = 'ESN' AND ACTIVE_FLG ='Y'

select * FROM S_LST_OF_VAL where TYPE = 'JTI_LOC_SUB_TYPE' AND ACTIVE_FLG ='Y' and LANG_ID = 'ESN' 

select * FROM S_LST_OF_VAL where TYPE = 'GAL_ME_FASCIA_TYPE'  AND ACTIVE_FLG ='Y' and LANG_ID = 'ESN'


select * FROM S_LST_OF_VAL where TYPE = 'GAL_ME_FASCIA_DETAIL' AND ACTIVE_FLG ='Y' and LANG_ID = 'ESN' 


select * FROM S_LST_OF_VAL where TYPE = 'GAL_ME_FASCIA_MESSAGE' AND ACTIVE_FLG ='Y' and LANG_ID = 'ESN' 

UPDATE S_LST_OF_VAL SET VAL= 'No Light box_TESTT' WHERE ROW_ID = '1-FB3AQ' 




select * from EIM_PRDINT_DTL