SELECT FIELD_VALUE, FIELD_NAME, FAILURE_DESCRIPTION, * FROM WC_ERRORS_G WHERE FILE_NAME LIKE '%ITCI1402_20220404_10%'

SELECT FIELD_VALUE, FIELD_NAME, FAILURE_DESCRIPTION, * FROM WC_ERRORS_G WHERE FILE_NAME LIKE '%RUCH0722_20220404_10%'


select ITEM.* FROM S_AGREE_ITEM ITEM INNER JOIN S_DOC_AGREE AGREE ON ITEM.DOC_AGREE_ID = AGREE.ROW_ID WHERE AGREE.BU_ID = '1-C4FV' AND AGREE.NAME IN ('1-469876907', '1-118059803')

select * FROM S_DOC_AGREE where NAME in ('1-469876907', '1-118059803')

select * FROM S_BU

EIM_AGREE_ITEM

SELECT IF_ROW_STAT, X_TARGET_NUM ,* FROM EIM_AGREE_ITEM WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')

insert into S_AGREE_ITEM (DOC_AGREE_ID, DOC_AGREE_NAME, 

SELECT IF_ROW_STAT,X_ORDER_CAT_CD ,* FROM EIM_ORDER_DTL --WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')

SELECT IF_ROW_STAT, * FROM EIM_AGREEMENT --WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')


-----------------------------------------------CH

select * from CX_LEGAL_ENTITY WHERE X_BU_ID = '1-21FD5'

UPDATE CX_LEGAL_ENTITY SET X_LEGAL_NAME_TEXT = 'VALID_LEGAL_ENTITY' WHERE ROW_ID = '1-7RIEU7'

-------------------PR
SELECT FIELD_VALUE, FIELD_NAME, FAILURE_DESCRIPTION, * FROM WC_ERRORS_G WHERE FILE_NAME LIKE '%ESPR1901_20220404_10%' order by 5, 3

DELETE FROM WC_ERRORS_G WHERE FILE_NAME LIKE '%ESPR1901_20220404_10%'

SELECT IF_ROW_STAT,* FROM EIM_PROD_INT WHERE IF_ROW_BATCH_NUM=100000000
SELECT IF_ROW_STAT,* FROM EIM_PRDINT_DTL WHERE IF_ROW_BATCH_NUM=100000000

select BAR_CODE_NUM,
    X_ME_EXTERNAL_WIDTH,
    X_ME_INTERNAL_WIDTH,
    X_INT_HEIGHT_NUM,
    X_ME_FASCIA_WIDTH,
    X_ME_FASCIA_MESSAGE,
    X_ME_FASCIA_DETAIL,
    X_ME_FASCIA_TYPE,
    X_ME_FASCIA_HEIGHT,
    X_DEF_LOC_SUB_TYPE_CD,
    X_SHELF_AUTOMATED_FLG,
    X_SHELF_DIVIDER_NUM,
    X_SLOT_DEPTH_NUM,
    X_SHELF_DIV_THICK_NUM,
    X_ROWS_NUM,
    X_FACING_ROW_NUM,
    X_FACINGS_NUM,
    X_ORDERABLE_START_DT,
    X_ORDERABLE_END_DT,
    X_RETURN_STRT_DT,
    X_RETURN_END_DT,
    X_DL_CONTRACTIBLE_FLG,
    X_SLOTS_FACING_NUM,
    X_COUNT_CLASS,
    X_GIFT_FACTOR,
    X_ORDER_QTY_FACT  
	from S_PROD_INT 
	where PART_NUM in ('CHG213528_Valid_Product_1' , 'CHG213528_Valid_Product_2')



select * from S_PROD_INT_X where PAR_ROW_ID in (select ROW_ID from S_PROD_INT where PART_NUM in ('CHG213528_Valid_Product_1' , 'CHG213528_Valid_Product_2'))

DELETE FROM S_PROD_INT_X WHERE PAR_ROW_ID IN (SELECT ROW_ID FROM S_PROD_INT WHERE PART_NUM  in ('CHG213528_Valid_Product_1' , 'CHG213528_Valid_Product_2'))

DELETE FROM S_PROD_INT WHERE PART_NUM in ('CHG213528_Valid_Product_1' , 'CHG213528_Valid_Product_2')

DELETE FROM WC_ERRORS_G WHERE FILE_NAME LIKE '%ESPR1901_20220404_10%'


-----------------------------------------CH

SELECT * FROM CX_LEGAL_ENTITY --SET X_LEGAL_NAME_TEXT = 'CHG228033_TEST' WHERE ROW_ID = '1-7RIEU7'


SELECT X_LEGAL_ENTITY_ID, CX.X_LEGAL_NAME_TEXT, * 
FROM S_DOC_AGREE S INNER JOIN CX_LEGAL_ENTITY CX ON CX.ROW_ID = S.X_LEGAL_ENTITY_ID WHERE NAME ='1-125637322'

SELECT * FROM WC_ETL_FILES_G WHERE FILENAME LIKE '%RUCH0722_20220404_10%'

SELECT IF_ROW_STAT, AGR_XLEGALLELEGALN ,* FROM EIM_AGREEMENT WHERE IF_ROW_BATCH_NUM=108000

DELETE FROM WC_ERRORS_G WHERE FILE_NAME LIKE '%RUCH0722_20220404_10%'

SELECT FIELD_VALUE, FIELD_NAME, FAILURE_DESCRIPTION, * FROM WC_ERRORS_G WHERE FILE_NAME LIKE '%RUCH0722_20220404_10%' order by 5, 3

SELECT AGR_STAT_CD, AGR_AGREE_CD FROM PRE_EIM_AGREEMENT_NEW


SELECT NAME, X_LEGAL_ENTITY_ID, * FROM S_DOC_AGREE WHERE NAME = '1-125637322'

SELECT NAME, * FROM S_ORG_EXT WHERE BU_ID ='1-21FD5' NAME ='1-65626426' 


UPDATE S_DOC_AGREE
SET X_LEGAL_ENTITY_ID=NULL 
where NAME IN ('1-125637322')