/*[20161117:RM] CHG099160 - New Version For USA*/
SELECT DISTINCT 
SO.X_EXPORT_STATUS , SO.STATUS_CD , OI.QTY_REQ , OI.DLVRY_STATUS_CD ,TP.NAME, SO.X_SUB_TYPE, OI.ROW_ID
FROM S_ORDER SO
RIGHT JOIN S_ORDER_ITEM OI(NOLOCK) ON SO.ROW_ID = OI.ORDER_ID
INNER JOIN S_ORG_EXT AC(NOLOCK) ON SO.ACCNT_ID = AC.ROW_ID
LEFT OUTER JOIN S_PROD_INT PR(NOLOCK) ON OI.PROD_ID = PR.ROW_ID
LEFT OUTER JOIN S_PRI_LST PL(NOLOCK) ON SO.PRI_LST_ID = PL.ROW_ID
INNER JOIN S_USER SU(NOLOCK) ON SO.CREATED_BY = SU.ROW_ID
LEFT OUTER JOIN S_ORG_EXT SOP(NOLOCK) ON SO.PAYTO_OU_ID = SOP.ROW_ID
INNER JOIN S_ORDER_TYPE TP(NOLOCK) ON SO.ORDER_TYPE_ID = TP.ROW_ID
INNER JOIN S_BU BU(NOLOCK) ON SO.BU_ID = BU.ROW_ID
LEFT OUTER JOIN S_PARTY_REL F2(NOLOCK) ON F2.REL_PARTY_ID = SO.ACCNT_ID
	AND F2.PARTY_ID = SO.PAYTO_OU_ID
LEFT OUTER JOIN S_ADDR_PER AD(NOLOCK) ON AC.PR_ADDR_ID = AD.ROW_ID
LEFT OUTER JOIN S_CONTACT CO(NOLOCK) ON SO.BL_CON_ID = CO.ROW_ID
LEFT OUTER JOIN S_CONTACT_X CX(NOLOCK) ON CO.ROW_ID = CX.PAR_ROW_ID
LEFT OUTER JOIN S_ADDR_PER SAD(NOLOCK) ON SO.BL_ADDR_ID = SAD.ROW_ID
LEFT OUTER JOIN S_CONTACT CONTACT(NOLOCK) ON CONTACT.ROW_ID = SU.ROW_ID
LEFT OUTER JOIN S_POSTN POS(NOLOCK) ON POS.ROW_ID = CONTACT.PR_HELD_POSTN_ID
LEFT OUTER JOIN S_ORDER_X(NOLOCK) ON S_ORDER_X.ROW_ID = SO.ROW_ID
LEFT OUTER JOIN S_CONTACT DELIVERY_CONTACT(NOLOCK) ON SO.CONTACT_ID = DELIVERY_CONTACT.ROW_ID
LEFT OUTER JOIN S_CONTACT_X DELIVERY_CX(NOLOCK) ON DELIVERY_CONTACT.ROW_ID = DELIVERY_CX.PAR_ROW_ID --DEFECT468
LEFT OUTER JOIN S_ORDER PAR_ORD ON PAR_ORD.ROW_ID = SO.PAR_ORDER_ID --CHG053186
WHERE 
(
(SO.X_EXPORT_STATUS IS NULL or SO.X_EXPORT_STATUS = 'In progress') 
AND SO.STATUS_CD IN ('Submitted', 'Returned') 
AND BU.NAME = 'Spain, ES' 
AND OI.QTY_REQ <> 0 
AND OI.DLVRY_STATUS_CD <> 'Sent to Altadis'
AND TP.NAME IN ('Service Order')
and SO.X_SUB_TYPE <> 'Stock Request'
)


--update S_ORDER_ITEM set DLVRY_STATUS_CD = 'Active' where ROW_ID = '1-734M1'

--select DLVRY_STATUS_CD from S_ORDER_ITEM where DLVRY_STATUS_CD <> 'Sent to Altadis'

--update S_ORDER set X_EXPORT_STATUS = NULL where ROW_ID = '1-734LU'
