/*[20161117:RM] CHG099160 - New Version For USA*/
SELECT DISTINCT SO.ORDER_NUM
	,TP.NAME
	,SO.X_SUB_TYPE
	,AC.NAME
	,AC.ALIAS_NAME
	,AC.X_ALIAS_NAME_2
	,SO.REQ_SHIP_DT
	,SO.STATUS_CD
	,OI.X_ORD_TO_CODE
	,OI.LN_NUM
	,--10
	PR.PART_NUM
	,PR.ALIAS_NAME
	,PR.TYPE
	,PL.NAME
	,OI.ADJ_UNIT_PRI
	,OI.QTY_REQ
	,OI.DLVRY_STATUS_CD
	,SO.ORDER_DT
	,SU.LOGIN
	,SOP.ALIAS_NAME
	,--20
	SOP.NAME
	,OI.X_FG_TXN_REASON_CD
	,SO.ROW_ID
	,OI.ROW_ID
	,SO.REV_NUM
	,OI.LN_NUM2
	,F2.X_CUST_NUM
	,--27
	AD.ADDR
	,AD.ZIPCODE
	,AD.CITY
	,OI.X_ACT_RECEIVED_QTY
	,OI.X_ACT_RETURNED_QTY
	,SO.X_TRADE_RETURN_NUM
	,SO.X_BAG_NUM
	,SO.X_CUST_DOCKET_NUM
	,OI.X_QTY_STICK_GRAMS
	,OI.X_RETAILER_PRICE
	,SO.X_WHLS_AUTH_BY
	,SO.DOC_NUM
	,CO.FST_NAME
	,CO.LAST_NAME
	,CO.X_QUALIFICATION
	,CX.ATTRIB_01
	,SAD.ADDR
	,SAD.CITY
	,SAD.COUNTRY
	,SAD.ZIPCODE
	,OI.X_QTY_PACKS_NUM
	,POS.NAME
	,SOP.X_ATTRIB_8
	,AC.X_ATTRIB_8
	,CONTACT.FST_NAME AS CREATED_BY_FST_NAME
	,CONTACT.LAST_NAME AS CREATED_BY_LAST_NAME
	,S_ORDER_X.ATTRIB_45 AS DELIVERY_METHOD
	,DELIVERY_CONTACT.FST_NAME AS DELIVERY_FST_NAME
	,DELIVERY_CONTACT.LAST_NAME AS DELIVERY_LAST_NAME
	,SO.BU_ID AS BU_ID
	,S_ADDR_PER1.ADDR AS ADDR_LINE_1
	,CASE 
		WHEN BU.NAME = 'United Kingdom, UK'
			THEN S_ADDR_PER1.X_ADDR2_TEXT
		ELSE S_ADDR_PER1.ADDR_LINE_2
		END AS ADDR_LINE_2
	,CASE 
		WHEN BU.NAME = 'United Kingdom, UK'
			THEN S_ADDR_PER1.ADDR_LINE_2
		ELSE 'Unspecified'
		END AS ADDR_LINE_3
	,S_ADDR_PER1.CITY AS SHIP_CITY
	,S_ADDR_PER1.ZIPCODE AS SHIP_ZIP_CODE
	,S_ADDR_PER1.X_STATE AS SHIP_STATES
	,S_ADDR_PER1.COUNTRY AS SHIP_COUNTRY
	,S_ADDR_PER1.ADDR_TYPE_CD AS SHIP_ADDR_TYPE
	,DEL_CON.FST_NAME AS DEL_CON_FST_NAME
	,DEL_CON.LAST_NAME AS DEL_CON_LAST_NAME
	,DEL_CON.PER_TITLE AS DEL_CON_TITLE
	,DEL_CON.CON_CD AS DEL_CON_TYPE
	,DEL_CON.X_LANGUAGE_CD AS DEL_CON_LANG
	,--S_LANG.NAMEremoved as per CHG062329
	S_ORDER_X.ATTRIB_53 AS DEL_EMAIL
	,S_ORDER_X.ATTRIB_46 AS DEL_FAX
	,DIGITAL_CON.FST_NAME AS DIGITAL_CON_FST_NAME
	,DIGITAL_CON.LAST_NAME AS DIGITAL_CON_LAST_NAME
	,DIGITAL_CON.PER_TITLE AS DIGITAL_CON_TITLE
	,DIGITAL_CON.CON_CD AS DIGITAL_CON_TYPE
	,DIGITAL_CON.X_LANGUAGE_CD AS DIGITAL_CON_LANG
	--SIGN_LANG.NAME removed as per CHG062329
	,S_ORDER_X.X_SIGNATURE_DT
	,REPLACE(REPLACE(SO.DESC_TEXT, CHAR(10), ' '), CHAR(13), ' ')
	,CASE 
		WHEN AC.OU_TYPE_CD = 'Wholesaler'
			THEN S_ORG_EXT_UTX.OWNERSHIP_CD
		ELSE UTX2.OWNERSHIP_CD
		END AS OWNERSHIP_CD
	,SO.DLVRY_STATUS_CD
	,SO.X_EXPORT_STATUS
	,OI.X_FIX_TAX_AMOUNT -- Calculated field: Quantity * ((Retailer Price + Fix Tax Amount)(1+ % Tax 1 CA + %Tax 2 CA)(1 + % Tax 3 CA)) AS 'X_SALES_AMOUNT'
	,OI.X_TAX_CA_1
	,OI.X_TAX_CA_2
	,OI.X_TAX_CA_3
	,SO.X_TOBACCO_LICN
	,SO.X_BANK_DEPOSIT
	,S_ORDER_X.ATTRIB_03
	,PAR_ORD.ORDER_NUM AS PAR_ORDER_NUM
	,SO.X_ORDER_REASON_CD
	--CHG067147
	,S_ORDER_X.ATTRIB_05
	--CHG067147
	,OI.X_FREE_GOODS_VALUE AS FREE_GOODS_VALUE
	,--CHG069230
	ISNULL((OI.X_VAT_TAX / 100) * (ISNULL((ISNULL((OI.X_RETAILER_PRICE * (100 - ISNULL(OI.DISCNT_PERCENT, 0))) / 100, OI.X_RETAILER_PRICE)) * OI.QTY_REQ, 0)), 0) + ISNULL((ISNULL((OI.X_RETAILER_PRICE * (100 - ISNULL(OI.DISCNT_PERCENT, 0))) / 100, OI.X_RETAILER_PRICE)) * OI.QTY_REQ, 0) AS TOTAL_ORDER_VALUE
	,--CHG069230
	AC.X_ATTRIB_8 AS X_ATTRIB_8
	,--CHG069230
	OI.X_AWARD_POINTS_NUM
	,--CHG069447
	DELIVERY_CONTACT.X_QUALIFICATION AS DELIVERY_QUALIFICATION
	--DEFECT468
	,DELIVERY_CX.ATTRIB_01 AS DELIVERY_PASSPORT
	,--DEFECT468
	DELIVERY_CONTACT.CON_CD AS DELIVERY_CON_TYPE
	,--DEFECT468
	S_ORDER_X.ATTRIB_43 --CHG091484
	,S_ORDER_X.ATTRIB_13 --CHG090896
	,S_REGION.NAME AS GEOGRAPHY_NAME --CHG099160
	,CX_REGION_X.X_ATTRIB_01 --CHG099160
	,AC.X_ATTRIB_2 --CHG099160
	,AC.X_ATTRIB_3 --CHG099160
	--------------CHG107288: New columns to be added 
	,AC.X_LEGAL_ACC_NAME
,S_ORDER_X.ATTRIB_36
,S_ORDER_X.ATTRIB_35
,S_ORDER_X.ATTRIB_34
,SO.X_CHEQUE
,S_ORDER_X.X_CRED_CARD_CONFIRM_FLG
----------CHG128424 ----------------
,OI.X_FEE_01_NUM
,OI.X_FEE_02_NUM
,OI.X_FEE_TYPE_CD

--start v20  - CHG145933 
,S_ORG_EXT_X.ATTRIB_52
,S_ORG_EXT_X.ATTRIB_53
-- End v20 -- CHG145933 
,OI.X_ORDER_UOM_TEXT
,OI.X_ORDER_QUANTITY_NUM
,S_ORDER_X.X_ORDER_CAT_CD
,S_ORDER_ITEM_X.ATTRIB_25
, REL_PROD.PART_NUM
, OI.X_REL_PROD_QTY
, EQUIV_PROD.PART_NUM
, PR.X_GIFT_FACTOR


FROM S_ORDER SO
RIGHT JOIN S_ORDER_ITEM OI(NOLOCK) ON SO.ROW_ID = OI.ORDER_ID
INNER JOIN S_ORG_EXT AC(NOLOCK) ON SO.ACCNT_ID = AC.ROW_ID
LEFT OUTER JOIN S_PROD_INT PR(NOLOCK) ON OI.PROD_ID = PR.ROW_ID
LEFT OUTER JOIN S_PRI_LST PL(NOLOCK) ON SO.PRI_LST_ID = PL.ROW_ID
INNER JOIN S_USER SU(NOLOCK) ON SO.CREATED_BY = SU.ROW_ID
LEFT OUTER JOIN S_ORG_EXT SOP(NOLOCK) ON SO.PAYTO_OU_ID = SOP.ROW_ID
INNER JOIN S_ORDER_TYPE TP(NOLOCK) ON SO.ORDER_TYPE_ID = TP.ROW_ID
INNER JOIN S_BU BU(NOLOCK) ON SO.BU_ID = BU.ROW_ID
LEFT OUTER JOIN S_PARTY_REL F2(NOLOCK) ON F2.REL_PARTY_ID = SO.ACCNT_ID
	AND F2.PARTY_ID = SO.PAYTO_OU_ID
LEFT OUTER JOIN S_ADDR_PER AD(NOLOCK) ON AC.PR_ADDR_ID = AD.ROW_ID
LEFT OUTER JOIN S_CONTACT CO(NOLOCK) ON SO.BL_CON_ID = CO.ROW_ID
LEFT OUTER JOIN S_CONTACT_X CX(NOLOCK) ON CO.ROW_ID = CX.PAR_ROW_ID
LEFT OUTER JOIN S_ADDR_PER SAD(NOLOCK) ON SO.BL_ADDR_ID = SAD.ROW_ID
LEFT OUTER JOIN S_CONTACT CONTACT(NOLOCK) ON CONTACT.ROW_ID = SU.ROW_ID
LEFT OUTER JOIN S_POSTN POS(NOLOCK) ON POS.ROW_ID = CONTACT.PR_HELD_POSTN_ID
LEFT OUTER JOIN S_ORDER_X(NOLOCK) ON S_ORDER_X.ROW_ID = SO.ROW_ID
LEFT OUTER JOIN S_CONTACT DELIVERY_CONTACT(NOLOCK) ON SO.CONTACT_ID = DELIVERY_CONTACT.ROW_ID
LEFT OUTER JOIN S_CONTACT_X DELIVERY_CX(NOLOCK) ON DELIVERY_CONTACT.ROW_ID = DELIVERY_CX.PAR_ROW_ID --DEFECT468
LEFT OUTER JOIN S_ORDER PAR_ORD ON PAR_ORD.ROW_ID = SO.PAR_ORDER_ID --CHG053186
	-------------------DEFECT--------------------- 
LEFT OUTER JOIN S_ADDR_PER S_ADDR_PER1(NOLOCK) ON S_ADDR_PER1.ROW_ID = SO.SHIP_PER_ADDR_ID
LEFT OUTER JOIN S_CONTACT DEL_CON(NOLOCK) ON DEL_CON.ROW_ID = SO.SHIP_CON_ID
--LEFT OUTER JOIN S_LANG(NOLOCK)ON S_LANG.LANG_CD=DEL_CON.PREF_LANG_ID
LEFT OUTER JOIN S_CONTACT DIGITAL_CON(NOLOCK) ON DIGITAL_CON.ROW_ID = S_ORDER_X.X_SIGNED_BY_ID
--LEFT OUTER JOIN S_LANG SIGN_LANG(NOLOCK)ON SIGN_LANG.LANG_CD=DIGITAL_CON.PREF_LANG_ID
LEFT OUTER JOIN S_ORG_EXT_UTX(NOLOCK) ON S_ORG_EXT_UTX.PAR_ROW_ID = SO.ACCNT_ID
LEFT OUTER JOIN S_ORG_EXT_UTX UTX2(NOLOCK) ON UTX2.PAR_ROW_ID = SO.PAYTO_OU_ID
	-------------------CHG099160------------------
LEFT OUTER JOIN S_REGION  ON S_REGION.ROW_ID =OI.X_REGION_ID
LEFT OUTER JOIN CX_REGION_X on CX_REGION_X.PAR_ROW_ID=S_REGION.ROW_ID
	-------------------CHG145933------------------
LEFT OUTER JOIN S_ORG_EXT_X ON S_ORG_EXT_X.PAR_ROW_ID = SO.ACCNT_ID
LEFT OUTER JOIN S_ORDER_ITEM_X ON S_ORDER_ITEM_X.ROW_ID = OI.ROW_ID

LEFT OUTER JOIN S_PROD_INT REL_PROD ON REL_PROD.ROW_ID = OI.X_REL_PROD_ID
LEFT OUTER JOIN  S_PROD_INT EQUIV_PROD  ON EQUIV_PROD.ROW_ID = PR.PR_EQUIV_PROD_ID
WHERE ((SO.X_EXPORT_STATUS IS NULL or SO.X_EXPORT_STATUS = 'In progress') AND SO.STATUS_CD IN ('Submitted', 'Returned') AND BU.NAME = 'Spain, ES' AND OI.QTY_REQ <> 0 AND OI.DLVRY_STATUS_CD <> 'Sent to Altadis' AND TP.NAME IN ('Service Order') and SO.X_SUB_TYPE <> 'Stock Request' ) OR ( (SO.X_EXPORT_STATUS IS NULL or SO.X_EXPORT_STATUS = 'In progress') AND SO.STATUS_CD IN ('To be approved') AND BU.NAME = 'Spain, ES' AND OI.QTY_REQ <> 0 AND OI.DLVRY_STATUS_CD <> 'Sent to Altadis' AND TP.NAME IN ('Service Order') and SO.X_SUB_TYPE = 'Stock Request' )
