SELECT S_ASSESS.ROW_ID AS ROW_ID
	,S_ASSESS.CREATED AS CREATED
	,S_ASSESS.NAME AS NAME
	,S_ASSESS.MAX_SCORE AS MAX_SCORE
	,S_ASSESS.ASSESS_TMPL_NAME AS ASSESS_TMPL_NAME
	,S_ASSESS.X_STATUS_CD AS X_STATUS_CD
	,S_ASSESS.X_LAST_ASSESS_TMPL_FLG AS X_LAST_ASSESS_TMPL_FLG
	,S_TMPL_PLANITEM.BU_ID AS BU_ID
	,S_TMPL_PLANITEM.TYPE_CD AS TYPE_CD
	,S_TMPL_PLANITEM.X_STATUS_CD AS X_STATUS_CD1
	,CASE S_TMPL_PLANITEM.X_SUPERVISOR_CD
		WHEN '1-2-1 Agent'
			THEN 'Y'
		ELSE 'N'
		END AS ASSESS_FLG
	,S_TMPL_PLANITEM.X_CONTACT_ASSESS_FLG AS X_CONTACT_ASSESS_FLG
	,S_ORG_EXT.LOC AS LOC
	,VISIT.X_RETRO_FLG AS X_RETRO_FLG_V
	,VISIT.X_RETRO_DT AS X_RETRO_DT_V
	,ACTIVITY.X_RETRO_FLG AS X_RETRO_FLG_A
	,ACTIVITY.X_RETRO_DT AS X_RETRO_DT_A
	,S_ASSESS.CREATED_BY
	,ACTIVITY.ROW_ID AS ACTIVITY_ID
	,S_TMPL_PLANITEM.DESC_TEXT
	,S_TMPL_PLANITEM.X_SUPERVISOR_CD
	,S_TMPL_PLANITEM.X_CHANNEL_CD
	,ISNULL (S_ASSESS.X_STATUS_UPD_DT, S_ASSESS.CREATED) AS SURVEY_EXECUTION_DT
	,S_ORG_EXT_ASSESS.INTEGRATION_ID
	,S_TMPL_PLANITEM.X_TEMPLATE_TYPE_CD -- CHG107249
	, PREV_ACT.X_OBJ_ACT_FLG  --CHG214588
	, ACTIVITY.X_EVT_STAT_FLG AS  IN_X_EVT_STAT_FLG  --CHG214588
	, PREV_ACT.X_EVT_STAT_FLG AS OBJ_X_EVT_STAT_FLG  --CHG214588
FROM V_ASSESS S_ASSESS
INNER JOIN S_TMPL_PLANITEM ON S_ASSESS.ASSESS_TMPL_ID = S_TMPL_PLANITEM.ROW_ID
LEFT OUTER JOIN S_ORG_EXT ON S_TMPL_PLANITEM.BU_ID = S_ORG_EXT.ROW_ID
LEFT OUTER JOIN S_EVT_ACT ACTIVITY ON S_ASSESS.ACTIVITY_ID = ACTIVITY.ROW_ID
LEFT OUTER JOIN S_EVT_ACT VISIT ON VISIT.ROW_ID = ACTIVITY.PAR_EVT_ID
LEFT OUTER JOIN S_ORG_EXT S_ORG_EXT_ASSESS ON S_ORG_EXT_ASSESS.ROW_ID =  S_ASSESS.ACCNT_ID
LEFT OUTER JOIN S_EVT_ACT PREV_ACT (NOLOCK) ON ACTIVITY.PREV_ACT_ID = PREV_ACT.ROW_ID --CHG214588




---------------------------------------------------------OLD
SELECT S_ASSESS.ROW_ID AS ROW_ID
	,S_ASSESS.CREATED AS CREATED
	,S_ASSESS.NAME AS NAME
	,S_ASSESS.MAX_SCORE AS MAX_SCORE
	,S_ASSESS.ASSESS_TMPL_NAME AS ASSESS_TMPL_NAME
	,S_ASSESS.X_STATUS_CD AS X_STATUS_CD
	,S_ASSESS.X_LAST_ASSESS_TMPL_FLG AS X_LAST_ASSESS_TMPL_FLG
	,S_TMPL_PLANITEM.BU_ID AS BU_ID
	,S_TMPL_PLANITEM.TYPE_CD AS TYPE_CD
	,S_TMPL_PLANITEM.X_STATUS_CD AS X_STATUS_CD1
	,CASE S_TMPL_PLANITEM.X_SUPERVISOR_CD
		WHEN '1-2-1 Agent'
			THEN 'Y'
		ELSE 'N'
		END AS ASSESS_FLG
	,S_TMPL_PLANITEM.X_CONTACT_ASSESS_FLG AS X_CONTACT_ASSESS_FLG
	,S_ORG_EXT.LOC AS LOC
	,VISIT.X_RETRO_FLG AS X_RETRO_FLG_V
	,VISIT.X_RETRO_DT AS X_RETRO_DT_V
	,ACTIVITY.X_RETRO_FLG AS X_RETRO_FLG_A
	,ACTIVITY.X_RETRO_DT AS X_RETRO_DT_A
	,S_ASSESS.CREATED_BY
	,ACTIVITY.ROW_ID AS ACTIVITY_ID
	,S_TMPL_PLANITEM.DESC_TEXT
	,S_TMPL_PLANITEM.X_SUPERVISOR_CD
	,S_TMPL_PLANITEM.X_CHANNEL_CD
	,ISNULL (S_ASSESS.X_STATUS_UPD_DT, S_ASSESS.CREATED) AS SURVEY_EXECUTION_DT
	,S_ORG_EXT_ASSESS.INTEGRATION_ID
	,S_TMPL_PLANITEM.X_TEMPLATE_TYPE_CD -- CHG107249
	, PREV_ACT.X_OBJ_ACT_FLG
	, ACTIVITY.X_EVT_STAT_FLG
	, PREV_ACT.X_EVT_STAT_FLG
FROM V_ASSESS S_ASSESS
INNER JOIN S_TMPL_PLANITEM ON S_ASSESS.ASSESS_TMPL_ID = S_TMPL_PLANITEM.ROW_ID
LEFT OUTER JOIN S_ORG_EXT ON S_TMPL_PLANITEM.BU_ID = S_ORG_EXT.ROW_ID
LEFT OUTER JOIN S_EVT_ACT ACTIVITY ON S_ASSESS.ACTIVITY_ID = ACTIVITY.ROW_ID
LEFT OUTER JOIN S_EVT_ACT VISIT ON VISIT.ROW_ID = ACTIVITY.PAR_EVT_ID
LEFT OUTER JOIN S_ORG_EXT S_ORG_EXT_ASSESS ON S_ORG_EXT_ASSESS.ROW_ID =  S_ASSESS.ACCNT_ID
LEFT OUTER JOIN S_EVT_ACT PREV_ACT (NOLOCK) ON ACTIVITY.PREV_ACT_ID = PREV_ACT.ROW_ID