SELECT DISTINCT
 CX_ACT_AGR_ITEM.ROW_ID, 
 CX_ACT_AGR_ITEM.LAST_UPD,
 CX_ACT_AGR_ITEM.MODIFICATION_NUM,
 CX_ACT_AGR_ITEM.DB_LAST_UPD,
IMG.ETL_PROC_WID
FROM 
 CX_ACT_AGR_ITEM, 
 S_EVT_ACT RA,
 S_EVT_ACT COM,
 S_ETL_I_IMG_20  IMG
WHERE 
 (
 IMG.ROW_ID = RA.ROW_ID 
 AND
 RA.PAR_EVT_ID = COM.PAR_EVT_ID
 AND  
 CX_ACT_AGR_ITEM.X_ACTIVITY_ID = COM.ROW_ID
 AND RA.EVT_STAT_CD='Done'
  AND RA.TODO_CD IN ('Retail Audit' ,'Retail Audit Location' )
AND COM.EVT_STAT_CD='Done' --CHG060377
 )
 AND  NOT EXISTS   
 ( SELECT 'X' 
  FROM 
  S_ETL_I_IMG_169 IMG1
  WHERE  
  IMG1.ROW_ID = CX_ACT_AGR_ITEM.ROW_ID
 )

UNION

SELECT DISTINCT
 CX_ACT_AGR_ITEM.ROW_ID, 
 CX_ACT_AGR_ITEM.LAST_UPD,
 CX_ACT_AGR_ITEM.MODIFICATION_NUM,
 CX_ACT_AGR_ITEM.DB_LAST_UPD,
IMG.ETL_PROC_WID
FROM 
 CX_ACT_AGR_ITEM, 
 S_EVT_ACT RA,
 S_EVT_ACT COM,
 S_ETL_I_IMG_20 IMG
WHERE 
 (
 IMG.ROW_ID = COM.ROW_ID 
 AND
 RA.PAR_EVT_ID = COM.PAR_EVT_ID
 AND 
 CX_ACT_AGR_ITEM.X_ACTIVITY_ID = COM.ROW_ID
 AND RA.EVT_STAT_CD='Done'
 AND RA.TODO_CD IN ('Retail Audit' ,'Retail Audit Location' )
AND COM.EVT_STAT_CD='Done'
 )
 AND NOT EXISTS 
 ( SELECT 'X' 
 FROM 
 S_ETL_I_IMG_169 IMG1
 WHERE 
 IMG1.ROW_ID = CX_ACT_AGR_ITEM.ROW_ID
 )

UNION --ADDED UNION AS PER CHG214588 

SELECT S_EVT_ACT.ROW_ID
	,S_EVT_ACT.MODIFICATION_NUM
	,S_EVT_ACT.LAST_UPD
	,S_EVT_ACT.DB_LAST_UPD
	,IMG.ETL_PROC_WID
FROM S_EVT_ACT
	,S_ETL_I_IMG_20 IMG
WHERE IMG.ROW_ID = S_EVT_ACT.PREV_ACT_ID
	AND S_EVT_ACT.X_BU_ID IN (
		SELECT MARKET_ID
		FROM WC_ETL_MARKET_PARAM_G
		WHERE ETL_PROCESS_NAME = 'AUX_IMG PREV_ACT_ID - S_EVT_ACT'
			AND EXECUTION_FLG = 'Y'
		)




--OLD

SELECT DISTINCT
 CX_ACT_AGR_ITEM.ROW_ID, 
 CX_ACT_AGR_ITEM.LAST_UPD,
 CX_ACT_AGR_ITEM.MODIFICATION_NUM,
 CX_ACT_AGR_ITEM.DB_LAST_UPD,
IMG.ETL_PROC_WID
FROM 
 CX_ACT_AGR_ITEM, 
 S_EVT_ACT RA,
 S_EVT_ACT COM,
 S_ETL_I_IMG_20  IMG
WHERE 
 (
 IMG.ROW_ID = RA.ROW_ID 
 AND
 RA.PAR_EVT_ID = COM.PAR_EVT_ID
 AND  
 CX_ACT_AGR_ITEM.X_ACTIVITY_ID = COM.ROW_ID
 AND RA.EVT_STAT_CD='Done'
  AND RA.TODO_CD IN ('Retail Audit' ,'Retail Audit Location' )
AND COM.EVT_STAT_CD='Done' --CHG060377
 )
 AND  NOT EXISTS   
 ( SELECT 'X' 
  FROM 
  S_ETL_I_IMG_169 IMG1
  WHERE  
  IMG1.ROW_ID = CX_ACT_AGR_ITEM.ROW_ID
 )

UNION

SELECT DISTINCT
 CX_ACT_AGR_ITEM.ROW_ID, 
 CX_ACT_AGR_ITEM.LAST_UPD,
 CX_ACT_AGR_ITEM.MODIFICATION_NUM,
 CX_ACT_AGR_ITEM.DB_LAST_UPD,
IMG.ETL_PROC_WID
FROM 
 CX_ACT_AGR_ITEM, 
 S_EVT_ACT RA,
 S_EVT_ACT COM,
 S_ETL_I_IMG_20 IMG
WHERE 
 (
 IMG.ROW_ID = COM.ROW_ID 
 AND
 RA.PAR_EVT_ID = COM.PAR_EVT_ID
 AND 
 CX_ACT_AGR_ITEM.X_ACTIVITY_ID = COM.ROW_ID
 AND RA.EVT_STAT_CD='Done'
 AND RA.TODO_CD IN ('Retail Audit' ,'Retail Audit Location' )
AND COM.EVT_STAT_CD='Done'
 )
 AND NOT EXISTS 
 ( SELECT 'X' 
 FROM 
 S_ETL_I_IMG_169 IMG1
 WHERE 
 IMG1.ROW_ID = CX_ACT_AGR_ITEM.ROW_ID
 )
