--If exist drop the stating tables
DROP TABLE StagingDB.dbo.CO_TO_BE_DELETED
DROP TABLE StagingDB.dbo.CO_IMPACTED_TAB_TO_BACKUP

--Populate Impacted ROW_ID in a staging table.
SELECT ROW_ID 
INTO StagingDB.dbo.CO_TO_BE_DELETED
FROM S_DOC_AGREE
WHERE ROW_ID IN  ('xxxx') --Contact UIDs provided by the client.

--Verify that the staging table was correctly populated.
SELECT * FROM StagingDB.dbo.CO_TO_BE_DELETED

--Verify impacted tables 
SELECT * FROM (
SELECT 'CX_AGR_PL_ITEM' AS TAB, COUNT(1) AS REC_COUNT, 'PAR_ROW_ID' AS COL FROM CX_AGR_PL_ITEM WHERE PAR_ROW_ID in (SELECT ROW_ID  FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'CX_AGR_PTS_TXN',COUNT(1), 'PAR_ROW_ID'		FROM CX_AGR_PTS_TXN		WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_AGREE_AWARDS',COUNT(1), 'PAR_ROW_ID'		FROM CX_AGREE_AWARDS	WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_EVENTS',		COUNT(1), 'X_AGREE_ID'		FROM CX_EVENTS			WHERE X_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_PTS_TXN',	COUNT(1), 'X_AGREE_ID'		FROM CX_PTS_TXN			WHERE X_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_PTS_TXN_REL',COUNT(1), 'X_FROM_AGREE_ID'	FROM CX_PTS_TXN_REL		WHERE X_FROM_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'CX_TMP_INI_PRD',COUNT(1), 'PAR_ROW_ID'		FROM CX_TMP_INI_PRD		WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_VM',			COUNT(1), 'AGREE_ID'		FROM CX_VM				WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ACCNT_AGR_CUT',COUNT(1), 'AGREE_ID'		FROM S_ACCNT_AGR_CUT	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGR_TERM_DESC',COUNT(1), 'AGREE_ID'		FROM S_AGR_TERM_DESC	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_APPR',	COUNT(1), 'DOC_AGREE_ID'	FROM S_AGREE_APPR	WHERE DOC_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_BNFT',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_BNFT	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_COND',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_COND	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_ITEM',	COUNT(1), 'DOC_AGREE_ID'	FROM S_AGREE_ITEM	WHERE DOC_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_PAY',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_PAY	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_POSTN',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_POSTN	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_PRI_LOG',COUNT(1), 'AGREE_ID'		FROM S_AGREE_PRI_LOG WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_TERMS',	COUNT(1), 'PAR_ROW_ID'		FROM S_AGREE_TERMS	WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_VMSG',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_VMSG	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ALERT_CUT',	COUNT(1), 'CONTRACT_ID'     FROM S_ALERT_CUT	WHERE CONTRACT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ASSET',		COUNT(1), 'CUR_AGREE_ID '   FROM S_ASSET		WHERE CUR_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_CL_ACTEXC_PMT', COUNT(1), 'CONTRACT_ID'   FROM S_CL_ACTEXC_PMT WHERE CONTRACT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DISCNT',		COUNT(1), 'SD_ID'			FROM S_DISCNT		WHERE SD_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_AGREE', COUNT(1), 'ROW_ID'			FROM S_DOC_AGREE	WHERE ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_AGREE_ATT', COUNT(1), 'PAR_ROW_ID'	FROM S_DOC_AGREE_ATT WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_AGREE_BU', COUNT(1), 'AGREEMENT_ID'	FROM S_DOC_AGREE_BU WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_AGREE_XM', COUNT(1), 'PAR_ROW_ID'		FROM S_DOC_AGREE_XM WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_QUOTE',	COUNT(1), 'AGREE_SD_ID'		FROM S_DOC_QUOTE	WHERE AGREE_SD_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ENTLMNT',		COUNT(1), 'PAR_AGREE_ID'	FROM S_ENTLMNT		WHERE PAR_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_EVT_ACT',		COUNT(1), 'AGREEMENT_ID'	FROM S_EVT_ACT		WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_FCST_ITEM',	COUNT(1), 'AGREE_ID'		FROM S_FCST_ITEM	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_INVOICE',		COUNT(1), 'AGREEMENT_ID'	FROM S_INVOICE		WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_INVOICE_CHRG', COUNT(1), 'AGREEMENT_ID'	FROM S_INVOICE_CHRG WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_INVOICE_ITEM', COUNT(1), 'AGREEMENT_ID'	FROM S_INVOICE_ITEM WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_NOTE_AGR_CUT', COUNT(1), 'SRC_ROW_ID'		FROM S_NOTE_AGR_CUT WHERE SRC_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_NOTE_AGREE',	COUNT(1), 'SRC_ROW_ID'		FROM S_NOTE_AGREE	WHERE SRC_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ORDER',		COUNT(1), 'AGREE_ID'		FROM S_ORDER		WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ORDER_ITEM',	COUNT(1), 'AGREE_ID'		FROM S_ORDER_ITEM	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ORDER_ITEM_OM', COUNT(1), 'PREV_DOC_AGREE_ID'  FROM S_ORDER_ITEM_OM WHERE PREV_DOC_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_QUOTE_ITEM',	COUNT(1), 'CUR_AGREE_ID'	FROM S_QUOTE_ITEM	WHERE CUR_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_QUOTE_ITEM_OM', COUNT(1), 'PREV_DOC_AGREE_ID'  FROM S_QUOTE_ITEM_OM WHERE PREV_DOC_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_QUOTE_SOLN', COUNT(1), 'CUR_AGREE_ID'		FROM S_QUOTE_SOLN	WHERE CUR_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_REVN',		COUNT(1), 'AGREE_ID'		FROM S_REVN			WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_SRC_PAYMENT', COUNT(1), 'CONTRACT_ID'		FROM S_SRC_PAYMENT	WHERE CONTRACT_ID in(SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_WRNTY_CLM_IT', COUNT(1), 'AGREEMENT_ID'	FROM S_WRNTY_CLM_IT WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_WRNTY_IT_PROD', COUNT(1), 'DOC_AGREE_ID'	FROM S_WRNTY_IT_PROD WHERE DOC_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)
)v where REC_COUNT > 0 


--Populate staging table with tables impacted and rows.
SELECT * INTO StagingDB.dbo.CO_IMPACTED_TAB_TO_BACKUP FROM (
SELECT 'CX_AGR_PL_ITEM' AS TAB, COUNT(1) AS REC_COUNT, 'PAR_ROW_ID' AS COL FROM CX_AGR_PL_ITEM WHERE PAR_ROW_ID in (SELECT ROW_ID  FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'CX_AGR_PTS_TXN',COUNT(1), 'PAR_ROW_ID'		FROM CX_AGR_PTS_TXN		WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_AGREE_AWARDS',COUNT(1), 'PAR_ROW_ID'		FROM CX_AGREE_AWARDS	WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_EVENTS',		COUNT(1), 'X_AGREE_ID'		FROM CX_EVENTS			WHERE X_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_PTS_TXN',	COUNT(1), 'X_AGREE_ID'		FROM CX_PTS_TXN			WHERE X_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_PTS_TXN_REL',COUNT(1), 'X_FROM_AGREE_ID'	FROM CX_PTS_TXN_REL		WHERE X_FROM_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'CX_TMP_INI_PRD',COUNT(1), 'PAR_ROW_ID'		FROM CX_TMP_INI_PRD		WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)	UNION
SELECT 'CX_VM',			COUNT(1), 'AGREE_ID'		FROM CX_VM				WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ACCNT_AGR_CUT',COUNT(1), 'AGREE_ID'		FROM S_ACCNT_AGR_CUT	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGR_TERM_DESC',COUNT(1), 'AGREE_ID'		FROM S_AGR_TERM_DESC	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_APPR',	COUNT(1), 'DOC_AGREE_ID'	FROM S_AGREE_APPR	WHERE DOC_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_BNFT',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_BNFT	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_COND',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_COND	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_ITEM',	COUNT(1), 'DOC_AGREE_ID'	FROM S_AGREE_ITEM	WHERE DOC_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_PAY',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_PAY	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_POSTN',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_POSTN	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_PRI_LOG',COUNT(1), 'AGREE_ID'		FROM S_AGREE_PRI_LOG WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_TERMS',	COUNT(1), 'PAR_ROW_ID'		FROM S_AGREE_TERMS	WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_AGREE_VMSG',	COUNT(1), 'AGREE_ID'		FROM S_AGREE_VMSG	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ALERT_CUT',	COUNT(1), 'CONTRACT_ID'     FROM S_ALERT_CUT	WHERE CONTRACT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ASSET',		COUNT(1), 'CUR_AGREE_ID '   FROM S_ASSET		WHERE CUR_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_CL_ACTEXC_PMT', COUNT(1), 'CONTRACT_ID'   FROM S_CL_ACTEXC_PMT WHERE CONTRACT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DISCNT',		COUNT(1), 'SD_ID'			FROM S_DISCNT		WHERE SD_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_AGREE', COUNT(1), 'ROW_ID'			FROM S_DOC_AGREE	WHERE ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_AGREE_ATT', COUNT(1), 'PAR_ROW_ID'	FROM S_DOC_AGREE_ATT WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_AGREE_BU', COUNT(1), 'AGREEMENT_ID'	FROM S_DOC_AGREE_BU WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_AGREE_XM', COUNT(1), 'PAR_ROW_ID'		FROM S_DOC_AGREE_XM WHERE PAR_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_DOC_QUOTE',	COUNT(1), 'AGREE_SD_ID'		FROM S_DOC_QUOTE	WHERE AGREE_SD_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ENTLMNT',		COUNT(1), 'PAR_AGREE_ID'	FROM S_ENTLMNT		WHERE PAR_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_EVT_ACT',		COUNT(1), 'AGREEMENT_ID'	FROM S_EVT_ACT		WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_FCST_ITEM',	COUNT(1), 'AGREE_ID'		FROM S_FCST_ITEM	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_INVOICE',		COUNT(1), 'AGREEMENT_ID'	FROM S_INVOICE		WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_INVOICE_CHRG', COUNT(1), 'AGREEMENT_ID'	FROM S_INVOICE_CHRG WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_INVOICE_ITEM', COUNT(1), 'AGREEMENT_ID'	FROM S_INVOICE_ITEM WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_NOTE_AGR_CUT', COUNT(1), 'SRC_ROW_ID'		FROM S_NOTE_AGR_CUT WHERE SRC_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_NOTE_AGREE',	COUNT(1), 'SRC_ROW_ID'		FROM S_NOTE_AGREE	WHERE SRC_ROW_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ORDER',		COUNT(1), 'AGREE_ID'		FROM S_ORDER		WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ORDER_ITEM',	COUNT(1), 'AGREE_ID'		FROM S_ORDER_ITEM	WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_ORDER_ITEM_OM', COUNT(1), 'PREV_DOC_AGREE_ID'  FROM S_ORDER_ITEM_OM WHERE PREV_DOC_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_QUOTE_ITEM',	COUNT(1), 'CUR_AGREE_ID'	FROM S_QUOTE_ITEM	WHERE CUR_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_QUOTE_ITEM_OM', COUNT(1), 'PREV_DOC_AGREE_ID'  FROM S_QUOTE_ITEM_OM WHERE PREV_DOC_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_QUOTE_SOLN', COUNT(1), 'CUR_AGREE_ID'		FROM S_QUOTE_SOLN	WHERE CUR_AGREE_ID  in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_REVN',		COUNT(1), 'AGREE_ID'		FROM S_REVN			WHERE AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_SRC_PAYMENT', COUNT(1), 'CONTRACT_ID'		FROM S_SRC_PAYMENT	WHERE CONTRACT_ID in(SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_WRNTY_CLM_IT', COUNT(1), 'AGREEMENT_ID'	FROM S_WRNTY_CLM_IT WHERE AGREEMENT_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED) UNION
SELECT 'S_WRNTY_IT_PROD', COUNT(1), 'DOC_AGREE_ID'	FROM S_WRNTY_IT_PROD WHERE DOC_AGREE_ID in (SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)
)v WHERE REC_COUNT > 0 

--Check impacted tables with impacted number of records
SELECT * FROM StagingDB.dbo.CO_IMPACTED_TAB_TO_BACKUP

---Generate back up script.Replace with correct incident number and date.INCXXX_YYYMMDD .E.g INC0012010_20171002
SELECT 'SELECT * INTO StagingDB.dbo.'+TAB+'_INCXXXXX_YYYMMDD  FROM ' + TAB+ ' WHERE '+COL +' IN(SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)'
FROM StagingDB.dbo.CO_IMPACTED_TAB_TO_BACKUP

--E.g.
SELECT * INTO StagingDB.dbo.S_AGREE_ITEM_INCXXXXX_YYYMMDD  FROM S_AGREE_ITEM WHERE DOC_AGREE_ID IN(SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)
SELECT * INTO StagingDB.dbo.S_DOC_AGREE_INCXXXXX_YYYMMDD  FROM S_DOC_AGREE WHERE ROW_ID IN(SELECT ROW_ID FROM StagingDB.dbo.CO_TO_BE_DELETED)


--Valid backup was correctly done. Replace with correct incident number and date.INCXXX_YYYMMDD 
SELECT 'SELECT ''' + name+''' ,COUNT(1) FROM StagingDB.dbo.'+name  FROM StagingDB.sys.objects where name like '%_INCXXXXX_YYYMMDD%'

SELECT 'S_AGREE_ITEM_INCXXXXX_YYYMMDD' ,COUNT(1) FROM StagingDB.dbo.S_AGREE_ITEM_INCXXXXX_YYYMMDD
SELECT 'S_DOC_AGREE_INCXXXXX_YYYMMDD' ,COUNT(1) FROM StagingDB.dbo.S_DOC_AGREE_INCXXXXX_YYYMMDD

