select 

ORD_BI, 
ORD_ORDER_NUM,
ORD_ORDTYP_NAME,
ORD_REV_NUM,
X_ORDER_CAT_CD

from EIM_ORDER_DTL

 O.ORDER_CAT_CD, P.VAL X_ORDER_CAT_CD , OX.X_ORDER_CAT_CD, O.X_SUB_TYPE

 DROP TABLE A_TAB
SELECT O.ROW_ID,
O.BU_ID ORD_BI, 
BU.NAME  ORD_BU,
O.ORDER_NUM ORD_ORDER_NUM,
OT.NAME ORD_ORDTYP_NAME,
O. REV_NUM ORD_REV_NUM,
 P.VAL  X_ORDER_CAT_CD, C.HIGH, P.HIGH
 --INTO dbo.A_TAB

FROM S_ORDER O
LEFT OUTER JOIN S_ORDER_X (NOLOCK) OX ON O.ROW_ID = OX.ROW_ID
INNER JOIN S_BU BU ON O.BU_ID = BU.ROW_ID
INNER JOIN S_ORDER_TYPE OT ON O.ORDER_TYPE_ID = OT.ROW_ID 

INNER JOIN S_LST_OF_VAL C ON C.VAL = O.X_SUB_TYPE
INNER JOIN S_LST_OF_VAL P ON P.ROW_ID = C.PAR_ROW_ID
WHERE C.TYPE = 'JTI_SUBTYPE_TYPE'
AND C.LANG_ID = 'ENU'
--AND O.ORDER_CAT_CD ='Material'
AND P.LANG_ID = 'ENU'
AND P.ACTIVE_FLG = 'Y'
AND OX.X_ORDER_CAT_CD IS NULL
-------------

SELECT O.ROW_ID,
O.BU_ID ORD_BI, 
BU.NAME  ORD_BU,
O.ORDER_NUM ORD_ORDER_NUM,
OT.NAME ORD_ORDTYP_NAME,
O. REV_NUM ORD_REV_NUM,
 P.VAL  O_X_ORDER_CAT_CD 
 , OX.X_ORDER_CAT_CD  OX_X_ORDER_CAT_CD
FROM S_ORDER O
LEFT OUTER JOIN S_ORDER_X (NOLOCK) OX ON O.ROW_ID = OX.ROW_ID
INNER JOIN S_BU BU ON O.BU_ID = BU.ROW_ID
INNER JOIN S_ORDER_TYPE OT ON O.ORDER_TYPE_ID = OT.ROW_ID 
INNER JOIN S_LST_OF_VAL C ON C.VAL = O.X_SUB_TYPE
INNER JOIN S_LST_OF_VAL P ON P.ROW_ID = C.PAR_ROW_ID
WHERE C.TYPE = 'JTI_SUBTYPE_TYPE'
AND C.LANG_ID = 'ENU'
AND O.ORDER_CAT_CD ='Material'
AND P.LANG_ID = 'ENU'
AND P.ACTIVE_FLG = 'Y'
AND OX.X_ORDER_CAT_CD IS NULL

--




UPDATE WC_PROCESS_PARAMS_G
SET ACTIVE_FLG = 'Y'
WHERE PROCESS = 'Material_Order_Update'
	AND BU_ID IN (
		SELECT ROW_ID
		FROM S_BU
		WHERE NAME IN (
				'Spain, ES'
				,'Czech Republic, CZ'
				)
		)

		UPDATE WC_PROCESS_PARAMS_G
SET ACTIVE_FLG = 'Y'
WHERE PROCESS = 'Material_Order_Promotion'
	AND BU_ID IN (
		SELECT ROW_ID
		FROM S_BU
		WHERE NAME IN (
				'Spain, ES'
				,'Czech Republic, CZ'
				)
		)



SELECT  IF_ROW_STAT,* FROM EIM_ORDER_DTL (NOLOCK) WHERE IF_ROW_BATCH_NUM BETWEEN 100000000 AND 100000999


SELECT X_ORDER_CAT_CD, * FROM S_ORDER_X WHERE ROW_ID IN ('1-4KD1S7','1-7VV219','1-7S6IRX','1-7SX0YY')
SELECT X_SUB_TYPE, * FROM S_ORDER WHERE ROW_ID IN ('1-4KD1S7','1-7VV219','1-7S6IRX','1-7SX0YY')


update S_ORDER_X set X_ORDER_CAT_CD = NULL where ROW_ID in ('1-4KD1S7','1-7VV219','1-7S6IRX','1-7SX0YY')


