


SELECT O.ROW_ID,
O.BU_ID ORD_BI, 
BU.NAME  ORD_BU,
O.ORDER_NUM ORD_ORDER_NUM,
OT.NAME ORD_ORDTYP_NAME,
O. REV_NUM ORD_REV_NUM,
O.X_PROMO_PRG_ID,
O.PROMO_ID,
O.ACCNT_ID
--P.PAR_SRC_ID, P.TMPL_ID
 --INTO dbo.A_TAB
 --UPDATE O SET PROMO_ID = NULL
FROM S_ORDER O
LEFT JOIN S_BU BU ON O.BU_ID = BU.ROW_ID
LEFT JOIN S_ORDER_TYPE OT ON O.ORDER_TYPE_ID = OT.ROW_ID 
WHERE O.X_PROMO_PRG_ID IS NOT NULL 




and O.PROMO_ID IS NULL

update S_ORDER set PROMO_ID = NULL where ROW_ID = '1-139ZRN'

SELECT NAME ,* FROM S_SRC WHERE ROW_ID = '1-139ZPC'
SELECT NAME, * 
FROM S_SRC WHERE PAR_SRC_ID  ='1-139ZPC'

SELECT NAME, * FROM S_SRC WHERE ROW_ID  ='1-139ZPC'

SELECT NAME, * 
--DELETE
FROM S_SRC WHERE PAR_SRC_ID  ='1-1A29K-0'

SELECT NAME, * 
--DELETE
FROM S_SRC WHERE ROW_ID  ='1-1A29K-0'


INSERT INTO EIM_ORDER (
ROW_ID
	,IF_ROW_STAT
	,IF_ROW_BATCH_NUM,
ORD_ORDER_NUM,
ORD_REV_NUM,
ORD_ORDTYP_NAME,
ORD_BU,
ORD_PROMO_SRC_BU,
ORD_PROMO_SRC_NUM,
ORD_PROMO_SUB_TYPE
)

SELECT S.ROW_ID,
 'FOR_IMPORT'
, 11--@PROMO_IF_ROW_BATCH_NUM
, S.ORDER_NUM ORD_ORDER_NUM
, S. REV_NUM ORD_REV_NUM
, OT.NAME ORD_ORDTYP_NAME
, BU.NAME  ORD_BU
, S.BU_ID ORD_BI
, PLAN_ACCNT.ORG_BU
, PLAN_ACCNT.SRC_NUM
, PLAN_ACCNT.SUB_TYPE
FROM S_ORDER S(NOLOCK)
INNER JOIN S_ORG_EXT O(NOLOCK) ON S.ACCNT_ID = O.ROW_ID
LEFT JOIN S_BU BU ON O.BU_ID = BU.ROW_ID
LEFT JOIN S_ORDER_TYPE OT ON S.ORDER_TYPE_ID = OT.ROW_ID
INNER JOIN WC_MAT_PLAN_PROMO_MERCH_PRE PLAN_ACCNT(NOLOCK) ON S.X_PROMO_PRG_ID = PLAN_ACCNT.PROG_ID AND S.ACCNT_ID = PLAN_ACCNT.ACCNT_ID
 
WHERE NOT EXISTS (
		SELECT 1
		FROM S_SRC SRC(NOLOCK)
		WHERE SRC.SUB_TYPE IN (
				'PLAN_ACCOUNT_PROMOTION'
				,'PLAN_ACCOUNT_MERCHANDISING'
				)
			AND SRC.TMPL_ID = S.X_PROMO_PRG_ID
			AND SRC.PR_ACCNT_ID = S.ACCNT_ID
		)
AND S.PROMO_ID IS NULL

SELECT * FROM WC_MAT_PLAN_PROMO_MERCH_PRE

Spain, ES



1-139ZPC1-139ZP3


ROW_ID	ORD_BI	ORD_BU	ORD_ORDER_NUM	ORD_ORDTYP_NAME	ORD_REV_NUM	X_PROMO_PRG_ID	PROMO_ID
1-139ZRN	1-CSNG	Spain, ES	1-65971283	Material Order	1.0000000	1-139ZPC	1-139ZPJ

EXEC sp_Material_Promotion

SELECT NAME FROM S_ORG_EXT WHERE ROW_ID = '1-139ZP3'

SELECT PR_ACCNT_ID, * 
UPDATE S_SRC SET PR_ACCNT_ID = '1-139ZP3A'
FROM S_SRC WHERe '1-139ZPC' IN (TMPL_ID, PAR_SRC_ID) AND PR_ACCNT_ID = '1-139ZP3'


SELECT PR_ACCNT_ID, * 

UPDATE S_SRC SET PR_ACCNT_ID = '1-139ZP3A'
FROM S_SRC WHERe '1-139ZPJ' IN (TMPL_ID, PAR_SRC_ID) AND PR_ACCNT_ID = '1-139ZP3'





-- AND O.ORDER_CAT_CD ='Material' AND

SELECT TMPL_ID, PR_ACCNT_ID FROM S_SRC WHERE ROW_ID = '1-139ZPJ'


SELECT TMPL_ID, PR_ACCNT_ID, SUB_TYPE FROM S_SRC WHERE PR_ACCNT_ID = '1-139ZP3'

SELECT 

1-139ZP3

SELECT SUB_TYPE, * FROM S_SRC WHERE ROW_ID = '1-12R2JF'

SELECT SUB_TYPE, * FROM S_SRC WHERE TMPL_ID = '1-3P4G0S'


SELECT SUB_TYPE, * FROM S_SRC WHERE PAR_SRC_ID = '1-12R2JF'

UPDATE S_ORDER SET X_PROMO_PRG_ID = '1-139ZPC'
WHERE ROW_ID = '1-139ZRN'


SELECT 'SELECT * FROM '+NAME , * FROM sys.tables where name like 'WC_MAT%'

SELECT 'drop table  '+NAME FROM sys.tables where name like 'WC_MAT%'


drop table  WC_MAT_EVENTS_PROMO_MERCH_PRE
drop table  WC_MAT_PLAN_INCENTIVE_PROMO_PRE
drop table  WC_MAT_PLAN_MERCH_ITEM_PROMO_MERCH_PRE
drop table  WC_MAT_PLAN_PROMO_MERCH_PRE
drop table  WC_MAT_PROD_PROMO_MERCH_PRE
drop table  WC_MAT_PROMO_MDF_PRE
drop table  WC_MAT_PROMO_MERCH_PRE
drop table  WC_MAT_PROMO_TACTIC_PRE


