::[20161125:RM] INC1792027 New variable SEARCH_SPEC added for "JTI OTM Submit Order" workflow with separator ;
::Version: 1.0
::Author: Rakotoasimbahoaka Misa
::Date: 05/04/2015
::Last modified: 05/15/2015
::Change: CHG071953 - Settings for all user name and password

ECHO OFF

SET USER_NAME=SIEBWKF_BE_DEV SIEBWKF_CH_DEV	SIEBWKF_FR_DEV SIEBWKF_IT_DEV SIEBWKF_NL_DEV SIEBWKF_AT_DEV SIEBWKF_CA_DEV SIEBWKF_CI_DEV SIEBWKF_ES_DEV SIEBWKF_IE_DEV SIEBWKF_PT_DEV SIEBWKF_SE_DEV SIEBWKF_US_DEV SIEBWKF_UK_DEV SIEBWKF_GE_DEV SIEBWKF_GR_DEV SIEBWKF_PL_DEV SIEBWKF_WW_DEV SIEBWKF_CZ_DEV SIEBWKF_RO_DEV SIEBWKF_SB_DEV SIEBWKF_UA_DEV SIEBWKF_KR_DEV SIEBWKF_KZ_DEV SIEBWKF_MY_DEV SIEBWKF_TW_DEV SIEBWKF_RU_DEV
::SET PASSWORD=SIEBWKF_BE_DEV SIEBWKF_CH_DEV	SIEBWKF_FR_DEV SIEBWKF_IT_DEV SIEBWKF_NL_DEV SIEBWKF_AT_DEV SIEBWKF_CA_DEV SIEBWKF_CI_DEV SIEBWKF_ES_DEV SIEBWKF_IE_DEV SIEBWKF_PT_DEV SIEBWKF_SE_DEV SIEBWKF_US_DEV SIEBWKF_UK_DEV SIEBWKF_GE_DEV SIEBWKF_GR_DEV SIEBWKF_PL_DEV SIEBWKF_WW_DEV SIEBWKF_CZ_DEV SIEBWKF_RO_DEV SIEBWKF_SB_DEV SIEBWKF_UA_DEV SIEBWKF_KR_DEV SIEBWKF_KZ_DEV SIEBWKF_MY_DEV SIEBWKF_TW_DEV SIEBWKF_RU_DEV

::SET SEARCH_SPEC=;;"[Status] =  LookupValue(""FS_ORDER_STATUS"", ""Mobile Submitted"") AND [Primary Organization Id]=""1-2O83""";;;;;;"[Status] =  LookupValue(""FS_ORDER_STATUS"", ""Mobile Submitted"") AND [Primary Organization Id]=""1-1ISXG""";;;;;;;;;;;;;;;;;;;