IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_ASSORTMENT_SCD_SK]'))
DROP TABLE [dbo].[WC_ASSORTMENT_SCD_SK]
GO 

CREATE TABLE [dbo].[WC_ASSORTMENT_SCD_SK](
	[ROW_WID] [numeric](10, 0) NOT NULL,
	[ETL_PROC_WID] [numeric](10, 0) NULL,
	[INTEGRATION_ID] [nvarchar](30) NULL,
	[DATASOURCE_NUM_ID] [numeric](10, 0) NULL,
	[SCD_START_DT_WID] [numeric](10, 0) NOT NULL,
	[SCD_END_DT_WID] [numeric](10, 0) NULL,
	[NAME] [nvarchar](50) NULL,
	[ACCOUNT_WID] [numeric](10, 0) NULL,
	[PRODUCT_WID] [numeric](10, 0) NULL,
	[TYPE_CD] [nvarchar](30) NULL,
	[TYPE_CD_I] [nvarchar](50) NULL,
	[LOC_TYPE_CD] [nvarchar](30) NULL,
	[LOC_TYPE_CD_I] [nvarchar](50) NULL,
	[LOC_SUBTYPE_CD] [nvarchar](30) NULL,
	[LOC_SUBTYPE_CD_I] [nvarchar](50) NULL,
	[BU_ID] [nvarchar](15) NOT NULL,
	[ASSORTMENT_START_DT] [datetime] NULL,
	[ASSORTMENT_END_DT] [datetime] NULL,
	[ASSORTMENT_ID] [nvarchar](30) NULL,
	[PERIOD_NAME] [nvarchar](50) NULL,
	[ORG_NAME] [nvarchar](100) NULL,
	[CTLG_NAME] [nvarchar](75) NULL,
 CONSTRAINT [WC_ASSORTMENT_SCD_SK_PK] PRIMARY KEY CLUSTERED 
(
	[ROW_WID] ASC,
	[SCD_START_DT_WID] ASC,
	[BU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WC_ASSORTMENT_SCD_SK]  WITH CHECK ADD  CONSTRAINT [WC_ASSORTMENT_SCD_SK_BU_ID] CHECK  (([BU_ID]='1-7Q8NB3'))
GO

ALTER TABLE [dbo].[WC_ASSORTMENT_SCD_SK] CHECK CONSTRAINT [WC_ASSORTMENT_SCD_SK_BU_ID]
GO


