IF  EXISTS (SELECT * FROM sys.procedures WHERE object_id = OBJECT_ID(N'[dbo].[sp_WC_SALES_F_SK]'))
DROP PROCEDURE [dbo].[sp_WC_SALES_F_SK]
GO 

CREATE PROCEDURE [dbo].[sp_WC_SALES_F_SK]

AS
DECLARE
---- Logging parameters
@OBJECT_TYPE NVARCHAR(30) ,
@PROCESS_OBJECTS NVARCHAR(30) ,
@PROCESS_TASKS NVARCHAR(30) ,
@PROCESS_DESCRIPTION NVARCHAR(100) ,
@DEBUG_VALUE NVARCHAR(150) ,
@COUNTRY_CODE NVARCHAR(30),
@TASK_STATUS NVARCHAR(30),
@ERROR_COD NVARCHAR(10),
@ETL_PROC_WID NUMERIC(10,0),
@ROW_CNT NVARCHAR(30),
@ROW_CNT1 INT,
@ROW_CNT2 INT
BEGIN

/*********************************************************************************************************************************
Name: sp_WC_SALES_F_SK
Execution: Call in OLAP Sales workflow
Description: Temporal procedure until CHG025165 - To change Sales View for one table per market. Part II (Data) is developed.
This will load WC_SALES_F_SK based on WC_SALES_DAILY_F_SK & WC_SALES_NONDAILY_F_SK
Based on daily execution by ETL_PROC_WID
Bsed on the Sales Load does not delete records
Release Date:12/12/2011
Process ID:CHG024928
Development Team:GDC Siebel
Author: Jaime Medina
Modificaction 1: 18/01/2012 Deletion based on ROW_WID and SALES_TYPE_WID as ROW_WID is not unique

Modificaction 2: 01/02/2012 Deletion based on INTEGRATION_ID and not in ROW_WID

Modificaction 3: 02/02/2012 Additional Fields to Sales Tables due to CHG014453
*********************************************************************************************************************************/
/*				
Executing stored proc sp_INSERT_WC_SP_DECOMMISION to populate table WC_SP_DECOMMISION 				
in the context of EXADATA project to indicate whether the stored proc has been run				
*/				
-- Added by Hursha				
-- Begin				
				
DECLARE 				
		  @SP_NAME	  NVARCHAR(100),	
		  @DATE_OF_EXECUTION	  DATETIME	
				
SET 				
		  @SP_NAME = 'sp_WC_SALES_F_SK'; -- name of stored proc being executed		
				
EXEC sp_INSERT_WC_SP_DECOMMISION @SP_NAME,				
				 @DATE_OF_EXECUTION;
-- End				

-- initialize

SELECT @ETL_PROC_WID = ETL_PROC_WID FROM W_PARAM_G


-- Initialize Logging parameters
SET @ROW_CNT1 = 0
SET @OBJECT_TYPE = 'STORED_PROCEDURE'
SET @PROCESS_OBJECTS = 'sp_WC_SALES_F_SK'
SET @COUNTRY_CODE = 'SK'
SET @TASK_STATUS = 'STARTED'

--DAILY START
SET @PROCESS_TASKS = 'DAILY SALES'

SET @DEBUG_VALUE = '1:Delete Existing Records'
SET @PROCESS_DESCRIPTION = 'START:DELETE WC_SALES_F_SK FOR DAILY'
EXEC INSERT_WC_PROCESS_EXECUTION_LOG @OBJECT_TYPE,@PROCESS_OBJECTS ,@PROCESS_TASKS ,@PROCESS_DESCRIPTION,@DEBUG_VALUE,@TASK_STATUS,@COUNTRY_CODE ,@ETL_PROC_WID
PRINT('Start Deletion for Daily Sales')

--DELETE DAILY
delete from WC_SALES_F_SK
where exists (select 1 from WC_SALES_DAILY_F_SK ETL (NOLOCK)
where WC_SALES_F_SK.INTEGRATION_ID=ETL.INTEGRATION_ID and WC_SALES_F_SK.SALES_TYPE_WID=ETL.SALES_TYPE_WID
and ETL.ETL_PROC_WID=@ETL_PROC_WID)

SET @ROW_CNT1 = ISNULL(@@ROWCOUNT,0)
SET @ROW_CNT = CAST(@ROW_CNT1 AS NVARCHAR(10))
SET @ERROR_COD = CAST(@@ERROR AS NVARCHAR(10))
SET @DEBUG_VALUE = '1:END:Delete DAILY'+' Rows DEL='+@ROW_CNT+' Error Code='+@ERROR_COD
SET @PROCESS_DESCRIPTION = 'END:DELETE WC_SALES_F_SK FOR DAILY'
EXEC INSERT_WC_PROCESS_EXECUTION_LOG @OBJECT_TYPE,@PROCESS_OBJECTS ,@PROCESS_TASKS ,@PROCESS_DESCRIPTION,@DEBUG_VALUE,@TASK_STATUS,@COUNTRY_CODE ,@ETL_PROC_WID
PRINT('End Deletion for Daily Sales')

SET @DEBUG_VALUE = '2:Insert Records'
SET @PROCESS_DESCRIPTION = 'START:INSERT WC_SALES_F_SK FOR DAILY'
EXEC INSERT_WC_PROCESS_EXECUTION_LOG @OBJECT_TYPE,@PROCESS_OBJECTS ,@PROCESS_TASKS ,@PROCESS_DESCRIPTION,@DEBUG_VALUE,@TASK_STATUS,@COUNTRY_CODE ,@ETL_PROC_WID
PRINT('Start Insert for Daily Sales')

--INSERT DAILY
INSERT INTO WC_SALES_F_SK
(ROW_WID, DATASOURCE_NUM_ID, INTEGRATION_ID, ETL_PROC_WID, SALES_TYPE_WID, START_DT_WID, END_DT_WID, PRODUCT_WID, PROM_MAT_WID, ACCNT_WID, TGT_ACCNT_WID, GEO_WID, VENDING_M_WID, ACTL_SHIPMENT_QTY_C, ACTL_SHIPMENT_QTY, ACTL_GROSS_SHIPMENT_AMT, ACTL_GROSS_SHIPMENT_AMT_USD, ACTL_NET_SHIPMENT_AMT, ACTL_NET_SHIPMENT_AMT_USD, GROSS_MARGIN, GROSS_MARGIN_USD, NET_MARGIN, NET_MARGIN_USD, PRODUCT_MARGIN, PRODUCT_MARGIN_USD, MARKET_EXPENDITURE, MARKET_EXPENDITURE_USD, SALES_EXPENDITURE, SALES_EXPENDITURE_USD, CONTRIBUTION, CONTRIBUTION_USD, OPERATING_PROFIT, OPERATING_PROFIT_USD, TAX_AMOUNT, TAX_AMOUNT_USD, PROM_MAT_QTY, AMT_CURCY, COUNTRY_CODE, CHANNEL_WID, SEGMENT_WID, D_POSTN_WID2, QUOTE_WID, X_BU_ID, PERIOD_WID, MONTH_WID, YEAR_WID, POSTN_WID, SALES_DISCOUNT, CUSTOMER_ORIENTED_DISCOUNT, CUSTOM_FIELD_1, CUSTOM_FIELD_2, CUSTOM_FIELD_3, CUSTOM_FIELD_4, CUSTOM_FIELD_5, CUSTOM_FIELD_6, CUSTOM_FIELD_7, CUSTOM_FIELD_8, CUSTOM_FIELD_9, CUSTOM_FIELD_10, CUSTOM_FIELD_11, CUSTOM_FIELD_12,MANUFACTURER_COGS,MANUFACTURER_COGS_USD,MANUFACTURER_PRICE,MANUFACTURER_PRICE_USD,MANUFACTURER_TAX,MANUFACTURER_TAX_USD,MANUFACTURER_GROSS_MARGIN,MANUFACTURER_GROSS_MARGIN_USD,WHOLESALER_PRICE,WHOLESALER_PRICE_USD,WHOLESALER_TAX,WHOLESALER_TAX_USD,WHOLESALER_GROSS_MARGIN,WHOLESALER_GROSS_MARGIN_USD,INTERMED1_PRICE,INTERMED1_PRICE_USD,INTERMED1_TAX,INTERMED1_TAX_USD,INTERMED1_GROSS_MARGIN,INTERMED1_GROSS_MARGIN_USD,INTERMED2_PRICE,INTERMED2_PRICE_USD,INTERMED2_TAX,INTERMED2_TAX_USD,INTERMED2_GROSS_MARGIN,INTERMED2_GROSS_MARGIN_USD,INTERMED3_PRICE,INTERMED3_PRICE_USD,INTERMED3_TAX,INTERMED3_TAX_USD,INTERMED3_GROSS_MARGIN,INTERMED3_GROSS_MARGIN_USD,RETAILER_SELLIN_PRICE,RETAILER_SELLIN_PRICE_USD,RETAILER_PRICE,RETAILER_PRICE_USD,RETAILER_TAX,RETAILER_TAX_USD,RETAILER_GROSS_MARGIN,RETAILER_GROSS_MARGIN_USD,X_STANDARD_COST,X_STANDARD_COST_USD,X_DISTRIBUTION_COST,X_DISTRIBUTION_COST_USD,X_OTHER_COSTS_OF_GOODS,X_OTHER_COSTS_OF_GOODS_USD)
SELECT
ROW_WID, DATASOURCE_NUM_ID, INTEGRATION_ID, ETL_PROC_WID, SALES_TYPE_WID, START_DT_WID, END_DT_WID, PRODUCT_WID, PROM_MAT_WID, ACCNT_WID, TGT_ACCNT_WID, GEO_WID, VENDING_M_WID, ACTL_SHIPMENT_QTY_C, ACTL_SHIPMENT_QTY, ACTL_GROSS_SHIPMENT_AMT, ACTL_GROSS_SHIPMENT_AMT_USD, ACTL_NET_SHIPMENT_AMT, ACTL_NET_SHIPMENT_AMT_USD, GROSS_MARGIN, GROSS_MARGIN_USD, NET_MARGIN, NET_MARGIN_USD, PRODUCT_MARGIN, PRODUCT_MARGIN_USD, MARKET_EXPENDITURE, MARKET_EXPENDITURE_USD, SALES_EXPENDITURE, SALES_EXPENDITURE_USD, CONTRIBUTION, CONTRIBUTION_USD, OPERATING_PROFIT, OPERATING_PROFIT_USD, TAX_AMOUNT, TAX_AMOUNT_USD, PROM_MAT_QTY, AMT_CURCY, COUNTRY_CODE, CHANNEL_WID, SEGMENT_WID, D_POSTN_WID2, QUOTE_WID, X_BU_ID, PERIOD_WID, MONTH_WID, YEAR_WID, POSTN_WID, SALES_DISCOUNT, CUSTOMER_ORIENTED_DISCOUNT, CUSTOM_FIELD_1, CUSTOM_FIELD_2, CUSTOM_FIELD_3, CUSTOM_FIELD_4, CUSTOM_FIELD_5, CUSTOM_FIELD_6, CUSTOM_FIELD_7, CUSTOM_FIELD_8, CUSTOM_FIELD_9, CUSTOM_FIELD_10, CUSTOM_FIELD_11, CUSTOM_FIELD_12,MANUFACTURER_COGS,MANUFACTURER_COGS_USD,MANUFACTURER_PRICE,MANUFACTURER_PRICE_USD,MANUFACTURER_TAX,MANUFACTURER_TAX_USD,MANUFACTURER_GROSS_MARGIN,MANUFACTURER_GROSS_MARGIN_USD,WHOLESALER_PRICE,WHOLESALER_PRICE_USD,WHOLESALER_TAX,WHOLESALER_TAX_USD,WHOLESALER_GROSS_MARGIN,WHOLESALER_GROSS_MARGIN_USD,INTERMED1_PRICE,INTERMED1_PRICE_USD,INTERMED1_TAX,INTERMED1_TAX_USD,INTERMED1_GROSS_MARGIN,INTERMED1_GROSS_MARGIN_USD,INTERMED2_PRICE,INTERMED2_PRICE_USD,INTERMED2_TAX,INTERMED2_TAX_USD,INTERMED2_GROSS_MARGIN,INTERMED2_GROSS_MARGIN_USD,INTERMED3_PRICE,INTERMED3_PRICE_USD,INTERMED3_TAX,INTERMED3_TAX_USD,INTERMED3_GROSS_MARGIN,INTERMED3_GROSS_MARGIN_USD,RETAILER_SELLIN_PRICE,RETAILER_SELLIN_PRICE_USD,RETAILER_PRICE,RETAILER_PRICE_USD,RETAILER_TAX,RETAILER_TAX_USD,RETAILER_GROSS_MARGIN,RETAILER_GROSS_MARGIN_USD,X_STANDARD_COST,X_STANDARD_COST_USD,X_DISTRIBUTION_COST,X_DISTRIBUTION_COST_USD,X_OTHER_COSTS_OF_GOODS,X_OTHER_COSTS_OF_GOODS_USD
FROM WC_SALES_DAILY_F_SK ETL (Nolock)
WHERE ETL.ETL_PROC_WID=@ETL_PROC_WID


SET @ROW_CNT1 = ISNULL(@@ROWCOUNT,0)
SET @ROW_CNT = CAST(@ROW_CNT1 AS NVARCHAR(10))
SET @ERROR_COD = CAST(@@ERROR AS NVARCHAR(10))
SET @DEBUG_VALUE = '2:END:INSERT DAILY '+' Rows INS='+@ROW_CNT+' Error Code='+@ERROR_COD
EXEC INSERT_WC_PROCESS_EXECUTION_LOG @OBJECT_TYPE,@PROCESS_OBJECTS ,@PROCESS_TASKS ,@PROCESS_DESCRIPTION,@DEBUG_VALUE,@TASK_STATUS,@COUNTRY_CODE ,@ETL_PROC_WID
PRINT('End Insert for Daily Sales')

--DAILY END

--NONDAILY START
SET @PROCESS_TASKS = 'NONDAILY SALES'
SET @DEBUG_VALUE = '3:Delete Existing Records'
SET @PROCESS_DESCRIPTION = 'START:DELETE WC_SALES_F_SK FOR NONDAILY'
EXEC INSERT_WC_PROCESS_EXECUTION_LOG @OBJECT_TYPE,@PROCESS_OBJECTS ,@PROCESS_TASKS ,@PROCESS_DESCRIPTION,@DEBUG_VALUE,@TASK_STATUS,@COUNTRY_CODE ,@ETL_PROC_WID
PRINT('Start Deletion for NON Daily Sales')

--DELETE NONDAILY

delete from WC_SALES_F_SK
where exists (select 1 from WC_SALES_NONDAILY_F_SK ETL (NOLOCK)
where WC_SALES_F_SK.INTEGRATION_ID=ETL.INTEGRATION_ID and WC_SALES_F_SK.SALES_TYPE_WID=ETL.SALES_TYPE_WID
and ETL.ETL_PROC_WID=@ETL_PROC_WID)

SET @ROW_CNT1 = ISNULL(@@ROWCOUNT,0)
SET @ROW_CNT = CAST(@ROW_CNT1 AS NVARCHAR(10))
SET @ERROR_COD = CAST(@@ERROR AS NVARCHAR(10))
SET @DEBUG_VALUE = '3:END:Delete NONDAILY'+' Rows DEL='+@ROW_CNT+' Error Code='+@ERROR_COD
SET @PROCESS_DESCRIPTION = 'START:INSERT WC_SALES_F_SK FOR NONDAILY'
EXEC INSERT_WC_PROCESS_EXECUTION_LOG @OBJECT_TYPE,@PROCESS_OBJECTS ,@PROCESS_TASKS ,@PROCESS_DESCRIPTION,@DEBUG_VALUE,@TASK_STATUS,@COUNTRY_CODE ,@ETL_PROC_WID
PRINT('End Delete for Non Daily Sales')


SET @DEBUG_VALUE = '4:Insert Records'
SET @PROCESS_DESCRIPTION = 'START:INSERT WC_SALES_F_SK FOR NONDAILY'
EXEC INSERT_WC_PROCESS_EXECUTION_LOG @OBJECT_TYPE,@PROCESS_OBJECTS ,@PROCESS_TASKS ,@PROCESS_DESCRIPTION,@DEBUG_VALUE,@TASK_STATUS,@COUNTRY_CODE ,@ETL_PROC_WID
PRINT('Start Insert for Non Daily Sales')


--INSERT NONDAILY
INSERT INTO WC_SALES_F_SK
(ROW_WID, DATASOURCE_NUM_ID, INTEGRATION_ID, ETL_PROC_WID, SALES_TYPE_WID, START_DT_WID, END_DT_WID, PRODUCT_WID, PROM_MAT_WID, ACCNT_WID, TGT_ACCNT_WID, GEO_WID, VENDING_M_WID, ACTL_SHIPMENT_QTY_C, ACTL_SHIPMENT_QTY, ACTL_GROSS_SHIPMENT_AMT, ACTL_GROSS_SHIPMENT_AMT_USD, ACTL_NET_SHIPMENT_AMT, ACTL_NET_SHIPMENT_AMT_USD, GROSS_MARGIN, GROSS_MARGIN_USD, NET_MARGIN, NET_MARGIN_USD, PRODUCT_MARGIN, PRODUCT_MARGIN_USD, MARKET_EXPENDITURE, MARKET_EXPENDITURE_USD, SALES_EXPENDITURE, SALES_EXPENDITURE_USD, CONTRIBUTION, CONTRIBUTION_USD, OPERATING_PROFIT, OPERATING_PROFIT_USD, TAX_AMOUNT, TAX_AMOUNT_USD, PROM_MAT_QTY, AMT_CURCY, COUNTRY_CODE, CHANNEL_WID, SEGMENT_WID, D_POSTN_WID2, QUOTE_WID, X_BU_ID, PERIOD_WID, MONTH_WID, YEAR_WID, POSTN_WID, SALES_DISCOUNT, CUSTOMER_ORIENTED_DISCOUNT, CUSTOM_FIELD_1, CUSTOM_FIELD_2, CUSTOM_FIELD_3, CUSTOM_FIELD_4, CUSTOM_FIELD_5, CUSTOM_FIELD_6, CUSTOM_FIELD_7, CUSTOM_FIELD_8, CUSTOM_FIELD_9, CUSTOM_FIELD_10, CUSTOM_FIELD_11, CUSTOM_FIELD_12,MANUFACTURER_COGS,MANUFACTURER_COGS_USD,MANUFACTURER_PRICE,MANUFACTURER_PRICE_USD,MANUFACTURER_TAX,MANUFACTURER_TAX_USD,MANUFACTURER_GROSS_MARGIN,MANUFACTURER_GROSS_MARGIN_USD,WHOLESALER_PRICE,WHOLESALER_PRICE_USD,WHOLESALER_TAX,WHOLESALER_TAX_USD,WHOLESALER_GROSS_MARGIN,WHOLESALER_GROSS_MARGIN_USD,INTERMED1_PRICE,INTERMED1_PRICE_USD,INTERMED1_TAX,INTERMED1_TAX_USD,INTERMED1_GROSS_MARGIN,INTERMED1_GROSS_MARGIN_USD,INTERMED2_PRICE,INTERMED2_PRICE_USD,INTERMED2_TAX,INTERMED2_TAX_USD,INTERMED2_GROSS_MARGIN,INTERMED2_GROSS_MARGIN_USD,INTERMED3_PRICE,INTERMED3_PRICE_USD,INTERMED3_TAX,INTERMED3_TAX_USD,INTERMED3_GROSS_MARGIN,INTERMED3_GROSS_MARGIN_USD,RETAILER_SELLIN_PRICE,RETAILER_SELLIN_PRICE_USD,RETAILER_PRICE,RETAILER_PRICE_USD,RETAILER_TAX,RETAILER_TAX_USD,RETAILER_GROSS_MARGIN,RETAILER_GROSS_MARGIN_USD,X_STANDARD_COST,X_STANDARD_COST_USD,X_DISTRIBUTION_COST,X_DISTRIBUTION_COST_USD,X_OTHER_COSTS_OF_GOODS,X_OTHER_COSTS_OF_GOODS_USD)
SELECT
ROW_WID, DATASOURCE_NUM_ID, INTEGRATION_ID, ETL_PROC_WID, SALES_TYPE_WID, START_DT_WID, END_DT_WID, PRODUCT_WID, PROM_MAT_WID, ACCNT_WID, TGT_ACCNT_WID, GEO_WID, VENDING_M_WID, ACTL_SHIPMENT_QTY_C, ACTL_SHIPMENT_QTY, ACTL_GROSS_SHIPMENT_AMT, ACTL_GROSS_SHIPMENT_AMT_USD, ACTL_NET_SHIPMENT_AMT, ACTL_NET_SHIPMENT_AMT_USD, GROSS_MARGIN, GROSS_MARGIN_USD, NET_MARGIN, NET_MARGIN_USD, PRODUCT_MARGIN, PRODUCT_MARGIN_USD, MARKET_EXPENDITURE, MARKET_EXPENDITURE_USD, SALES_EXPENDITURE, SALES_EXPENDITURE_USD, CONTRIBUTION, CONTRIBUTION_USD, OPERATING_PROFIT, OPERATING_PROFIT_USD, TAX_AMOUNT, TAX_AMOUNT_USD, PROM_MAT_QTY, AMT_CURCY, COUNTRY_CODE, CHANNEL_WID, SEGMENT_WID, D_POSTN_WID2, QUOTE_WID, X_BU_ID, PERIOD_WID, MONTH_WID, YEAR_WID, POSTN_WID, SALES_DISCOUNT, CUSTOMER_ORIENTED_DISCOUNT, CUSTOM_FIELD_1, CUSTOM_FIELD_2, CUSTOM_FIELD_3, CUSTOM_FIELD_4, CUSTOM_FIELD_5, CUSTOM_FIELD_6, CUSTOM_FIELD_7, CUSTOM_FIELD_8, CUSTOM_FIELD_9, CUSTOM_FIELD_10, CUSTOM_FIELD_11, CUSTOM_FIELD_12,MANUFACTURER_COGS,MANUFACTURER_COGS_USD,MANUFACTURER_PRICE,MANUFACTURER_PRICE_USD,MANUFACTURER_TAX,MANUFACTURER_TAX_USD,MANUFACTURER_GROSS_MARGIN,MANUFACTURER_GROSS_MARGIN_USD,WHOLESALER_PRICE,WHOLESALER_PRICE_USD,WHOLESALER_TAX,WHOLESALER_TAX_USD,WHOLESALER_GROSS_MARGIN,WHOLESALER_GROSS_MARGIN_USD,INTERMED1_PRICE,INTERMED1_PRICE_USD,INTERMED1_TAX,INTERMED1_TAX_USD,INTERMED1_GROSS_MARGIN,INTERMED1_GROSS_MARGIN_USD,INTERMED2_PRICE,INTERMED2_PRICE_USD,INTERMED2_TAX,INTERMED2_TAX_USD,INTERMED2_GROSS_MARGIN,INTERMED2_GROSS_MARGIN_USD,INTERMED3_PRICE,INTERMED3_PRICE_USD,INTERMED3_TAX,INTERMED3_TAX_USD,INTERMED3_GROSS_MARGIN,INTERMED3_GROSS_MARGIN_USD,RETAILER_SELLIN_PRICE,RETAILER_SELLIN_PRICE_USD,RETAILER_PRICE,RETAILER_PRICE_USD,RETAILER_TAX,RETAILER_TAX_USD,RETAILER_GROSS_MARGIN,RETAILER_GROSS_MARGIN_USD,X_STANDARD_COST,X_STANDARD_COST_USD,X_DISTRIBUTION_COST,X_DISTRIBUTION_COST_USD,X_OTHER_COSTS_OF_GOODS,X_OTHER_COSTS_OF_GOODS_USD
FROM WC_SALES_NONDAILY_F_SK ETL (Nolock)
WHERE ETL.ETL_PROC_WID=@ETL_PROC_WID

SET @ROW_CNT1 = ISNULL(@@ROWCOUNT,0)
SET @ROW_CNT = CAST(@ROW_CNT1 AS NVARCHAR(10))
SET @ERROR_COD = CAST(@@ERROR AS NVARCHAR(10))
SET @DEBUG_VALUE = '4:END:INSERT NONDAILY '+' Rows INS='+@ROW_CNT+' Error Code='+@ERROR_COD
SET @PROCESS_DESCRIPTION = 'START:INSERT WC_SALES_F_SK FOR NONDAILY'
EXEC INSERT_WC_PROCESS_EXECUTION_LOG @OBJECT_TYPE,@PROCESS_OBJECTS ,@PROCESS_TASKS ,@PROCESS_DESCRIPTION,@DEBUG_VALUE,@TASK_STATUS,@COUNTRY_CODE ,@ETL_PROC_WID
PRINT('End Insert for Non Daily Sales')

--NONDAILY END

END






GO


