SELECT TOP 100 S_ORG_EXT.ROW_ID, S_ORG_EXT_X.X_TRADING_AS_TXT
, S_ORG_EXT_X.X_TT_EOID_TXT
, S_ORG_EXT_X.X_TT_FID_TXT
, S_ORG_EXT_X.X_TT_UPDATE_STAT_CD
, S_ORG_EXT_X.X_TT_REQUEST_DT
, X_TT_REQ_BY.LOGIN X_TT_REQ_BY
, S_ORG_EXT_X.X_TT_REJECT_APP_DT
, X_TT_REJECT_APP_BY.LOGIN X_TT_REJECT_APP_BY
,S_ORG_EXT.PR_POSTN_ID
, S_ORG_EXT.X_ACCNT_POSTN_ID
	,S_ORG_EXT.ALIAS_NAME
	,CASE 
		WHEN CHARINDEX(CHAR(10), S_ORG_EXT.MAIN_FAX_PH_NUM) > 0
			THEN LEFT(S_ORG_EXT.MAIN_FAX_PH_NUM, (CHARINDEX(CHAR(10), S_ORG_EXT.MAIN_FAX_PH_NUM) - 1))
		ELSE S_ORG_EXT.MAIN_FAX_PH_NUM
		END
	,S_ORG_EXT.LAST_CALL_DT
	,S_ORG_EXT.INTEGRATION_ID
	,S_ORG_EXT.MAIN_EMAIL_ADDR
	,S_ORG_EXT.X_ALIAS_NAME_2
	,S_ORG_EXT.X_INACTIVE_REASON
	,S_ORG_EXT.X_CONTRACT_STATUS
	,S_ORG_EXT.X_CONTACT_TYPE
	,S_ORG_EXT.X_KEY_ACCOUNT
	,S_ADDR_PER.ADDR_LINE_2
	,S_ORG_EXT_X.ATTRIB_75
	,S_ORG_EXT.X_AGE_BUCKET1
	,S_ORG_EXT.X_AGE_BUCKET2
	,S_ORG_EXT.X_AGE_BUCKET3
	,S_ORG_EXT.X_AGE_BUCKET4
	,S_ORG_EXT.X_ETHNICITY_CD
	,S_ORG_EXT.X_GENDER_FEMALE
	,S_ORG_EXT.X_INCOME_CD
	,S_ORG_EXT.X_MARITAL_STATUS_CD
	,S_ORG_EXT.X_ASSORTMENT_CD
	,S_ORG_EXT.X_CONTROL_DISTRIBUTION_CD
	,S_ORG_EXT.X_CUISINE_CD
	,S_ORG_EXT.X_CUSTOM_121_CD
	,S_ORG_EXT.X_CUSTOM_BRANDING_CD
	,S_ORG_EXT.X_CUSTOM_EVENTS_CD
	,S_ORG_EXT.X_DISPLAY_JTI_BRANDS_CD
	,S_ORG_EXT.X_DRESS_CODE_CD
	,S_ORG_EXT.X_DRESSING_CD
	,S_ORG_EXT.X_DRINKS_BEST_SALES_CD
	,S_ORG_EXT.X_EDUC_LEVEL_CD
	,S_ORG_EXT.X_ENTRANCE_POLICY_CD
	,S_ORG_EXT.X_FREE_TIME_CD
	,S_ORG_EXT.X_HH_OCCUPANCY_CD
	,S_ORG_EXT.X_HOBBY_CD
	,S_ORG_EXT.X_LANGUAGE_CD
	,S_ORG_EXT.X_LOCATION_CD
	,S_ORG_EXT.X_MOTIVATE_STAFF_CD
	,S_ORG_EXT.X_MUSIC_FACILITY_CD
	,S_ORG_EXT.X_MUSIC_STYLE_CD
	,S_ORG_EXT.X_OCCUPATION_CD
	,S_ORG_EXT.X_OUTLET_CAPACITY_CD
	,S_ORG_EXT.X_PARKING_CD
	,S_ORG_EXT.X_POS_MATERIAL_CD
	,S_ORG_EXT.X_PRICE_INDEX_CD
	,S_ORG_EXT.X_PROGRAM_CD
	,S_ORG_EXT.X_PROMO_REELS_CD
	,S_ORG_EXT.X_QUALITY_SERVICE_CD
	,S_ORG_EXT.X_REASON_TO_VISIT_CD
	,S_ORG_EXT.X_RESIDENCE_CD
	,S_ORG_EXT.X_SCREENS_AVAILABILITY_CD
	,S_ORG_EXT.X_SPECIAL_BRANDING_CD
	,S_ORG_EXT.X_SPONSOR_EVENTS_CD
	,S_ORG_EXT.X_SPORT_CD
	,S_ORG_EXT.X_TOOLS_CD
	,S_ORG_EXT_BU_NAME.LOC AS BU_LOC
	,S_ORG_EXT.X_BRANDFOCUS_SOURCE_CD
	,S_ORG_EXT.X_ORDER_WITH_INC_CD
	,S_ORG_EXT.X_MULTIPLE_STOCK_CD
	,S_ORG_EXT.X_INFLUENCE_SHELF_CD
	,S_ORG_EXT.X_SHELF_VISIBILITY_CD
	,S_ORG_EXT.X_INFL_MERCH_CD
	,S_ORG_EXT.X_INFL_PROMO_CD
	,S_ORG_EXT.X_COUNTER_PART_CD
	,S_ORG_EXT.X_SHELF_AVAILABLE_CD
	,S_ORG_EXT.X_VENDING_INSIDE_CD
	,S_ORG_EXT.TAX_EXEMPT_NUM
	,S_ORG_EXT.X_TM_TYPE
	,S_REGION.X_INTEGRATION_ID AS REGION_ID
	,S_ORG_EXT_X.ATTRIB_73
	,S_ORG_EXT.X_OUTLET_FLG
	,S_ORG_EXT.X_ATTRIB_46
	,S_ORG_EXT.X_BRAND_FOCUS
	,S_ORG_EXT.X_ORDER_DAY
	,S_ORG_EXT.X_SPECIALIZATION
	,S_ORG_EXT.X_YAS
	,S_ORG_EXT.X_CUST_MUSTS
	,S_ORG_EXT.X_CUST_WANTS
	,S_ORG_EXT.X_INFLUENCE_CD
	,S_ORG_EXT.X_OUTLET_FORMAT
	,S_ORG_EXT.X_POWER_FACTOR
	,S_ORG_EXT.X_PLANOGRAM_FLG
	,S_ORG_EXT.X_SEASON_END_DT
	,S_ORG_EXT.X_SEASON_START_DT
	,S_ORG_EXT.X_SEASONAL_FLG
	,S_ORG_EXT.X_SELL_SPACE_NUM
	,S_ORG_EXT.X_PREF_VISIT_DAY_CD
	,S_ORG_EXT.X_NIELSEN_AREA_CD
	,S_ORG_EXT.X_ATTRIB_1
	,S_ORG_EXT.X_ATTRIB_11
	,S_ORG_EXT.X_ATTRIB_12
	,S_ORG_EXT.X_ATTRIB_13
	,S_ORG_EXT.X_ATTRIB_14
	,S_ORG_EXT.X_ATTRIB_15
	,S_ORG_EXT.X_ATTRIB_16
	,S_ORG_EXT.X_ATTRIB_17
	,S_ORG_EXT.X_ATTRIB_18
	,S_ORG_EXT.X_ATTRIB_2
	,S_ORG_EXT.X_ATTRIB_21
	,S_ORG_EXT.X_ATTRIB_22
	,S_ORG_EXT.X_ATTRIB_23
	,S_ORG_EXT.X_ATTRIB_24
	,S_ORG_EXT.X_ATTRIB_25
	,S_ORG_EXT.X_ATTRIB_26
	,S_ORG_EXT.X_ATTRIB_27
	,S_ORG_EXT.X_ATTRIB_28
	,S_ORG_EXT.X_ATTRIB_3
	,S_ORG_EXT.X_ATTRIB_31
	,S_ORG_EXT.X_ATTRIB_32
	,S_ORG_EXT.X_ATTRIB_33
	,S_ORG_EXT.X_ATTRIB_34
	,S_ORG_EXT.X_ATTRIB_35
	,S_ORG_EXT.X_ATTRIB_36
	,S_ORG_EXT.X_ATTRIB_37
	,S_ORG_EXT.X_ATTRIB_38
	,S_ORG_EXT.X_ATTRIB_4
	,S_ORG_EXT.X_ATTRIB_41
	,S_ORG_EXT.X_ATTRIB_42
	,S_ORG_EXT.X_ATTRIB_43
	,S_ORG_EXT.X_ATTRIB_44
	,S_ORG_EXT.X_ATTRIB_5
	,S_ORG_EXT.X_ATTRIB_6
	,S_ORG_EXT.X_ATTRIB_7
	,S_ORG_EXT.X_ATTRIB_8
	,S_ORG_EXT_X.ATTRIB_09
	,S_ORG_EXT_X.ATTRIB_11
	,S_ORG_EXT_X.ATTRIB_20
	,S_ORG_EXT_X.ATTRIB_56
	,S_ORG_EXT_X.ATTRIB_07
	,ISNULL(S_ORG_EXT_X.X_CURRENT_TARGETED_FLG, 'N')
	,S_ORG_EXT_X.X_CURRENT_CHANNEL_CD
	,S_ORG_EXT_X.X_CURRENT_SEGMENT_CD
	,S_ORG_EXT_X.X_CURRENT_BRAND_OPPT_CD
	,S_ORG_EXT_X.X_CURRENT_BRAND_OPPT_SC_NUM
	,S_ORG_EXT.X_BRANDED_ITEMS_CD
	,S_ORG_EXT.X_MUSIC_AMBIANCE_CD
	,S_ORG_EXT.X_OUTLET_COMMUNICATION_CD
	,S_ORG_EXT.X_OUTLET_STYLE_CD
	,S_ORG_EXT_UTX.LEGAL_STAT_CD
	,S_ORG_EXT_X.ATTRIB_34
	,S_ORG_EXT_X.ATTRIB_35
	,S_ORG_EXT_X.ATTRIB_39
	,S_ORG_EXT_X.ATTRIB_40
	,S_ORG_EXT_X.ATTRIB_41
	,S_ORG_EXT_X.ATTRIB_42 --,ORG_DFL.ALIAS_NAME	--,ORG_DFT.ALIAS_NAME
	,S_ORG_EXT.X_ATTRIB_40
	,S_ORG_EXT.X_ATTRIB_45
	,S_ORG_EXT.X_ATTRIB_39
	,S_ORG_EXT.X_ATTRIB_65
	,S_ORG_EXT.X_ATTRIB_66
	,S_ORG_EXT.X_ATTRIB_67
	,S_ORG_EXT.X_ATTRIB_68
	,S_ORG_EXT.X_ATTRIB_69
	,S_ORG_EXT.X_ATTRIB_70
	,S_ORG_EXT.X_ATTRIB_71
	,S_ORG_EXT.X_ATTRIB_72
	,S_ORG_EXT.X_ATTRIB_73
	,S_ORG_EXT.X_ATTRIB_75
	,S_ORG_EXT.X_ATTRIB_76
	,S_ORG_EXT.X_ATTRIB_60
	,S_ORG_EXT.X_ATTRIB_61
	,S_ORG_EXT.X_ATTRIB_62
	,S_ORG_EXT.X_ATTRIB_63
	,S_ORG_EXT.X_ATTRIB_64
	,S_ORG_EXT.X_ATTRIB_74
	,PAR_ORG.ALIAS_NAME AS PAR_ALIAS_NAME
	,S_ORG_EXT.X_ATTRIB_47
	,S_ORG_EXT.X_ATTRIB_48
	,S_ORG_EXT.X_ATTRIB_30
	,S_ADDR_PER.X_STATE
	,S_ORG_EXT.PAY_TYPE_CD
	,S_ORG_EXT.EXPERTISE_CD
	,PAR_ORG.X_ALIAS_NAME_2 AS PAR_X_ALIAS_NAME_2
	,PAR_ORG.NAME AS PARENT_NAME
	,S_ORG_EXT_X.JTI_SUB_SEGMENT_CURRENT
	,S_ORG_EXT_UTX.OWNERSHIP_CD
	,S_ORG_EXT.PR_CON_ID
	,S_ORG_EXT.X_ATTRIB_77
	,S_ORG_EXT.X_LEGAL_ACC_NAME
	,CASE 
		WHEN S_BU.NAME = 'United States, US'
			THEN CX_INFO.X_ACCNT_TAX_ID
		ELSE S_ORG_EXT.X_TAX_PAY
		END
	,S_ORG_EXT.BU_ID
	,S_ORG_EXT.X_LAST_CALL_DT
	,S_ORG_EXT.X_ATTRIB_79
	,S_ORG_EXT.X_ATTRIB_78
	,S_ORG_EXT.X_ATTRIB_9
	,S_ORG_EXT.X_ATTRIB_80 AS X_ATTRIB_80
	,S_ORG_EXT.X_ATTRIB_81
	,S_ORG_EXT.X_ASSORTMENT_ID AS X_ATTRIB_372
	,S_ADDR_PER.X_ATTRIBUTE_1
	,S_ORG_EXT.X_LAST_ORDER_ID
	,S_ADDR_PER.LATITUDE
	,S_ADDR_PER.LONGITUDE
	,S_ORG_EXT.X_ATTRIB_49
	,DATEADD(mi, ISNULL(SUMMER_X_LAST_VISIT_DT.DST_BIAS, 0), DATEADD(mi, ISNULL(S_TIMEZONE.UTC_OFFSET, 0), S_ORG_EXT.X_LAST_VISIT_DT)) X_LAST_VISIT_DT
	,S_ORG_EXT_X.ATTRIB_03
	,S_ORG_EXT_X.ATTRIB_51
	,S_ORG_EXT.X_SPACE
	,S_ORG_EXT.X_SPACE_TYPE_CD
	,S_ORG_EXT.X_SPACE_SUBTYPE_CD
	,PAR_ORG.ACCNT_TYPE_CD AS PAR_ACCNT_TYPE_CD
	,S_ORG_EXT_X.ATTRIB_44
	,S_ORG_EXT_X.ATTRIB_57
	,S_ORG_EXT_X.ATTRIB_58
	,S_ORG_EXT_X.ATTRIB_59
	,S_ORG_EXT_X.ATTRIB_60
	,S_ORG_EXT_X.ATTRIB_61
	,S_ORG_EXT_X.ATTRIB_62
	,S_ORG_EXT_X.ATTRIB_63
	,S_ORG_EXT_X.ATTRIB_64
	,S_ORG_EXT_X.ATTRIB_65
	,S_ORG_EXT_X.ATTRIB_76
	,S_ORG_EXT_X.ATTRIB_77
	,S_ORG_EXT_X.ATTRIB_78
	,S_ORG_EXT_X.ATTRIB_54
	,S_ORG_EXT_X.ATTRIB_55
	,S_ORG_EXT.X_CONT_TOBC_BUYER_CD
	,S_ORG_EXT.X_VISIT_TIME_DT
	,S_ORG_EXT.X_CONSUMER_AGE_CD
	,S_ORG_EXT.X_STUDENT_NIGHT_FLG
	,S_ORG_EXT.X_SMOKING_AREA_CD
	,S_ORG_EXT.X_SMOKING_AREA_CAP_CD
	,S_ORG_EXT.X_1_2_1_ACTIVITY_CD
	,S_ORG_EXT.X_BACK_BAR_COMP_CD
	,S_ORG_EXT.X_BACK_BAR_BRAND_CD
	,S_ORG_EXT.X_EXCLUSIVITY_CD
	,S_ORG_EXT.X_SUGGESTED_BRAND_CD
	,S_ORG_EXT_X.X_JTI_LEAD_RMC_FLG
	,S_ORG_EXT_X.X_LEAD_SECTOR_CD
	,S_ORG_EXT_X.X_JTI_LEAD_BRAND_CD
	,S_ORG_EXT_X.X_VOLUME_PREM_NUM
	,S_ORG_EXT_X.X_VOLUME_SUB_NUM
	,S_ORG_EXT_X.X_VOLUME_MID_NUM
	,S_ORG_EXT_X.X_VOLUME_VALUE_NUM
	,S_ORG_EXT_X.X_SG_PREM_NUM
	,S_ORG_EXT_X.X_SG_SUB_NUM
	,S_ORG_EXT_X.X_SG_MED_NUM
	,S_ORG_EXT_X.X_SG_VALUE_NUM
	,S_ORG_EXT_X.X_JTI_LEAD_PREM_FLG
	,S_ORG_EXT_X.X_JTI_LEAD_SUB_FLG
	,S_ORG_EXT_X.X_JTI_LEAD_MID_FLG
	,S_ORG_EXT_X.X_JTI_LEAD_VALUE_FLG
	,S_ORG_EXT_X.X_JTI_LEAD_RYO_FLG
	,S_ORG_EXT_X.X_VOLUME_LOW_NUM
	,S_ORG_EXT_X.X_VOLUME_MED_NUM
	,S_ORG_EXT_X.X_VOLUME_HIGH_NUM
	,DISTRIBUTOR.ALIAS_NAME AS X_MAIN_DISTRIBUTOR_NAME
	,DISTRIBUTOR.NAME AS X_MAIN_DISTRIBUTOR_CODE
	,ADDR.CITY AS X_MAIN_DISTRIBUTOR_CITY
	,S_ORG_EXT.X_OUTERS_PER_WEEK
	,S_ORG_EXT.X_PAY_POINT
	,S_ORG_EXT_X.X_REST_MARK_STORE
	,S_ORG_EXT_X.X_ATTRIB_83
	,S_ORG_EXT_X.X_ATTRIB_84
	,S_ORG_EXT_X.X_ATTRIB_85
	,S_ADDR_PER.ADDR_NAME
	,S_ORG_EXT_X.X_TS_ATTRIB_38_CD
	,S_ORG_EXT_X.X_TS_ATTRIB_39_CD
	,S_ORG_EXT_X.X_TS_ATTRIB_40_CD
	,S_ORG_EXT.ASGN_USR_EXCLD_FLG
	,S_ORG_EXT.X_VM_CIF
	,S_ORG_EXT.X_VM_NIF
	,S_ORG_EXT_X.X_NO_EXCAR_SALE_FLG
	,ORIGIN.NAME AS ORIGINAL_ACCNT_CODE
	,S_ORG_EXT_X.ATTRIB_22
	,S_ORG_EXT_X.ATTRIB_23
	,S_ORG_EXT_X.ATTRIB_25
	,S_ORG_EXT_X.X_ATTRIB_89
	,S_ORG_EXT_X.X_ATTRIB_90
	,USR.LOGIN
	,S_ORG_EXT_X.X_NOCOPY_FLG
	,S_ORG_EXT_X.X_ATTRIB_86
	,PAR_ORG.CUST_STAT_CD AS PAR_CUST_STAT_CD
	,PAR_ADDR.CITY AS PAR_CITY
	,PAR_ADDR.ADDR AS PAR_ADDR
	,S_ADDR_PER.X_GEO_COOR_NUM
	,S_ORG_EXT_X.X_ATTRIB_91
	,S_ORG_EXT_X.X_ATTRIB_92
	,S_ORG_EXT_X.X_ATTRIB_93
	,S_ORG_EXT_X.X_EXE_AT_ID
	,S_ORG_EXT_X.X_PAY_AT_ID
	,S_ADDR_PER.X_GEO_COORDS_SRC_CD --CHG062134
	,S_ORG_EXT_X.X_TAX_ID_STATUS_CD
	,S_ADDR_PER.X_ADDR2_TEXT
	,S_ORG_EXT.ACTIVE_FLG
	,S_ORG_EXT.AGENCY_FLG
	,S_ORG_EXT.CREATED
	,S_ORG_EXT.INT_ORG_FLG
	,ORG_BU.CREATED AS ISORG_CREATED
	,S_ORG_EXT.CUST_END_DT
	,S_ORG_EXT.CUST_SINCE_DT
	,S_ORG_EXT.ACCNT_TYPE_CD
	,S_ORG_EXT.LOC AS ACCNT_LOC
	,S_ORG_EXT.CUST_STAT_CD
	,S_ORG_EXT.OU_TYPE_CD
	,S_ORG_EXT_BU_NAME.NAME AS BU_NAME
	,S_ORG_EXT.CALL_FREQUENCY
	,S_ADDR_PER.CITY
	,S_ADDR_PER.COUNTRY
	,ORG.EXPERTISE_CD AS ORG_EXPERTISE_CD
	,CASE 
		WHEN CHARINDEX(CHAR(10), S_ORG_EXT.MAIN_PH_NUM) > 0
			THEN LEFT(S_ORG_EXT.MAIN_PH_NUM, (CHARINDEX(CHAR(10), S_ORG_EXT.MAIN_PH_NUM) - 1))
		ELSE S_ORG_EXT.MAIN_PH_NUM
		END
	,S_ORG_EXT.MARKET_CLASS_CD
	,S_CONTACT.FST_NAME AS ORG_MGR_FST_NAME
	,S_CONTACT.LAST_NAME AS ORG_MGR_LAST_NAME
	,S_CONTACT.MID_NAME AS ORG_MGR_MID_NAME
	,S_ORG_EXT.NAME
	,ADDRORG.COUNTRY AS ORG_COUNTRY
	,ORG.NAME AS ORG_NAME
	,S_ORG_EXT.PAR_OU_ID
	,S_ORG_EXT.PAR_DIVN_ID
	,S_ORG_EXT.REGION
	,S_ADDR_PER.ADDR
	,S_ADDR_PER.STATE
	,S_ADDR_PER.ZIPCODE
	,S_ORG_EXT_X.X_JTI_LEAD_HIGH_FLG
	,S_ORG_EXT_X.X_JTI_LEAD_LOW_FLG
	,S_ORG_EXT_X.X_JTI_LEAD_MED_FLG
	,S_ORG_EXT_X.X_SG_HIGH_NUM
	,S_ORG_EXT_X.X_SG_LOW_NUM
	,S_ORG_EXT_X.X_VOLUME_LW_NUM
	,S_ORG_EXT_X.X_VOLUME_SW_NUM
	,S_ORG_EXT_X.X_JTI_LEAD_LW_FLG
	,S_ORG_EXT_X.X_JTI_LEAD_SW_FLG
	,S_ORG_EXT_X.X_SG_LW_NUM
	,S_ORG_EXT_X.X_SG_SW_NUM
	,S_ORG_EXT_X.X_LOCAL_DEMO_CD
	,S_ORG_EXT_X.X_FOOTBALL_INFLUENCE_CD
	,S_ORG_EXT_X.X_COMP_LEAD_CD
	,S_ORG_EXT_X.X_URBAN_CD
	,S_ORG_EXT_X.X_SG_MED_RYO_NUM
	,S_ORG_EXT_X.X_ATTRIB_82
	,S_ORG_EXT.X_EMAIL_ADDR_TEXT
	,S_ORG_EXT.X_SERVICE_REGION
	,S_ORG_EXT.X_WEEKLY_FOOTBAL_NUM
	,S_ORG_EXT.X_NUM_BARS_NUM
	,S_ORG_EXT.X_NUM_SITES_NUM
	,S_ORG_EXT.X_BUDGET_TRADE_NUM
	,S_ORG_EXT.X_WEBSITE_TEXT
	,S_ORG_EXT_X.ATTRIB_80
	,X_GROUP.ALIAS_NAME AS X_GROUP_ALIAS_NAME
	,X_GROUP.NAME AS X_GROUP_NAME
	,S_POSTN_ORG.NAME AS X_POSTN_NAME
	,CASE 
		WHEN CHARINDEX(CHAR(10), S_ORG_EXT.X_MAIN_PHONE_TEXT) > 0
			THEN LEFT(S_ORG_EXT.X_MAIN_PHONE_TEXT, (CHARINDEX(CHAR(10), S_ORG_EXT.X_MAIN_PHONE_TEXT) - 1))
		ELSE S_ORG_EXT.X_MAIN_PHONE_TEXT
		END
	,S_ORG_EXT.X_CONT_TOBACCO_TEXT
	,PAR_ORG.X_BRAND_FOCUS AS PAR_X_BRAND_FOCUS --INC1891481
	,PAR_ORG_X.ATTRIB_07 AS PAR_X_BRAND_FOCUS_SCENARIO
	,S_REGION.X_STRATA
	,S_ORG_EXT_X.X_WHOLESALER_TYPE_CD
	,S_ORG_EXT_X.X_JTI_LEAD_CIGARS_FLG
	,CASE 
		WHEN S_ORG_EXT_X.X_ACTUAL_POSTN_ID = S_ORG_EXT.PR_POSTN_ID
			THEN 'Y'
		ELSE 'N'
		END AS ACTUAL_OWNER_FLG
	,CASE 
		WHEN S_ORG_EXT_BU_NAME.NAME = 'United States' --INC1891481
			THEN CX_INFO.X_TO_ACCNT_NUM
		ELSE S_ORG_EXT_X.X_ACCOUNT_NUM
		END
	,S_ORG_EXT_X.X_BANK_ACCOUNT_FLG
	,CX_BANK_ADMIN.X_BANK_NAME_TEXT
	,S_ORG_EXT_X.X_BANK_NUM
	,S_ORG_EXT_X.X_FIRST_NAME_BA_TEXT
	,S_ORG_EXT_X.X_LAST_NAME_BA_TEXT
	,S_ORG_EXT_X.X_PAYMENT_TYPE_RETAILER_CD
	,S_ORG_EXT_X.X_TRANSIT_NUM
	,S_ORG_EXT_X.X_ATTRIB_94
	,S_ORG_EXT_X.X_ATTRIB_95
	,S_ORG_EXT_X.X_ATTRIB_96
	,S_ORG_EXT_X.X_ATTRIB_115
	,S_ORG_EXT_X.X_ATTRIB_116
	,S_ORG_EXT_X.X_ATTRIB_110
	,S_ORG_EXT_X.X_ATTRIB_111
	,S_ORG_EXT_X.X_ATTRIB_112
	,S_ORG_EXT_X.X_ATTRIB_99
	,S_ORG_EXT_X.X_ATTRIB_100
	,S_ORG_EXT_X.X_ATTRIB_113
	,S_ORG_EXT_X.X_ATTRIB_114
	,S_ORG_EXT_X.X_ATTRIB_97
	,S_ORG_EXT_X.X_ATTRIB_98
	,S_ORG_EXT_X.X_ATTRIB_101
	,S_ORG_EXT_X.X_ATTRIB_102
	,S_ORG_EXT_X.X_ATTRIB_103
	,S_ORG_EXT_X.X_ATTRIB_104
	,S_ORG_EXT_X.X_ATTRIB_105
	,S_ORG_EXT_X.X_ATTRIB_106
	,S_ORG_EXT_X.X_ATTRIB_107
	,S_ORG_EXT_X.X_ATTRIB_108
	,S_ORG_EXT_X.X_ATTRIB_109
	,S_ORG_EXT.VAT_REGN_NUM
	,EXE_AT.NAME AS EXE_AT_NAME
	,EXE_AT.ALIAS_NAME AS EXE_AT_ALIAS_NAME
	,EXE_AT.OU_TYPE_CD AS EXE_AT_OU_TYPE_CD
	,EXE_AT.ACCNT_TYPE_CD AS EXE_AT_ACCNT_TYPE_CD
	,EXE_AT.CUST_STAT_CD AS EXE_AT_CUST_STAT_CD
	,PAY_AT.NAME AS PAY_AT_NAME
	,PAY_AT.ALIAS_NAME AS PAY_AT_ALIAS_NAME
	,PAY_AT.OU_TYPE_CD AS PAY_AT_OU_TYPE_CD
	,PAY_AT.ACCNT_TYPE_CD AS PAY_AT_ACCNT_TYPE_CD
	,PAY_AT.CUST_STAT_CD AS PAY_AT_CUST_STAT_CD
	,CX_BANK_ADMIN.X_TRANSIT_NUMBER_TEXT
	,S_ORG_EXT_X.X_PAYEEE_TYPE_CD
	,ACC_POS.ASGN_MANL_FLG
	,ACC_POS.ASGN_SYS_FLG
	,S_ORG_EXT_X.ATTRIB_31
	,S_ORG_EXT_X.ATTRIB_32
	,S_ORG_EXT_X.ATTRIB_33
	,S_ORG_EXT_X.X_ATTRIB_117
	,S_ORG_EXT_X.X_ATTRIB_118
	,S_ORG_EXT.X_ORDER_WITHOUT_INC_CD
	,S_ADDR_PER.ADDR_LINE_4
	-------------CHG069482-------------------
	,S_ORG_EXT_X.X_TR_MIN_MIN_BET_VISITS_NUM
	,S_ORG_EXT_X.X_TR_MIN_SERVICE_TIME_NUM
	,S_ORG_EXT_X.X_TR_SERVICE_TIME_NUM
	,S_ORG_EXT_X.X_TR_RANKING_NUM
	,S_ORG_EXT_X.X_ASSET_COMP_SERVICE_TIME_NUM
	,CX_BANK_ADMIN.X_BANK_KEY_TEXT
	,CX_BANK_ADMIN.X_BANK_NUMBER_TEXT
	,CX_BANK_ADMIN.X_BRANCH_NAME_TEXT
	,CX_BANK_ADMIN.X_CITY_TEXT
	,CX_BANK_ADMIN.X_STATE_TEXT
	,CX_BANK_ADMIN.X_STREET_TEXT
	-----------CHG089495----------------
	,S_ORG_EXT_X.X_RETAIL_CHANNEL_CD
	-----------CHG090227----------------
	,S_ORG_EXT_X.X_DRIVE_SRV_TIME_GR_NUM
	,S_ORG_EXT_X.X_DRIVE_SRV_TIME_NUM
	------------CHG101582---------------
      ,S_ORG_EXT_X.X_TS_ATTRIB_41_CD
      ,S_ORG_EXT_X.X_TS_ATTRIB_42_CD
      ,S_ORG_EXT_X.X_TS_ATTRIB_43_CD
      ------------CHG098897---------------
	,S_ORG_EXT_X.X_DEF_DEL_METHOD_CD
      -----------CHG099099---------------
      ,S_ORG_EXT_X.X_RESERVE_TM_FLG
	,S_ORG_EXT_X.X_ATTRIB_119_FLG
	-----------CHG099011---------------
,S_ORG_EXT_X.X_IBAN_TEXT
--CHG107127
,S_ORG_EXT_X.X_BA_VALID_DT X_BA_VERIFIED_DT
,S_ORG_EXT_X.X_BA_PHONE_TEXT X_BA_PHONE_NUM
,S_ORG_EXT_X.X_BANK_STATUS_CD X_BANK_STATUS
, CONTACT_POST.PR_EMP_ID
--CHG107127 DEF613
,S_ORG_EXT_X.X_BA_ATTRIB2_TEXT
,S_ORG_EXT_X.X_BA_ATTRIB3_TEXT
--CHG117267
,S_ORG_EXT_X.X_P1_LAST_VISIT_DT
,S_ORG_EXT_X.X_P2_LAST_VISIT_DT
,S_ORG_EXT_X.X_BA_ATTRIB4_TEXT
,S_ORG_EXT_X.X_BA_ATTRIB5_TEXT
,CX_INFO.X_IBAN_TEXT AS X_IBAN_TEXT_FULL --CHG117346
,S_ORG_EXT_X.ATTRIB_52
,S_ORG_EXT_X.ATTRIB_53
,S_ORG_EXT_X.X_MASTER_GROUP_FLG
,S_ORG_EXT_X.X_TYPE_MASTER_GROUP_CD
,S_ORG_EXT_X.X_GM_ALIAS_NAME
,S_POSTN_ORG.NAME HANDLER_POS
,S_ORG_EXT_X.X_GM_ACCOUNT_CLASS
,PARTY.CREATED GRP_CREATED_DT
,S_ORG_EXT.LAST_UPD LAST_UPD_DT
,S_ORG_EXT_X.X_TIMESTAMP_52_TT
,S_ORG_EXT_X.X_TIMESTAMP_53
,S_ORG_EXT_X.X_EMAIL_ACCEPT_CD --CHG201045
,S_ORG_EXT_X.X_SUSPEND_ORDERS_FLG
, CASE WHEN BO.LAST_NAME IS NULL AND BO.FST_NAME IS NULL THEN NULL ELSE
ISNULL(BO.LAST_NAME, '.') + ', '+ISNULL(BO.FST_NAME, '.') END X_BUSINESS_OWNER
,BO.EMAIL_ADDR  BO_EMAIL_ADDR--CHG201045
, S_ORG_EXT_X.X_TRADING_AS_TXT
, S_ORG_EXT_X.X_TT_EOID_TXT
, S_ORG_EXT_X.X_TT_FID_TXT
, S_ORG_EXT_X.X_TT_UPDATE_STAT_CD
, S_ORG_EXT_X.X_TT_REQUEST_DT
, X_TT_REQ_BY.LOGIN X_TT_REQ_BY
, S_ORG_EXT_X.X_TT_REJECT_APP_DT
, X_TT_REJECT_APP_BY.LOGIN X_TT_REJECT_APP_BY
, S_ORG_EXT.X_ACCNT_POSTN_ID
, S_ORG_EXT_X.X_GROUP_CUST_NUM_TEXT

FROM S_ORG_EXT S_ORG_EXT(NOLOCK)
LEFT OUTER JOIN S_BU(NOLOCK) ON S_ORG_EXT.BU_ID = S_BU.ROW_ID
LEFT OUTER JOIN S_BU ORG_BU(NOLOCK) ON S_ORG_EXT.ROW_ID = ORG_BU.ROW_ID
LEFT OUTER JOIN S_ADDR_PER(NOLOCK) ON S_ORG_EXT.PR_ADDR_ID = S_ADDR_PER.ROW_ID
LEFT OUTER JOIN S_ORG_EXT_X(NOLOCK) ON S_ORG_EXT.ROW_ID = S_ORG_EXT_X.PAR_ROW_ID
LEFT OUTER JOIN S_USER X_TT_REQ_BY(NOLOCK) ON X_TT_REQ_BY.ROW_ID = S_ORG_EXT_X.X_TT_REQ_BY_ID
LEFT OUTER JOIN S_USER X_TT_REJECT_APP_BY(NOLOCK) ON X_TT_REJECT_APP_BY.ROW_ID = S_ORG_EXT_X.X_TT_REJECT_APP_BY_ID

LEFT OUTER JOIN S_ORG_EXT(NOLOCK) S_ORG_EXT_BU_NAME ON S_ORG_EXT.BU_ID = S_ORG_EXT_BU_NAME.ROW_ID
LEFT OUTER JOIN S_ORG_EXT_UTX(NOLOCK) ON S_ORG_EXT.ROW_ID = S_ORG_EXT_UTX.PAR_ROW_ID
LEFT OUTER JOIN S_ORG_EXT ORG(NOLOCK) ON S_ORG_EXT.PAR_BU_ID = ORG.ROW_ID
LEFT OUTER JOIN S_PARTY(NOLOCK) ON ORG.PAR_BU_ID = S_PARTY.ROW_ID
LEFT OUTER JOIN S_ORG_EXT(NOLOCK) PAR_ORG ON S_ORG_EXT.PAR_OU_ID = PAR_ORG.ROW_ID
LEFT OUTER JOIN S_REGION(NOLOCK) ON S_ORG_EXT.REGION_ID = S_REGION.ROW_ID
LEFT OUTER JOIN S_POSTN CONTACT_POST(NOLOCK) ON CONTACT_POST.ROW_ID = S_ORG_EXT.PR_POSTN_ID
LEFT OUTER JOIN S_CONTACT(NOLOCK) S_CONTACT_TIME ON S_CONTACT_TIME.ROW_ID = CONTACT_POST.PR_EMP_ID
LEFT OUTER JOIN S_TIMEZONE(NOLOCK) ON S_CONTACT_TIME.TIMEZONE_ID = S_TIMEZONE.ROW_ID
LEFT OUTER LOOP JOIN WC_SUMMERTIME SUMMER_X_LAST_VISIT_DT(NOLOCK) ON (
		SUMMER_X_LAST_VISIT_DT.TIMEZONE_ID = S_TIMEZONE.ROW_ID
		AND S_ORG_EXT.X_LAST_VISIT_DT BETWEEN SUMMER_X_LAST_VISIT_DT.START_DATE
			AND SUMMER_X_LAST_VISIT_DT.END_DATE
		)
LEFT OUTER JOIN S_ORG_EXT(NOLOCK) DISTRIBUTOR ON DISTRIBUTOR.ROW_ID = S_ORG_EXT_X.X_MAIN_DISTRIBUTOR_ID --CH015148
LEFT OUTER JOIN S_ADDR_PER ADDR(NOLOCK) ON ADDR.ROW_ID = DISTRIBUTOR.PR_ADDR_ID
LEFT OUTER JOIN S_ORG_EXT ORIGIN(NOLOCK) ON ORIGIN.ROW_ID = S_ORG_EXT_X.X_ORIG_ACCNT_ID
LEFT OUTER JOIN S_USER USR(NOLOCK) ON USR.ROW_ID = S_ORG_EXT.LAST_UPD_BY
LEFT OUTER JOIN S_ADDR_PER(NOLOCK) PAR_ADDR ON PAR_ORG.PR_ADDR_ID = PAR_ADDR.ROW_ID
LEFT OUTER JOIN CX_BANK_INFO(NOLOCK) CX_INFO ON CX_INFO.X_ACCNT_ID = S_ORG_EXT.ROW_ID --Defect 212
LEFT OUTER JOIN S_POSTN(NOLOCK) ORG_POSTN ON ORG.PR_MGR_POSTN_ID = ORG_POSTN.ROW_ID
LEFT OUTER JOIN S_CONTACT(NOLOCK) ORG_MGR ON ORG_POSTN.PR_EMP_ID = ORG_MGR.ROW_ID
LEFT OUTER JOIN S_POSTN(NOLOCK) ON S_ORG_EXT.PR_MGR_POSTN_ID = S_POSTN.ROW_ID
LEFT OUTER JOIN S_CONTACT(NOLOCK) ON S_POSTN.PR_EMP_ID = S_CONTACT.ROW_ID
LEFT OUTER JOIN S_ADDR_PER(NOLOCK) ADDRORG ON ORG.PR_ADDR_ID = ADDRORG.ROW_ID
LEFT OUTER JOIN S_ORG_EXT(NOLOCK) X_GROUP ON X_GROUP.ROW_ID = S_ORG_EXT.X_GROUP_ID
LEFT OUTER JOIN S_POSTN(NOLOCK) S_POSTN_ORG ON S_POSTN_ORG.ROW_ID = S_ORG_EXT.X_ACCNT_POSTN_ID
--LEFT OUTER JOIN S_ORG_EXT(NOLOCK) PAR_ACCNT ON S_ORG_EXT.PAR_OU_ID = PAR_ACCNT.ROW_ID --INC1891481
LEFT OUTER JOIN S_ORG_EXT_X(NOLOCK) PAR_ORG_X ON PAR_ORG_X.ROW_ID = PAR_ORG.ROW_ID
LEFT OUTER JOIN S_ORG_EXT(NOLOCK) EXE_AT ON S_ORG_EXT_X.X_EXE_AT_ID = EXE_AT.ROW_ID
LEFT OUTER JOIN S_ORG_EXT(NOLOCK) PAY_AT ON S_ORG_EXT_X.X_PAY_AT_ID = PAY_AT.ROW_ID
LEFT OUTER JOIN CX_BANK_ADMIN(NOLOCK) ON CX_BANK_ADMIN.ROW_ID = S_ORG_EXT_X.X_BANK_ID
LEFT OUTER JOIN S_ACCNT_POSTN(NOLOCK) ACC_POS ON ACC_POS.OU_EXT_ID = S_ORG_EXT.ROW_ID
	AND ACC_POS.POSITION_ID = S_ORG_EXT.PR_POSTN_ID
INNER JOIN S_PARTY PARTY ON PARTY.ROW_ID = S_ORG_EXT.PAR_ROW_ID
LEFT JOIN S_CONTACT BO ON BO.ROW_ID = S_ORG_EXT_X.X_BUSINESS_OWNER_ID
WHERE S_ORG_EXT_BU_NAME.LOC = 'UK' 
AND S_ORG_EXT.ROW_ID in ( '1-2OWSOL', '1-11BQS-2')
--AND X_TT_REQ_BY.LOGIN IS NOT NULL AND X_TT_REJECT_APP_BY.LOGIN IS NOT NULL
--WHERE S_ORG_EXT_X.X_TRADING_AS_TXT IS NOT NULL AND S_ORG_EXT_X.X_TT_EOID_TXT IS NOT NULL AND S_ORG_EXT_X.X_TT_FID_TXT IS NOT NULL AND  S_ORG_EXT_X.X_TT_UPDATE_STAT_CD IS NOT NULL AND S_ORG_EXT_X.X_TT_REQUEST_DT IS NOT NULL 
--AND X_TT_REQ_BY.LOGIN  IS NOT NULL AND S_ORG_EXT_X.X_TT_REJECT_APP_DT IS NOT NULL AND X_TT_REJECT_APP_BY.LOGIN IS NOT NULL AND S_ORG_EXT.X_ACCNT_POSTN_ID IS NOT NULL 