SELECT D.ROW_WID AS ROW_WID
	,D.ETL_PROC_WID AS ETL_PROC_WID
	,D.INTEGRATION_ID AS INTEGRATION_ID
	,D.DATASOURCE_NUM_ID AS DATASOURCE_NUM_ID
	,D.ATTRIB_93 AS ATTRIB_93
	,D.ATTRIB_53 AS ATTRIB_53
	,D.ATTRIB_52 AS ATTRIB_52
	,D.X_TRADING_AS_TXT AS X_TRADING_AS_TXT
	,D.X_TT_EOID_TXT AS X_TT_EOID_TXT
	,D.X_TT_FID_TXT AS X_TT_FID_TXT
	,D.X_TT_UPDATE_STAT_CD AS X_TT_UPDATE_STAT_CD
	,D.X_TT_REQUEST_DT AS X_TT_REQUEST_DT
	,D.X_TT_REQ_BY AS X_TT_REQ_BY
	,D.X_TT_REJECT_APP_DT AS X_TT_REJECT_APP_DT
	,D.X_TT_REJECT_APP_BY AS X_TT_REJECT_APP_BY
FROM WC_ORG_HISTORY_D D
INNER JOIN (
	SELECT MAX(ROW_WID) AS ROW_WID
	FROM WC_ORG_HISTORY_D
	GROUP BY INTEGRATION_ID
	) M ON M.ROW_WID = D.ROW_WID
	
AND EXISTS (
		SELECT 1
		FROM WC_ORG_DS
		WHERE D.INTEGRATION_ID = WC_ORG_DS.INTEGRATION_ID
		)


		SELECT * FROM W_PARAM_G ORDER BY 1 DESC 

		--UPDATE W_PARAM_G  SET ETL_PROC_WID = 10116