---DAY 1

UPDATE S_ORG_EXT_X 
SET S_ORG_EXT_X.ATTRIB_53 = 'EOID_TXT_CHG215394',
 S_ORG_EXT_X.ATTRIB_52 ='FID_TXT_CHG215394',
 S_ORG_EXT_X.X_TRADING_AS_TXT  =  NULL, 
 S_ORG_EXT_X.X_TT_EOID_TXT = NULL,
 S_ORG_EXT_X.X_TT_FID_TXT = NULL,
 S_ORG_EXT_X.X_TT_UPDATE_STAT_CD = NULL,
 S_ORG_EXT_X.X_TT_REQUEST_DT = NULL ,
 X_TT_REQ_BY_ID = NULL,
 S_ORG_EXT_X.X_TT_REJECT_APP_DT = null,
 X_TT_REJECT_APP_BY_ID = NULL 
 --S_ORG_EXT.X_ACCNT_POSTN_ID = 'POSTN_ID_CHG215394' 
WHERE ROW_ID = '1-11BQS-2' 

UPDATE S_ORG_EXT
SET S_ORG_EXT.ALIAS_NAME = 'RADING_AS_TXT_CHG215394' 
WHERE ROW_ID = '1-11BQS-2'

----DAY 2

UPDATE S_ORG_EXT_X 
SET S_ORG_EXT_X.ATTRIB_53 = 'EOID_TXT_CHG215394',
 S_ORG_EXT_X.ATTRIB_52 ='FID_TXT_CHG215394',
 S_ORG_EXT_X.X_TRADING_AS_TXT  = 'NEW_RADING_AS_TXT_CHG215394' , 
 S_ORG_EXT_X.X_TT_EOID_TXT = 'NEW_EOID_TXT_CHG215394',
 S_ORG_EXT_X.X_TT_FID_TXT ='NEW_FID_TXT_CHG215394',
 S_ORG_EXT_X.X_TT_UPDATE_STAT_CD = 'Pending',
 S_ORG_EXT_X.X_TT_REQUEST_DT = GETDATE() ,
 X_TT_REQ_BY_ID = '1-8Y20N',
 S_ORG_EXT_X.X_TT_REJECT_APP_DT = null,
 X_TT_REJECT_APP_BY_ID = NULL 
 --S_ORG_EXT.X_ACCNT_POSTN_ID = 'POSTN_ID_CHG215394' 
WHERE ROW_ID = '1-11BQS-2' 

UPDATE S_ORG_EXT
SET S_ORG_EXT.ALIAS_NAME = 'RADING_AS_TXT_CHG215394' 
WHERE ROW_ID = '1-11BQS-2'

------DAY 3

UPDATE S_ORG_EXT_X 
SET S_ORG_EXT_X.ATTRIB_53 = 'NEW_EOID_TXT_CHG215394',
 S_ORG_EXT_X.ATTRIB_52 ='NEW_FID_TXT_CHG215394',
 S_ORG_EXT_X.X_TRADING_AS_TXT  = 'NEW_RADING_AS_TXT_CHG215394' , 
 S_ORG_EXT_X.X_TT_EOID_TXT = 'NEW_EOID_TXT_CHG215394',
 S_ORG_EXT_X.X_TT_FID_TXT ='NEW_FID_TXT_CHG215394',
 S_ORG_EXT_X.X_TT_UPDATE_STAT_CD = 'Approved',
 S_ORG_EXT_X.X_TT_REQUEST_DT = GETDATE() ,
 X_TT_REQ_BY_ID = '1-8Y20N',
 S_ORG_EXT_X.X_TT_REJECT_APP_DT = GETDATE(),
 X_TT_REJECT_APP_BY_ID = '1-8Y20N' 
 --S_ORG_EXT.X_ACCNT_POSTN_ID = 'POSTN_ID_CHG215394' 
WHERE ROW_ID = '1-11BQS-2' 

UPDATE S_ORG_EXT
SET S_ORG_EXT.ALIAS_NAME = 'NEW_RADING_AS_TXT_CHG215394' 
WHERE ROW_ID = '1-11BQS-2'




select X_ACCNT_POSTN_ID, * from S_ORG_EXT where  ROW_ID = '1-11BQS-2'
update S_ORG_EXT set X_ACCNT_POSTN_ID = 1234 where ROW_ID = '1-11BQS-2'

select * from S_BU

SELECT * FROM S_ORG_EXT_X WHERE  ROW_ID = '1-11BQS-2'
GO

SELECT S_ORG_EXT.ROW_ID, S_ORG_EXT.ALIAS_NAME, S_ORG_EXT_X.ATTRIB_53, S_ORG_EXT_X.ATTRIB_52, S_ORG_EXT_X.X_TRADING_AS_TXT, S_ORG_EXT_X.X_TT_EOID_TXT
, S_ORG_EXT_X.X_TT_FID_TXT, S_ORG_EXT_X.X_TT_UPDATE_STAT_CD, S_ORG_EXT_X.X_TT_REQUEST_DT, S_ORG_EXT_X.X_TT_REQ_BY_ID, S_ORG_EXT_X.X_TT_REJECT_APP_DT, S_ORG_EXT_X.X_TT_REJECT_APP_BY_ID
, S_ORG_EXT.X_ACCNT_POSTN_ID,*
FROM S_ORG_EXT 
LEFT OUTER JOIN S_ORG_EXT_X ON S_ORG_EXT.ROW_ID = S_ORG_EXT_X.PAR_ROW_ID
WHERE S_ORG_EXT.ROW_ID = '1-11BQS-2'

--where ALIAS_NAME = 'Acc_29042016'

SELECT TOP 1 ALIAS_NAME FROM S_ORG_EXT

select * from S_ORG_EXT where ALIAS_NAME = 'Acc_29042016'



ALTER VIEW V_ORG_EXT AS SELECT * FROM S_ORG_EXT WHERE ROW_ID in ( '1-2OWSOL', '1-11BQS-2')
GO

SELECT * FROM V_ORG_EXT

SELECT * FROM S_PARTY WHERE ROW_ID = '1-11BQS-2'

DELETE FROM EIM_ACCNT_DTL WHERE ROW_ID =  '1-11BQS-2'

SELECT ROW_ID, IF_ROW_STAT,* FROM EIM_ACCNT_DTL WHERE ROW_ID in ('1-11BQS-2')




1-8XL3L