SELECT * FROM S_LST_OF_VAL WHERE TYPE ='FS_ORDER_TYPE_CODE' AND LANG_ID = 'EIR'




select X_ORDER_CAT_CD ,* from EIM_ORDER_DTL
select X_ORDER_CAT_CD,* from PRE_EIM_ORDERS_OD

SELECT * FROM WC_ERRORS_G WHERE FILE_NAME LIKE '%IEOD0501_20211118_10%'


SELECT IF_ROW_STAT,* FROM EIM_ORDER WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')
SELECT IF_ROW_STAT,* FROM EIM_ORDER1 WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')

select X_ORDER_CAT_CD,* from PRE_EIM_ORDERS_OD
SELECT IF_ROW_STAT,X_ORDER_CAT_CD ,* FROM EIM_ORDER_DTL WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')



DELETE FROM EIM_ORDER WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')
DELETE FROM EIM_ORDER1 WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')
DELETE  FROM EIM_ORDER_DTL WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')
DELETE  FROM PRE_EIM_ORDERS_OD WHERE ORD_ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')

SELECT ORDER_NUM, * FROM S_ORDER WHERE ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')
SELECT X_ORDER_CAT_CD, * FROM S_ORDER_X WHERE PAR_ROW_ID IN (SELECT ROW_ID FROM S_ORDER WHERE ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2'))




delete from S_ORDER where ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2')
delete from S_ORDER_X WHERE PAR_ROW_ID IN (SELECT ROW_ID FROM S_ORDER WHERE ORDER_NUM IN ('TEST_ORDER_1','TEST_ORDER_2'))
