IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[MERGE_WC_SALES_F_SK]'))
DROP TABLE [dbo].[MERGE_WC_SALES_F_SK]
GO 

CREATE TABLE [dbo].[MERGE_WC_SALES_F_SK](
	[ROW_WID] [numeric](15, 0) NOT NULL,
	[DATASOURCE_NUM_ID] [numeric](10, 0) NOT NULL,
	[INTEGRATION_ID] [nvarchar](30) NOT NULL,
	[ETL_PROC_WID] [numeric](10, 0) NOT NULL,
	[SALES_TYPE_WID] [numeric](10, 0) NOT NULL,
	[START_DT_WID] [numeric](10, 0) NOT NULL,
	[END_DT_WID] [numeric](10, 0) NOT NULL,
	[PRODUCT_WID] [numeric](10, 0) NOT NULL,
	[PROM_MAT_WID] [numeric](10, 0) NOT NULL,
	[ACCNT_WID] [numeric](10, 0) NOT NULL,
	[TGT_ACCNT_WID] [numeric](10, 0) NOT NULL,
	[GEO_WID] [numeric](10, 0) NOT NULL,
	[VENDING_M_WID] [numeric](10, 0) NOT NULL,
	[ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[GROSS_MARGIN] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[NET_MARGIN] [numeric](21, 7) NULL,
	[NET_MARGIN_USD] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[CONTRIBUTION] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[OPERATING_PROFIT] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[TAX_AMOUNT] [numeric](21, 7) NULL,
	[TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[PROM_MAT_QTY] [numeric](15, 0) NULL,
	[AMT_CURCY] [nvarchar](15) NULL,
	[COUNTRY_CODE] [nvarchar](2) NOT NULL,
	[CHANNEL_WID] [numeric](10, 0) NULL,
	[SEGMENT_WID] [numeric](10, 0) NULL,
	[D_POSTN_WID2] [numeric](10, 0) NULL,
	[QUOTE_WID] [numeric](10, 0) NULL,
	[X_BU_ID] [nvarchar](30) NULL,
	[PERIOD_WID] [numeric](10, 0) NULL,
	[MONTH_WID] [numeric](10, 0) NULL,
	[YEAR_WID] [numeric](10, 0) NULL,
	[POSTN_WID] [numeric](10, 0) NULL,
	[SALES_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOM_FIELD_1] [nvarchar](50) NULL,
	[CUSTOM_FIELD_2] [nvarchar](50) NULL,
	[CUSTOM_FIELD_3] [nvarchar](50) NULL,
	[CUSTOM_FIELD_4] [nvarchar](50) NULL,
	[CUSTOM_FIELD_5] [nvarchar](50) NULL,
	[CUSTOM_FIELD_6] [nvarchar](50) NULL,
	[CUSTOM_FIELD_7] [nvarchar](50) NULL,
	[CUSTOM_FIELD_8] [nvarchar](50) NULL,
	[CUSTOM_FIELD_9] [nvarchar](50) NULL,
	[CUSTOM_FIELD_10] [nvarchar](50) NULL,
	[CUSTOM_FIELD_11] [nvarchar](50) NULL,
	[CUSTOM_FIELD_12] [nvarchar](50) NULL,
	[MANUFACTURER_COGS] [numeric](21, 7) NULL,
	[MANUFACTURER_COGS_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE_USD] [numeric](21, 7) NULL,
	[WHOLESALER_TAX] [numeric](21, 7) NULL,
	[WHOLESALER_TAX_USD] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED1_PRICE] [numeric](21, 7) NULL,
	[INTERMED1_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED1_TAX] [numeric](21, 7) NULL,
	[INTERMED1_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED2_PRICE] [numeric](21, 7) NULL,
	[INTERMED2_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED2_TAX] [numeric](21, 7) NULL,
	[INTERMED2_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED3_PRICE] [numeric](21, 7) NULL,
	[INTERMED3_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED3_TAX] [numeric](21, 7) NULL,
	[INTERMED3_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_PRICE] [numeric](21, 7) NULL,
	[RETAILER_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_TAX] [numeric](21, 7) NULL,
	[RETAILER_TAX_USD] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[X_STANDARD_COST] [numeric](21, 7) NULL,
	[X_STANDARD_COST_USD] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST_USD] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS_USD] [numeric](21, 7) NULL,
	[CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[SALES_TYPE_DESC] [nvarchar](30) NULL,
	[OOS_PRODUCT_WID] [numeric](10, 0) NULL,
	[X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL,
	[INTEGRATION_ID2] [nvarchar](32) NULL,
 CONSTRAINT [MERGE_WC_SALES_F_SK_PK] PRIMARY KEY NONCLUSTERED 
(
	[SALES_TYPE_WID] ASC,
	[ROW_WID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_PRODUCT_WID]  DEFAULT ((0)) FOR [PRODUCT_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_PROM_MAT_WID]  DEFAULT ((0)) FOR [PROM_MAT_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_ACCNT_WID]  DEFAULT ((0)) FOR [ACCNT_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_TGT_ACCNT_WID]  DEFAULT ((0)) FOR [TGT_ACCNT_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_GEO_WID]  DEFAULT ((0)) FOR [GEO_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_VENDING_M_WID]  DEFAULT ((0)) FOR [VENDING_M_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_COGS]  DEFAULT ((0)) FOR [MANUFACTURER_COGS]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_COGS_USD]  DEFAULT ((0)) FOR [MANUFACTURER_COGS_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_PRICE]  DEFAULT ((0)) FOR [MANUFACTURER_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_PRICE_USD]  DEFAULT ((0)) FOR [MANUFACTURER_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_TAX]  DEFAULT ((0)) FOR [MANUFACTURER_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_TAX_USD]  DEFAULT ((0)) FOR [MANUFACTURER_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_GROSS_MARGIN]  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_PRICE]  DEFAULT ((0)) FOR [WHOLESALER_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_PRICE_USD]  DEFAULT ((0)) FOR [WHOLESALER_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_TAX]  DEFAULT ((0)) FOR [WHOLESALER_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_TAX_USD]  DEFAULT ((0)) FOR [WHOLESALER_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_GROSS_MARGIN]  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_PRICE]  DEFAULT ((0)) FOR [INTERMED1_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_PRICE_USD]  DEFAULT ((0)) FOR [INTERMED1_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_TAX]  DEFAULT ((0)) FOR [INTERMED1_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_TAX_USD]  DEFAULT ((0)) FOR [INTERMED1_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_GROSS_MARGIN]  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_PRICE]  DEFAULT ((0)) FOR [INTERMED2_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_PRICE_USD]  DEFAULT ((0)) FOR [INTERMED2_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_TAX]  DEFAULT ((0)) FOR [INTERMED2_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_TAX_USD]  DEFAULT ((0)) FOR [INTERMED2_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_GROSS_MARGIN]  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_PRICE]  DEFAULT ((0)) FOR [INTERMED3_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_PRICE_USD]  DEFAULT ((0)) FOR [INTERMED3_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_TAX]  DEFAULT ((0)) FOR [INTERMED3_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_TAX_USD]  DEFAULT ((0)) FOR [INTERMED3_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_GROSS_MARGIN]  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_SELLIN_PRICE]  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_SELLIN_PRICE_USD]  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_PRICE]  DEFAULT ((0)) FOR [RETAILER_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_PRICE_USD]  DEFAULT ((0)) FOR [RETAILER_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_TAX]  DEFAULT ((0)) FOR [RETAILER_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_TAX_USD]  DEFAULT ((0)) FOR [RETAILER_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_GROSS_MARGIN]  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_STANDARD_COST]  DEFAULT ((0)) FOR [X_STANDARD_COST]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_STANDARD_COST_USD]  DEFAULT ((0)) FOR [X_STANDARD_COST_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_DISTRIBUTION_COST]  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_DISTRIBUTION_COST_USD]  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_OTHER_COSTS_OF_GOODS]  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_OTHER_COSTS_OF_GOODS_USD]  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CUSTOM_SALES_FIGURES_1]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CUSTOM_SALES_FIGURES_2]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CUSTOM_SALES_FIGURES_3]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_DELIVERED_QTY]  DEFAULT ((0)) FOR [X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_DELIVERED_PACK]  DEFAULT ((0)) FOR [X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_GROSS_MARGIN_CONF]  DEFAULT ((0)) FOR [GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_NET_MARGIN_CONF]  DEFAULT ((0)) FOR [NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_PRODUCT_MARGIN_CONF]  DEFAULT ((0)) FOR [PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CONTRIBUTION_CONF]  DEFAULT ((0)) FOR [CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_OPERATING_PROFIT_CONF]  DEFAULT ((0)) FOR [OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_GROSS_MARGIN_USD_CONF]  DEFAULT ((0)) FOR [GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_NET_MARGIN_USD_CONF]  DEFAULT ((0)) FOR [NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_PRODUCT_MARGIN_USD_CONF]  DEFAULT ((0)) FOR [PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CONTRIBUTION_USD_CONF]  DEFAULT ((0)) FOR [CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_OPERATING_PROFIT_USD_CONF]  DEFAULT ((0)) FOR [OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK]  WITH CHECK ADD  CONSTRAINT [MERGE_WC_SALES_F_SK_COUNTRY_CODE] CHECK  (([COUNTRY_CODE]='SK'))
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] CHECK CONSTRAINT [MERGE_WC_SALES_F_SK_COUNTRY_CODE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK]  WITH CHECK ADD  CONSTRAINT [MERGE_WC_SALES_F_SK_PERIOD_LEVEL] CHECK  (([SALES_TYPE_WID]>=(59000) AND [SALES_TYPE_WID]<=(60999)))
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] CHECK CONSTRAINT [MERGE_WC_SALES_F_SK_PERIOD_LEVEL]
GO


