IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_M_A_BRAND_SK]'))
DROP TABLE [dbo].[WC_SALES_M_A_BRAND_SK]
GO 

CREATE TABLE [dbo].[WC_SALES_M_A_BRAND_SK](
	[ROW_WID] [numeric](10, 0) NOT NULL,
	[COUNTRY_CODE] [nvarchar](2) NOT NULL,
	[MONTH_WID] [numeric](10, 0) NOT NULL,
	[SALES_TYPE_WID] [numeric](10, 0) NOT NULL,
	[PRODUCT_WID] [numeric](10, 0) NULL,
	[PROM_MAT_WID] [numeric](10, 0) NULL,
	[ACCNT_WID] [numeric](10, 0) NULL,
	[TGT_ACCNT_WID] [numeric](10, 0) NULL,
	[GEO_WID] [numeric](10, 0) NULL,
	[VENDING_M_WID] [numeric](10, 0) NULL,
	[CHANNEL_WID] [numeric](10, 0) NULL,
	[SEGMENT_WID] [numeric](10, 0) NULL,
	[D_POSTN_WID2] [numeric](10, 0) NULL,
	[AMT_CURCY] [nvarchar](15) NULL,
	[ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[GROSS_MARGIN] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[NET_MARGIN] [numeric](21, 7) NULL,
	[NET_MARGIN_USD] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[CONTRIBUTION] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[OPERATING_PROFIT] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[TAX_AMOUNT] [numeric](21, 7) NULL,
	[TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[PROM_MAT_QTY] [numeric](15, 0) NULL,
	[YTD_ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[YTD_ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[YTD_ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[YTD_ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[YTD_ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[YTD_ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN_USD] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[YTD_MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[YTD_MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[YTD_SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[YTD_SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[YTD_TAX_AMOUNT] [numeric](21, 7) NULL,
	[YTD_TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[YTD_PROM_MAT_QTY] [numeric](15, 0) NULL,
	[QUOTE_WID] [numeric](10, 0) NULL,
	[X_BU_ID] [nvarchar](30) NULL,
	[ASSMT_ST_DT_WID] [numeric](10, 0) NULL,
	[ETL_PROC_WID] [numeric](10, 0) NULL,
	[MAT_ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[MAT_ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[MAT_ACTL_GROSS_SHIPMENT_AMT] [numeric](22, 7) NULL,
	[MAT_ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](22, 7) NULL,
	[MAT_ACTL_NET_SHIPMENT_AMT] [numeric](22, 7) NULL,
	[MAT_ACTL_NET_SHIPMENT_AMT_USD] [numeric](22, 7) NULL,
	[MAT_GROSS_MARGIN] [numeric](22, 7) NULL,
	[MAT_GROSS_MARGIN_USD] [numeric](22, 7) NULL,
	[MAT_NET_MARGIN] [numeric](22, 7) NULL,
	[MAT_NET_MARGIN_USD] [numeric](22, 7) NULL,
	[MAT_PRODUCT_MARGIN] [numeric](22, 7) NULL,
	[MAT_PRODUCT_MARGIN_USD] [numeric](22, 7) NULL,
	[MAT_MARKET_EXPENDITURE] [numeric](22, 7) NULL,
	[MAT_MARKET_EXPENDITURE_USD] [numeric](22, 7) NULL,
	[MAT_SALES_EXPENDITURE] [numeric](22, 7) NULL,
	[MAT_SALES_EXPENDITURE_USD] [numeric](22, 7) NULL,
	[MAT_CONTRIBUTION] [numeric](22, 7) NULL,
	[MAT_CONTRIBUTION_USD] [numeric](22, 7) NULL,
	[MAT_OPERATING_PROFIT] [numeric](22, 7) NULL,
	[MAT_OPERATING_PROFIT_USD] [numeric](22, 7) NULL,
	[MAT_TAX_AMOUNT] [numeric](22, 7) NULL,
	[MAT_TAX_AMOUNT_USD] [numeric](22, 7) NULL,
	[MAT_PROM_MAT_QTY] [numeric](22, 7) NULL,
	[SALES_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[YTD_SALES_DISCOUNT] [numeric](22, 7) NULL,
	[YTD_CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[MAT_SALES_DISCOUNT] [numeric](22, 7) NULL,
	[MAT_CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[GROSS_SALES] [numeric](38, 7) NULL,
	[GROSS_SALES_USD] [numeric](38, 7) NULL,
	[NET_SALES] [numeric](38, 7) NULL,
	[NET_SALES_USD] [numeric](38, 7) NULL,
	[MANUFACTURER_COGS] [numeric](21, 7) NULL,
	[MANUFACTURER_COGS_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE_USD] [numeric](21, 7) NULL,
	[WHOLESALER_TAX] [numeric](21, 7) NULL,
	[WHOLESALER_TAX_USD] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED1_PRICE] [numeric](21, 7) NULL,
	[INTERMED1_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED1_TAX] [numeric](21, 7) NULL,
	[INTERMED1_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED2_PRICE] [numeric](21, 7) NULL,
	[INTERMED2_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED2_TAX] [numeric](21, 7) NULL,
	[INTERMED2_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED3_PRICE] [numeric](21, 7) NULL,
	[INTERMED3_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED3_TAX] [numeric](21, 7) NULL,
	[INTERMED3_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_PRICE] [numeric](21, 7) NULL,
	[RETAILER_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_TAX] [numeric](21, 7) NULL,
	[RETAILER_TAX_USD] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[X_STANDARD_COST] [numeric](21, 7) NULL,
	[X_STANDARD_COST_USD] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST_USD] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS_USD] [numeric](21, 7) NULL,
	[CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[YTD_CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[YTD_CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[YTD_CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[SALES_TYPE_DESC] [nvarchar](30) NULL,
	[X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[YTD_X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[YTD_X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MAT_SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MAT_CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_CUST_FIG1]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_CUST_FIG2]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_CUST_FIG3]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_YTD_CUST_FIG1]  DEFAULT ((0)) FOR [YTD_CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_YTD_CUST_FIG2]  DEFAULT ((0)) FOR [YTD_CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_YTD_CUST_FIG3]  DEFAULT ((0)) FOR [YTD_CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_M_A_BRAND_SK_CON_SALES_TYPE_WID] CHECK  (([SALES_TYPE_WID]>=(56000) AND [SALES_TYPE_WID]<=(56999)))
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] CHECK CONSTRAINT [WC_SALES_M_A_BRAND_SK_CON_SALES_TYPE_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_M_A_BRAND_SK_COUNTRY_CODE] CHECK  (([COUNTRY_CODE]='SK'))
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] CHECK CONSTRAINT [WC_SALES_M_A_BRAND_SK_COUNTRY_CODE]
GO


