IF  NOT EXISTS (select * from sys.partition_functions where name = 'pf_SALES_TYPE_WID_HU')
CREATE PARTITION FUNCTION [pf_SALES_TYPE_WID_HU](numeric(10,0)) AS RANGE LEFT FOR VALUES (69999, 70000, 70001, 70003, 71018, 71019, 71020, 71021)
GO 


IF  NOT EXISTS (select * from sys.partition_functions where name = 'pf_SALES_TYPE_WID_SK')
CREATE PARTITION FUNCTION [pf_SALES_TYPE_WID_SK](numeric(10,0)) AS RANGE LEFT FOR VALUES (58999, 59000, 59001, 59003, 60018, 60019, 60020, 60021)
GO



IF NOT  EXISTS (SELECT * FROM sys.partition_schemes where name = 'ps_SALES_TYPE_WID_HU')
CREATE PARTITION SCHEME [ps_SALES_TYPE_WID_HU] AS PARTITION [pf_SALES_TYPE_WID_HU] TO ([PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY])
GO


IF  NOT EXISTS (SELECT * FROM sys.partition_schemes where name = 'ps_SALES_TYPE_WID_SK')
CREATE PARTITION SCHEME [ps_SALES_TYPE_WID_SK] AS PARTITION [pf_SALES_TYPE_WID_SK] TO ([PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY])
GO 











