IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_RTLAUDIT_M_TREND_A_SK]'))
DROP TABLE [dbo].[WC_RTLAUDIT_M_TREND_A_SK]
GO 

CREATE TABLE [dbo].[WC_RTLAUDIT_M_TREND_A_SK](
	[ROW_WID] [numeric](10, 0) NULL,
	[MONTH_WID] [numeric](10, 0) NOT NULL,
	[PROD_WID] [numeric](10, 0) NOT NULL,
	[ACCNT_WID] [numeric](10, 0) NULL,
	[INVLOC_WID] [numeric](10, 0) NULL,
	[DISPLAY_FLG] [nchar](1) NULL,
	[OUT_OF_STOCK_FLG] [nchar](1) NULL,
	[FACING_NUM] [numeric](22, 7) NULL,
	[SLOTS_NUM] [numeric](10, 0) NULL,
	[ACTIVITY_TYPE] [numeric](10, 0) NULL,
	[REPLENISH_FLG] [nchar](1) NULL,
	[REPLENISH_QTY] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[BASE_ENTRY_FLG] [nvarchar](3) NULL,
	[OWNER_POSTN_WID] [numeric](10, 0) NULL,
	[EMP_WID] [numeric](10, 0) NULL,
	[TC_FACING_NUM] [numeric](22, 7) NULL,
	[BU_ID] [nvarchar](30) NULL,
	[ATTRIB_117] [numeric](22, 7) NULL,
	[CORRECTED_OOS] [nchar](1) NULL,
	[ATTRIB_52] [numeric](10, 0) NULL,
	[ATTRIB_96] [nchar](1) NULL,
	[STOCK_NUM] [numeric](10, 0) NULL,
	[ATTRIB_121] [numeric](10, 0) NULL,
	[ATTRIB_122] [numeric](10, 0) NULL,
	[X_SELLING_CARTON_AMT] [numeric](18, 3) NULL,
	[X_SELLING_CARTON_AMT_USD] [numeric](18, 3) NULL,
	[ATTRIB_119] [nchar](1) NULL,
	[X_NB_FACINGS_OOS] [numeric](18, 3) NULL,
	[X_SKU_POS_CD1] [nvarchar](30) NULL,
	[X_SKU_POS_CD2] [nvarchar](30) NULL,
	[X_OOS_REASON_CD] [nvarchar](30) NULL,
	[X_CONTRACT_PRD_FLG] [nchar](1) NULL,
	[U_PRICE_PT] [numeric](22, 7) NULL,
	[X_STD_PRICE_PACK_REACHED] [nchar](1) NULL,
	[X_STD_PRICE_CARTON_REACHED] [nchar](1) NULL,
	[U_CURCY_CD] [nvarchar](20) NULL,
	[ATTRIB_115] [nvarchar](20) NULL,
	[PRICE_PT] [numeric](22, 7) NULL,
	[ATTRIB_106] [numeric](22, 7) NULL,
	[ATTRIB_116] [numeric](22, 7) NULL,
	[X_SKU_POS_CD4] [nvarchar](30) NULL,
	[INVLOV_SLOTS_NUM] [numeric](10, 0) NULL,
	[INVLOC_FACINGS_NUM] [numeric](10, 0) NULL,
	[X_EXPIRED_PRODUCTS_FLG] [nchar](1) NULL,
	[PROD_POSITION] [nvarchar](30) NULL,
	[ACTIVITY_TYPE_VAL] [nvarchar](30) NULL,
	[PROD_IMPORTANCE] [nvarchar](30) NULL,
	[X_SIS_CONTRACT_FLG] [nchar](1) NULL,
	[RTLAUDIT_PREV_WID] [numeric](10, 0) NULL,
	[ATTRIB_02] [numeric](22, 7) NULL,
	[X_PMP_FLG] [nvarchar](1) NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WC_RTLAUDIT_M_TREND_A_SK] ADD  DEFAULT ((0)) FOR [MONTH_WID]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_M_TREND_A_SK] ADD  DEFAULT ((0)) FOR [PROD_WID]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_M_TREND_A_SK] ADD  DEFAULT ((0)) FOR [ACCNT_WID]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_M_TREND_A_SK] ADD  DEFAULT ((0)) FOR [INVLOC_WID]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_M_TREND_A_SK] ADD  DEFAULT ((0)) FOR [ACTIVITY_TYPE]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_M_TREND_A_SK] ADD  DEFAULT ((0)) FOR [RTLAUDIT_PREV_WID]
GO


