----------- BEGIN CREATE TABLE [WC_DAY_D_SK]--------------------------

PRINT 'CREATE TABLE [WC_DAY_D_SK]'
GO

IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]'))
DROP TABLE [dbo].[WC_DAY_D_SK]
GO 

CREATE TABLE [dbo].[WC_DAY_D_SK](
	[ROW_WID] [numeric](10, 0) NULL,
	[CALENDAR_DATE] [datetime] NULL,
	[CAL_HALF] [numeric](2, 0) NULL,
	[CAL_MONTH] [numeric](2, 0) NULL,
	[CAL_TRIMESTER] [numeric](10, 0) NULL,
	[CAL_WEEK] [numeric](2, 0) NULL,
	[CAL_YEAR] [numeric](4, 0) NULL,
	[DAY_DT] [datetime] NULL,
	[DAY_OF_MONTH] [numeric](2, 0) NULL,
	[DAY_OF_WEEK] [numeric](1, 0) NULL,
	[DAY_OF_YEAR] [numeric](3, 0) NULL,
	[JULIAN_MONTH_NUM] [numeric](10, 0) NULL,
	[MONTH_AGO_WID] [numeric](10, 0) NULL,
	[PERIOD_KEY] [numeric](10, 0) NULL,
	[QUARTER_AGO_WID] [numeric](10, 0) NULL,
	[WEEK_AGO_WID] [numeric](10, 0) NULL,
	[YEAR_AGO_WID] [numeric](10, 0) NULL,
	[DAY_NAME] [nvarchar](30) NULL,
	[MONTH_NAME] [nvarchar](30) NULL,
	[PER_NAME_FSCL_MNTH] [nvarchar](50) NULL,
	[PER_NAME_FSCL_QTR] [nvarchar](50) NULL,
	[PER_NAME_FSCL_WEEK] [nvarchar](50) NULL,
	[PER_NAME_FSCL_YEAR] [nvarchar](50) NULL,
	[PER_NAME_HALF] [nvarchar](50) NULL,
	[PER_NAME_MONTH] [nvarchar](50) NULL,
	[PER_NAME_QTR] [nvarchar](50) NULL,
	[PER_NAME_TER] [nvarchar](50) NULL,
	[PER_NAME_WEEK] [nvarchar](50) NULL,
	[CAL_DAY_OF_WEEK] [numeric](1, 0) NULL,
	[RECAL_WEEK] [numeric](2, 0) NULL,
	[CAL_PER_NAME_WEEK] [nvarchar](50) NULL,
	[RECAL_WEEK_YEAR] [nvarchar](50) NULL,
	[ISO_WEEK_DATE] [nvarchar](50) NULL,
	[FIRST_DAY_YR_WID] [numeric](10, 0) NULL,
	[FIRST_DAY_YAGO_WID] [numeric](10, 0) NULL,
	[FIRST_DAY_MTH_WID] [numeric](10, 0) NULL,
	[FIRST_DAY_MTH_YAGO_WID] [numeric](10, 0) NULL,
	[FIRST_DAY_WEEK_WID] [numeric](10, 0) NULL,
	[LAST_DAY_WEEK_FLG] [nvarchar](1) NULL,
	[LAST_DAY_MTH_FLG] [nvarchar](1) NULL,
	[FST_WEEKDAY_YAGO_WID] [numeric](10, 0) NULL,
	[WEEKDAY_YAGO_WID] [numeric](10, 0) NULL,
	[BI_MONTH] [nvarchar](2) NULL,
	[BI_MONTH_YR] [nvarchar](7) NULL,
	[DSD_WEEK] [nvarchar](30) NULL,
	[DAY_WEIGHT] [numeric](22, 7) NULL,
	[DAY_WEIGHT_YAGO] [numeric](22, 7) NULL,
	[CUSTOM_CYCLE_1] [nvarchar](30) NULL,
	[CUSTOM_CYCLE_2] [nvarchar](30) NULL,
	[CUSTOM_CYCLE_3] [nvarchar](30) NULL,
	[CUSTOM_CYCLE_4] [nvarchar](30) NULL,
	[CUSTOM_CYCLE_5] [nvarchar](30) NULL,
	[BU_ID] [nvarchar](15) NULL,
	[COUNTRY_CODE] [nvarchar](2) NULL,
	[FIRST_DAY_MTH_FLG] [nvarchar](1) NULL,
	[FIRST_DAY_WEEK_FLG] [nvarchar](1) NULL,
	[TOTAL_MONTH_SELL_DAYS] [numeric](10, 0) NULL,
	[TOTAL_MONTH_SELL_DAYS_YAGO] [numeric](22, 10) NULL,
	[MONTH_WEIGHT] [numeric](22, 7) NULL,
	[MONTH_WEIGHT_YAGO] [numeric](22, 7) NULL,
	[MONTH_SELL_DAYS] [numeric](22, 10) NULL,
	[MONTH_SELL_DAYS_YAGO] [numeric](22, 10) NULL,
	[DAY_NAME_LOCALIZED] [nvarchar](30) NULL,
	[MONTH_NAME_LOCALIZED] [nvarchar](30) NULL,
	[TOTAL_MONTH_SELL_DAYS_MAGO] [numeric](10, 0) NULL,
	[MONTH_SELL_DAYS_MAGO] [numeric](10, 0) NULL,
	[MONTH_WEIGHT_MAGO] [numeric](10, 0) NULL,
	[DTW_CALENDAR_DATE]  AS (CONVERT([date],[CALENDAR_DATE])) PERSISTED
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_F2]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_F2] ON [dbo].[WC_DAY_D_SK]
(
	[WEEK_AGO_WID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_F7]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_F7] ON [dbo].[WC_DAY_D_SK]
(
	[YEAR_AGO_WID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_Govn_Perf_idx1]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_Govn_Perf_idx1] ON [dbo].[WC_DAY_D_SK]
(
	[PER_NAME_MONTH] ASC,
	[ISO_WEEK_DATE] ASC
)
INCLUDE ( 	[ROW_WID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_Govn_Perf_idx2]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_Govn_Perf_idx2] ON [dbo].[WC_DAY_D_SK]
(
	[CAL_YEAR] ASC,
	[PER_NAME_WEEK] ASC,
	[CAL_WEEK] ASC,
	[CALENDAR_DATE] ASC
)
INCLUDE ( 	[ROW_WID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_Govn_Perf_idx3]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_Govn_Perf_idx3] ON [dbo].[WC_DAY_D_SK]
(
	[CAL_YEAR] ASC,
	[CAL_MONTH] ASC,
	[CALENDAR_DATE] ASC
)
INCLUDE ( 	[ROW_WID]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M1]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M1] ON [dbo].[WC_DAY_D_SK]
(
	[CAL_WEEK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M16]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M16] ON [dbo].[WC_DAY_D_SK]
(
	[PER_NAME_WEEK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M17]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M17] ON [dbo].[WC_DAY_D_SK]
(
	[PER_NAME_MONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M18]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M18] ON [dbo].[WC_DAY_D_SK]
(
	[PER_NAME_QTR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M2]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M2] ON [dbo].[WC_DAY_D_SK]
(
	[CAL_MONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M23]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M23] ON [dbo].[WC_DAY_D_SK]
(
	[JULIAN_MONTH_NUM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M39]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M39] ON [dbo].[WC_DAY_D_SK]
(
	[DAY_DT] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M5]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M5] ON [dbo].[WC_DAY_D_SK]
(
	[CAL_YEAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M6]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M6] ON [dbo].[WC_DAY_D_SK]
(
	[DAY_OF_WEEK] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_M9]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_M9] ON [dbo].[WC_DAY_D_SK]
(
	[DAY_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_MS_Recommended_20080410183428_5493]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_MS_Recommended_20080410183428_5493] ON [dbo].[WC_DAY_D_SK]
(
	[CALENDAR_DATE] ASC,
	[CAL_YEAR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_P1]')
CREATE UNIQUE CLUSTERED INDEX [WC_DAY_D_SK_P1] ON [dbo].[WC_DAY_D_SK]
(
	[ROW_WID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_PERF_IDX_2_12_1]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_PERF_IDX_2_12_1] ON [dbo].[WC_DAY_D_SK]
(
	[CALENDAR_DATE] ASC,
	[CAL_MONTH] ASC,
	[ROW_WID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_PERF_IDX_2_16_1]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_PERF_IDX_2_16_1] ON [dbo].[WC_DAY_D_SK]
(
	[ROW_WID] ASC,
	[CALENDAR_DATE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_PERF_IDX_2_49_1]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_PERF_IDX_2_49_1] ON [dbo].[WC_DAY_D_SK]
(
	[MONTH_NAME] ASC,
	[ROW_WID] ASC,
	[PER_NAME_MONTH] ASC,
	[YEAR_AGO_WID] ASC,
	[CALENDAR_DATE] ASC
)
INCLUDE ( 	[CAL_MONTH]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_PERF_IDX_2_6_1]')
CREATE NONCLUSTERED INDEX [WC_DAY_D_SK_PERF_IDX_2_6_1] ON [dbo].[WC_DAY_D_SK]
(
	[MONTH_NAME] ASC,
	[ROW_WID] ASC,
	[CAL_MONTH] ASC,
	[PER_NAME_MONTH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO


IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_WC_DAY_DHL_U1]')
CREATE UNIQUE NONCLUSTERED INDEX [WC_DAY_D_SK_WC_DAY_DHL_U1] ON [dbo].[WC_DAY_D_SK]
(
	[BU_ID] ASC,
	[ROW_WID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_DAY_D_SK]') AND name = N'[WC_DAY_D_SK_WC_DAY_DHL_U2]')
CREATE UNIQUE NONCLUSTERED INDEX [WC_DAY_D_SK_WC_DAY_DHL_U2] ON [dbo].[WC_DAY_D_SK]
(
	[COUNTRY_CODE] ASC,
	[ROW_WID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95)

GO

------------------------- END CREATE TABLE [WC_DAY_D_SK] --------------------------

