IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_RTLAUDIT_ML_M_TREND_A_SK]'))
DROP TABLE [dbo].[WC_RTLAUDIT_ML_M_TREND_A_SK]
GO 

CREATE TABLE [dbo].[WC_RTLAUDIT_ML_M_TREND_A_SK](
	[ROW_WID] [numeric](10, 0) NOT NULL,
	[MONTH_WID] [numeric](10, 0) NULL,
	[ACCNT_WID] [numeric](10, 0) NULL,
	[INVLOC_WID] [numeric](10, 0) NULL,
	[ACTIVITY_TYPE] [numeric](10, 0) NULL,
	[OWNER_POSTN_WID] [numeric](10, 0) NULL,
	[EMP_WID] [numeric](10, 0) NULL,
	[BU_ID] [nvarchar](30) NOT NULL,
	[INVLOV_SLOTS_NUM] [numeric](10, 0) NULL,
	[INVLOC_FACINGS_NUM] [numeric](10, 0) NULL,
	[ATTRIB_117] [numeric](22, 7) NULL,
	[ATTRIB_121] [numeric](10, 0) NULL,
	[BASE_ENTRY_FLG] [nvarchar](3) NULL
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[WC_RTLAUDIT_ML_M_TREND_A_SK] ADD  CONSTRAINT [DF_WC_RTLAUDIT_ML_M_TREND_A_SK_MONTH_WID]  DEFAULT ((0)) FOR [MONTH_WID]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_ML_M_TREND_A_SK] ADD  CONSTRAINT [DF_WC_RTLAUDIT_ML_M_TREND_A_SK_ACCNT_WID]  DEFAULT ((0)) FOR [ACCNT_WID]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_ML_M_TREND_A_SK] ADD  CONSTRAINT [DF_WC_RTLAUDIT_ML_M_TREND_A_SK_INVLOC_WID]  DEFAULT ((0)) FOR [INVLOC_WID]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_ML_M_TREND_A_SK] ADD  CONSTRAINT [DF_WC_RTLAUDIT_ML_M_TREND_A_SK_ACTIVITY_TYPE]  DEFAULT ((0)) FOR [ACTIVITY_TYPE]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_ML_M_TREND_A_SK] ADD  CONSTRAINT [DF_WC_RTLAUDIT_ML_M_TREND_A_SK_OWNER_POSTN_WID]  DEFAULT ((0)) FOR [OWNER_POSTN_WID]
GO

ALTER TABLE [dbo].[WC_RTLAUDIT_ML_M_TREND_A_SK] ADD  CONSTRAINT [DF_WC_RTLAUDIT_ML_M_TREND_A_SK_EMP_WID]  DEFAULT ((0)) FOR [EMP_WID]
GO


