SELECT 
ACT.INTEGRATION_ID,
ACT.X_BU_ID,
PER.ROW_WID CON_ROW_WID, 
A.ROW_WID ACCNT_ROW_WID,  
EMP.ROW_WID EMP_ROW_WID, 
ACT.TYPE_CD,
ACT.STATUS_CD,
ACT.PRIORITY_CD,
ACT.ACTUAL_START_DT, 
ACT.ACTUAL_END_DT, 
ACT.TRAVEL_TM_MIN ,
ACT.CATEGORY_CD,
ACT.CURCY_CD,
ACT.COST_EXCH_DT,
ACT.COST, 
ACT.CALL_DURATION, 
ACT.FS_CURCY_CD,
ACT.FS_CURCY_EXCH_DT,
ACT.RESOLUTION_CD,
REG.ROW_WID REGION_ROW_WID,
COST.FS_B_EXP_COST,
COST.FS_NB_EXP_COST,
COST.FS_EXP_B_PRICE,
COST.FS_EXP_NB_PRICE,
COST.FS_B_PART_COST,
COST.FS_NB_PART_COST,
COST.FS_PART_B_PRICE,
COST.FS_PART_NB_PRICE,
COST.FS_B_TS_COST,
COST.FS_NB_TS_COST,
COST.FS_TS_B_PRICE,
COST.FS_TS_NB_PRICE,
COST.FS_TS_TOTAL_TIME,
COST.FS_TS_B_TIME,
COST.FS_TS_NB_TIME,
POSTN.ROW_WID,
ACT.FK_01_ID,
ACT.ATTRIB_03,
ACT.ATTRIB_04,
ACT.ATTRIB_06,
ACT.ATTRIB_100,
ACT.ATTRIB_101,
ACT.ATTRIB_111,
ACT.ATTRIB_112,
ACT.ATTRIB_114,
ACT.ATTRIB_115,
ACT.ATTRIB_116,
ACT.ATTRIB_119,
ACT.FK_23_ID,
ACT.FK_24_ID,
ACT.FK_22_ID,
ACT.ATTRIB_123,
ACT.FK_27_ID,
ACT.FK_28_ID,
ACT.ATTRIB_61,
ACT.ATTRIB_95,
ACT.ATTRIB_96,
ACT.ATTRIB_99,
PRD.ROW_WID PR_PRDINT_WID,
W_PLAN_PROMO_D.ROW_WID PRD_PROMO_WID,
W_PERIOD_D.ROW_WID X_PERIOD_WID,
ACT.FK_19_ID,
ACT.FK_20_ID,
ACT.FK_21_ID,
ACT.ATTRIB_104,
ACT.FK_25_ID,
ACT.FK_26_ID,
ACT.FK_18_ID,
ACT.X_APPT_DURATION_MIN,
ACT.ATTRIB_94,
ACT.ATTRIB_93,
ACT.ATTRIB_97,
ACT.ATTRIB_98,
--ASSESS.ROW_WID, Defect 725
ACT.ATTRIB_126,
ACT.X_REAL_START_DATE,
ACT.X_REAL_END_DATE,
ACT.X_SUBTODO_CD,
ACT.FK_04_ID,
ACT.PARTICIPANT_NUM,
ACT.APPT_START_DT,
ACT.X_RESOURCES_NUM,
ACT.AGREE_ID,
ACT.X_MANUAL_CREATED_FLG,
ACT.X_END_KM_NUM,
ACT.X_START_KM_NUM,
ACT.LIC_PLATE_NUM,
ACT.X_ACTIVITY_COST_NUM,
ACT.X_ORDER_TMPL_NAME,
ACT.X_RETRO_FLG,
ACT.VISIT_INPUT_DT,
ACT.X_STAFF_TRAINING,
ACT.X_FIXED_FLAG,
ACT.X_ATTRIB_01,
ACT.X_ATTRIB_02,
ACT.X_ATTRIB_03,
ACT.X_ATTRIB_04,
ACT.X_ATTRIB_05,
ACT.X_ATTRIB_06,
ACT.X_ATTRIB_07,
ACT.X_ATTRIB_08,
ACT.X_ATTRIB_09,
ACT.X_ATTRIB_10,
ACT.X_ATTRIB_11,
ACT.X_ATTRIB_12,
ACT.X_ATTRIB_13,
ACT.X_ATTRIB_14,
ACT.X_ATTRIB_15 ,
ACT.X_ATTRIB_16 ,
ACT.X_ATTRIB_17 ,
ACT.X_ATTRIB_18 ,
ACT.X_ATTRIB_19 ,
ACT.X_ATTRIB_20 ,
ACT.X_ATTRIB_21 ,
ACT.X_ATTRIB_22 ,
ACT.X_ATTRIB_23 ,
ACT.X_ATTRIB_24 ,
ACT.X_ATTRIB_25 ,
ACT.X_ATTRIB_26 ,
ACT.X_ATTRIB_27 ,
ACT.X_ATTRIB_28 ,
ACT.X_ATTRIB_29 ,
ACT.SERV_RQST_ID ,
ACT.SR_ASSET_ID,
ACT.KPI_STATUS_CD,
ACT.OWNER_LOGIN,
ACT.X_PREVIOUS_VISIT_DATE,
ISNULL(ACT.ACTUAL_START_DT,ACT.FK_25_ID) DEVELOPMENT_DT
,ACT.X_MC_ID
,ACT.X_ATTRIB_30
--CHG038681
,ACT.ATTRIB_14
,ACT.ATTRIB_46
,ACT.OBJECTIVE_NAME
,ACT.LAST_UPD_BY
,ACT.X_OUT_OF_HRS_FLG
,ACT.X_AUDIT_FLG
,ACT.X_AUDIT_COMMENTS_TEXT
,ACT.ATTRIB_127
,ACT.ATTRIB_128
,ACT.PROG_START_DT
,ACT.PROG_END_DT
,ACT.X_LATITUDE
,ACT.X_LONGITUDE
,ACT.ASSIGNED_TO
,ACT.PAR_ASSIGNED_TO
,ACT.PAR_PERFORMED_BY
--CHG053118
,ACT.X_RESCH_PLANNED_START_DT
,ACT.X_RESCH_PLANNED_END_DT
,ACT.X_PLANNED_FLG
,ACT.RT_CYCLE_NAME
--CHG062271
,ACT.X_CANCELLED_BY
,ACT.X_PAR_CANCELLED_BY
,ACT.X_START_KMS_FIRST_NUM
,ACT.X_END_KMS_LAST_NUM
,ACT.X_PARKING_FEES_NUM
,ACT.PAR_MANL_CREATED_FLG
--CHG061084
,ACT.X_ORDER_NUM
--CHG062266
,ACT.X_TODO_TYPE_CD
,ACT.X_TODO_SUBTYPE_CD
,ACT.COMMENTS
,ACT.CLOSED_BY
,ACT.CG_SRC_PAYMENT_ID
--CHG061752
,ACT.X_SIGN_STATE_FLG
,ACT.SIG_FST_NAME
,ACT.SIG_LST_NAME
,ACT.EMAIL_ADDR
,ACT.X_SIGNATURE_DT
,ACT.CYCLE_WID --CHG062361
,ACT.X_TR_REROUTE_ID -- CHG069117, CHG069482
,ACT.ROUTING_CYCLE --CHG069117
,ACT.REROUTING_CYCLE --CHG069117
,ACT.X_START_TIME_DELAY_CD -- CHG069482
,ACT.X_TR_APPOINT_TYPE_CD -- INC1498940
,ACT.X_TR_FIXED_FLG -- INC1498940
,ACT.X_TR_PUBLIC_FLG -- INC1498940
,ACT.OBJ_PERIOD_NAME --CHG090388
,ACT.X_VISIT_CREATION_REASON_CD --CHG090137
,ACT.X_ATTRIB_31_CD --CHG099095
,ACT.X_ATTRIB_32_CD --CHG099095
,ACT.X_RA_RAL_LINK_ID --CHG107551
,ACT.X_ATTRIB_33_CD --CHG117366
,ACT.X_ATTRIB_34_CD --CHG117366
,ACT.X_ATTRIB_35 --CHG117366
,ACT.X_ATTRIB_36 --CHG117366
,ACT.X_ATTRIB_37 --CHG117366
,ACT.X_ACT_CREATION_REASON_CD--CHG117167
,ACT.X_LOCAL_ATTRIB_1_CD--CHG117403
,ACT.X_TRADE_RETURN_START_DT  --CHG117391
,ACT.X_TRADE_RETURN_END_DT --CHG117391
,ACT.X_LOCAL_ATTRIB_2_CD --CHG117391
,ACT.X_NO_OF_BOXES --CHG117391
,ACT.X_NO_OF_STICKS --CHG117391
,ACT.X_BOOT_INFO_NUM --CHG117391
,ACT.X_BOOT_RTN_INFO_NUM --CHG117391
,ACT.X_STICKS_ISSUED_NUM --CHG117391
,ACT.X_RARAL_DT --CHG124131 
,ACT.X_CAR_HIRE_FLG -- INC2370602
--CHG176441
,ACT.EVTX_ATTRIB_50
,ACT.EVTX_ATTRIB_51
,ACT.EVTX_ATTRIB_52
,ACT.EVTX_ATTRIB_34
,ACT.EVTX_ATTRIB_35
,ACT.X_DOC_TYPE_CD --CHG201045
,ACT.X_MESSAGE_STATUS --CHG201045
,ACT.X_RECIPIENT --CHG201045
,ACT.X_EVT_STAT_FLG --CHG214588
FROM
WC_ACTIVITY_FS ACT 
LEFT OUTER JOIN W_PERSON_D PER ON ACT.TARGET_PER_ID = PER.INTEGRATION_ID AND PER.CONTACT_TYPE_I = 'Contact' 
LEFT OUTER JOIN W_EMPLOYEE_D EMP ON ACT.BASE_EMP_ASGN_ID= EMP.INTEGRATION_ID 
LEFT OUTER JOIN W_PRODUCT_D PROD ON ACT.BASE_ASST_PROD_ID= PROD.INTEGRATION_ID 
LEFT OUTER JOIN W_SOURCE_D P ON	ACT.BASE_SRC_ID= P.INTEGRATION_ID 
LEFT OUTER JOIN W_OPTY_D O ON ACT.BASE_OPTY_ID= O.INTEGRATION_ID 
LEFT OUTER JOIN W_ORG_D A ON ACT.BASE_ACCNT_ID= A.INTEGRATION_ID 
LEFT OUTER JOIN W_EMP_ORG_D OWNORG ON ACT.OWNER_ORG_ID = OWNORG.INTEGRATION_ID 
LEFT OUTER JOIN W_EMP_ORG_D CRTDORG ON ACT.CREATED_BY_ORG_ID = CRTDORG.INTEGRATION_ID  
LEFT OUTER JOIN W_SRVREQ_D SR ON ACT.BASE_SR_ID = SR.INTEGRATION_ID 
LEFT OUTER JOIN W_REGION_D REG ON ACT.REGION_ID = REG.INTEGRATION_ID 
LEFT OUTER JOIN W_POSITION_D POSTN ON ACT.POSITION_ID = POSTN.INTEGRATION_ID 
LEFT OUTER JOIN W_FS_ACT_CST_FS COST ON ACT.INTEGRATION_ID = COST.INTEGRATION_ID 
LEFT OUTER JOIN W_AGREE_D AGREE ON ACT.AGREEMENT_ID  = AGREE.INTEGRATION_ID 
LEFT OUTER JOIN W_ENTLMNT_D ENTITLE ON ACT.ENTITLEMENT_ID  = ENTITLE.INTEGRATION_ID 
LEFT OUTER JOIN W_ASSET_D ON ACT.ASSET_ID = W_ASSET_D.INTEGRATION_ID 
LEFT OUTER JOIN W_CLAIMELMNT_D ON ACT.INSCLM_ELMNT_ID = W_CLAIMELMNT_D.INTEGRATION_ID 
LEFT OUTER JOIN W_INS_CLAIM_D ON ACT.CLAIM_ID = W_INS_CLAIM_D.INTEGRATION_ID 
LEFT OUTER JOIN W_PRODUCT_D PRD ON ACT.FK_02_ID = PRD.INTEGRATION_ID        
LEFT OUTER JOIN WC_ACTIVITY_F ON ACT.FK_01_ID = WC_ACTIVITY_F.INTEGRATION_ID      	
LEFT OUTER JOIN W_PLAN_PROMO_D ON ACT.FK_03_ID = W_PLAN_PROMO_D.INTEGRATION_ID 	
LEFT OUTER JOIN W_PERIOD_D ON ACT.FK_04_ID = W_PERIOD_D.INTEGRATION_ID          	
--LEFT OUTER JOIN W_ASSESS_D ASSESS ON ACT.FK_07_ID = ASSESS.INTEGRATION_ID Defect 725