----------- BEGIN CREATE TABLE [MERGE_WC_SALES_F_SK]--------------------------

PRINT 'CREATE TABLE [MERGE_WC_SALES_F_SK]'
GO


IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[MERGE_WC_SALES_F_SK]'))
DROP TABLE [dbo].[MERGE_WC_SALES_F_SK]
GO 

CREATE TABLE [dbo].[MERGE_WC_SALES_F_SK](
	[ROW_WID] [numeric](15, 0) NOT NULL,
	[DATASOURCE_NUM_ID] [numeric](10, 0) NOT NULL,
	[INTEGRATION_ID] [nvarchar](30) NOT NULL,
	[ETL_PROC_WID] [numeric](10, 0) NOT NULL,
	[SALES_TYPE_WID] [numeric](10, 0) NOT NULL,
	[START_DT_WID] [numeric](10, 0) NOT NULL,
	[END_DT_WID] [numeric](10, 0) NOT NULL,
	[PRODUCT_WID] [numeric](10, 0) NOT NULL,
	[PROM_MAT_WID] [numeric](10, 0) NOT NULL,
	[ACCNT_WID] [numeric](10, 0) NOT NULL,
	[TGT_ACCNT_WID] [numeric](10, 0) NOT NULL,
	[GEO_WID] [numeric](10, 0) NOT NULL,
	[VENDING_M_WID] [numeric](10, 0) NOT NULL,
	[ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[GROSS_MARGIN] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[NET_MARGIN] [numeric](21, 7) NULL,
	[NET_MARGIN_USD] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[CONTRIBUTION] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[OPERATING_PROFIT] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[TAX_AMOUNT] [numeric](21, 7) NULL,
	[TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[PROM_MAT_QTY] [numeric](15, 0) NULL,
	[AMT_CURCY] [nvarchar](15) NULL,
	[COUNTRY_CODE] [nvarchar](2) NOT NULL,
	[CHANNEL_WID] [numeric](10, 0) NULL,
	[SEGMENT_WID] [numeric](10, 0) NULL,
	[D_POSTN_WID2] [numeric](10, 0) NULL,
	[QUOTE_WID] [numeric](10, 0) NULL,
	[X_BU_ID] [nvarchar](30) NULL,
	[PERIOD_WID] [numeric](10, 0) NULL,
	[MONTH_WID] [numeric](10, 0) NULL,
	[YEAR_WID] [numeric](10, 0) NULL,
	[POSTN_WID] [numeric](10, 0) NULL,
	[SALES_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOM_FIELD_1] [nvarchar](50) NULL,
	[CUSTOM_FIELD_2] [nvarchar](50) NULL,
	[CUSTOM_FIELD_3] [nvarchar](50) NULL,
	[CUSTOM_FIELD_4] [nvarchar](50) NULL,
	[CUSTOM_FIELD_5] [nvarchar](50) NULL,
	[CUSTOM_FIELD_6] [nvarchar](50) NULL,
	[CUSTOM_FIELD_7] [nvarchar](50) NULL,
	[CUSTOM_FIELD_8] [nvarchar](50) NULL,
	[CUSTOM_FIELD_9] [nvarchar](50) NULL,
	[CUSTOM_FIELD_10] [nvarchar](50) NULL,
	[CUSTOM_FIELD_11] [nvarchar](50) NULL,
	[CUSTOM_FIELD_12] [nvarchar](50) NULL,
	[MANUFACTURER_COGS] [numeric](21, 7) NULL,
	[MANUFACTURER_COGS_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE_USD] [numeric](21, 7) NULL,
	[WHOLESALER_TAX] [numeric](21, 7) NULL,
	[WHOLESALER_TAX_USD] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED1_PRICE] [numeric](21, 7) NULL,
	[INTERMED1_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED1_TAX] [numeric](21, 7) NULL,
	[INTERMED1_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED2_PRICE] [numeric](21, 7) NULL,
	[INTERMED2_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED2_TAX] [numeric](21, 7) NULL,
	[INTERMED2_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED3_PRICE] [numeric](21, 7) NULL,
	[INTERMED3_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED3_TAX] [numeric](21, 7) NULL,
	[INTERMED3_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_PRICE] [numeric](21, 7) NULL,
	[RETAILER_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_TAX] [numeric](21, 7) NULL,
	[RETAILER_TAX_USD] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[X_STANDARD_COST] [numeric](21, 7) NULL,
	[X_STANDARD_COST_USD] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST_USD] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS_USD] [numeric](21, 7) NULL,
	[CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[SALES_TYPE_DESC] [nvarchar](30) NULL,
	[OOS_PRODUCT_WID] [numeric](10, 0) NULL,
	[X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL,
	[INTEGRATION_ID2] [nvarchar](32) NULL,
 CONSTRAINT [MERGE_WC_SALES_F_SK_PK] PRIMARY KEY NONCLUSTERED 
(
	[SALES_TYPE_WID] ASC,
	[ROW_WID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95) ON [PRIMARY]
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_PRODUCT_WID]  DEFAULT ((0)) FOR [PRODUCT_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_PROM_MAT_WID]  DEFAULT ((0)) FOR [PROM_MAT_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_ACCNT_WID]  DEFAULT ((0)) FOR [ACCNT_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_TGT_ACCNT_WID]  DEFAULT ((0)) FOR [TGT_ACCNT_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_GEO_WID]  DEFAULT ((0)) FOR [GEO_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_VENDING_M_WID]  DEFAULT ((0)) FOR [VENDING_M_WID]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_COGS]  DEFAULT ((0)) FOR [MANUFACTURER_COGS]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_COGS_USD]  DEFAULT ((0)) FOR [MANUFACTURER_COGS_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_PRICE]  DEFAULT ((0)) FOR [MANUFACTURER_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_PRICE_USD]  DEFAULT ((0)) FOR [MANUFACTURER_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_TAX]  DEFAULT ((0)) FOR [MANUFACTURER_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_TAX_USD]  DEFAULT ((0)) FOR [MANUFACTURER_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_GROSS_MARGIN]  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_MANUFACTURER_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_PRICE]  DEFAULT ((0)) FOR [WHOLESALER_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_PRICE_USD]  DEFAULT ((0)) FOR [WHOLESALER_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_TAX]  DEFAULT ((0)) FOR [WHOLESALER_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_TAX_USD]  DEFAULT ((0)) FOR [WHOLESALER_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_GROSS_MARGIN]  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_WHOLESALER_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_PRICE]  DEFAULT ((0)) FOR [INTERMED1_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_PRICE_USD]  DEFAULT ((0)) FOR [INTERMED1_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_TAX]  DEFAULT ((0)) FOR [INTERMED1_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_TAX_USD]  DEFAULT ((0)) FOR [INTERMED1_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_GROSS_MARGIN]  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED1_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_PRICE]  DEFAULT ((0)) FOR [INTERMED2_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_PRICE_USD]  DEFAULT ((0)) FOR [INTERMED2_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_TAX]  DEFAULT ((0)) FOR [INTERMED2_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_TAX_USD]  DEFAULT ((0)) FOR [INTERMED2_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_GROSS_MARGIN]  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED2_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_PRICE]  DEFAULT ((0)) FOR [INTERMED3_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_PRICE_USD]  DEFAULT ((0)) FOR [INTERMED3_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_TAX]  DEFAULT ((0)) FOR [INTERMED3_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_TAX_USD]  DEFAULT ((0)) FOR [INTERMED3_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_GROSS_MARGIN]  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_INTERMED3_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_SELLIN_PRICE]  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_SELLIN_PRICE_USD]  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_PRICE]  DEFAULT ((0)) FOR [RETAILER_PRICE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_PRICE_USD]  DEFAULT ((0)) FOR [RETAILER_PRICE_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_TAX]  DEFAULT ((0)) FOR [RETAILER_TAX]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_TAX_USD]  DEFAULT ((0)) FOR [RETAILER_TAX_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_GROSS_MARGIN]  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_RETAILER_GROSS_MARGIN_USD]  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_STANDARD_COST]  DEFAULT ((0)) FOR [X_STANDARD_COST]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_STANDARD_COST_USD]  DEFAULT ((0)) FOR [X_STANDARD_COST_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_DISTRIBUTION_COST]  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_DISTRIBUTION_COST_USD]  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_OTHER_COSTS_OF_GOODS]  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_OTHER_COSTS_OF_GOODS_USD]  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS_USD]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CUSTOM_SALES_FIGURES_1]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CUSTOM_SALES_FIGURES_2]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CUSTOM_SALES_FIGURES_3]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_DELIVERED_QTY]  DEFAULT ((0)) FOR [X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_X_DELIVERED_PACK]  DEFAULT ((0)) FOR [X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_GROSS_MARGIN_CONF]  DEFAULT ((0)) FOR [GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_NET_MARGIN_CONF]  DEFAULT ((0)) FOR [NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_PRODUCT_MARGIN_CONF]  DEFAULT ((0)) FOR [PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CONTRIBUTION_CONF]  DEFAULT ((0)) FOR [CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_OPERATING_PROFIT_CONF]  DEFAULT ((0)) FOR [OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_GROSS_MARGIN_USD_CONF]  DEFAULT ((0)) FOR [GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_NET_MARGIN_USD_CONF]  DEFAULT ((0)) FOR [NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_PRODUCT_MARGIN_USD_CONF]  DEFAULT ((0)) FOR [PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_CONTRIBUTION_USD_CONF]  DEFAULT ((0)) FOR [CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] ADD  CONSTRAINT [DF_MERGE_WC_SALES_F_SK_OPERATING_PROFIT_USD_CONF]  DEFAULT ((0)) FOR [OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK]  WITH CHECK ADD  CONSTRAINT [MERGE_WC_SALES_F_SK_COUNTRY_CODE] CHECK  (([COUNTRY_CODE]='SK'))
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] CHECK CONSTRAINT [MERGE_WC_SALES_F_SK_COUNTRY_CODE]
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK]  WITH CHECK ADD  CONSTRAINT [MERGE_WC_SALES_F_SK_PERIOD_LEVEL] CHECK  (([SALES_TYPE_WID]>=(59000) AND [SALES_TYPE_WID]<=(60999)))
GO

ALTER TABLE [dbo].[MERGE_WC_SALES_F_SK] CHECK CONSTRAINT [MERGE_WC_SALES_F_SK_PERIOD_LEVEL]
GO

------------------------- END CREATE TABLE [MERGE_WC_SALES_F_SK] --------------------------

----------- BEGIN CREATE TABLE [dbo].[WC_SALES_F_SK]--------------------------

PRINT 'CREATE TABLE [WC_SALES_F_SK]'
GO


IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_F_SK]'))
DROP TABLE [dbo].[WC_SALES_F_SK]
GO 

CREATE TABLE [dbo].[WC_SALES_F_SK](
	[ROW_WID] [numeric](15, 0) NOT NULL,
	[DATASOURCE_NUM_ID] [numeric](10, 0) NOT NULL,
	[INTEGRATION_ID] [nvarchar](30) NOT NULL,
	[ETL_PROC_WID] [numeric](10, 0) NOT NULL,
	[SALES_TYPE_WID] [numeric](10, 0) NOT NULL,
	[START_DT_WID] [numeric](10, 0) NOT NULL,
	[END_DT_WID] [numeric](10, 0) NOT NULL,
	[PRODUCT_WID] [numeric](10, 0) NULL,
	[PROM_MAT_WID] [numeric](10, 0) NULL,
	[ACCNT_WID] [numeric](10, 0) NULL,
	[TGT_ACCNT_WID] [numeric](10, 0) NULL,
	[GEO_WID] [numeric](10, 0) NULL,
	[VENDING_M_WID] [numeric](10, 0) NULL,
	[ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[GROSS_MARGIN] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[NET_MARGIN] [numeric](21, 7) NULL,
	[NET_MARGIN_USD] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[CONTRIBUTION] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[OPERATING_PROFIT] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[TAX_AMOUNT] [numeric](21, 7) NULL,
	[TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[PROM_MAT_QTY] [numeric](15, 0) NULL,
	[AMT_CURCY] [nvarchar](15) NULL,
	[COUNTRY_CODE] [nvarchar](2) NOT NULL,
	[CHANNEL_WID] [numeric](10, 0) NULL,
	[SEGMENT_WID] [numeric](10, 0) NULL,
	[D_POSTN_WID2] [numeric](10, 0) NULL,
	[QUOTE_WID] [numeric](10, 0) NULL,
	[X_BU_ID] [nvarchar](30) NULL,
	[PERIOD_WID] [numeric](10, 0) NULL,
	[MONTH_WID] [numeric](10, 0) NULL,
	[YEAR_WID] [numeric](10, 0) NULL,
	[POSTN_WID] [numeric](10, 0) NULL,
	[SALES_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOM_FIELD_1] [nvarchar](50) NULL,
	[CUSTOM_FIELD_2] [nvarchar](50) NULL,
	[CUSTOM_FIELD_3] [nvarchar](50) NULL,
	[CUSTOM_FIELD_4] [nvarchar](50) NULL,
	[CUSTOM_FIELD_5] [nvarchar](50) NULL,
	[CUSTOM_FIELD_6] [nvarchar](50) NULL,
	[CUSTOM_FIELD_7] [nvarchar](50) NULL,
	[CUSTOM_FIELD_8] [nvarchar](50) NULL,
	[CUSTOM_FIELD_9] [nvarchar](50) NULL,
	[CUSTOM_FIELD_10] [nvarchar](50) NULL,
	[CUSTOM_FIELD_11] [nvarchar](50) NULL,
	[CUSTOM_FIELD_12] [nvarchar](50) NULL,
	[MANUFACTURER_COGS] [numeric](21, 7) NULL,
	[MANUFACTURER_COGS_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE_USD] [numeric](21, 7) NULL,
	[WHOLESALER_TAX] [numeric](21, 7) NULL,
	[WHOLESALER_TAX_USD] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED1_PRICE] [numeric](21, 7) NULL,
	[INTERMED1_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED1_TAX] [numeric](21, 7) NULL,
	[INTERMED1_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED2_PRICE] [numeric](21, 7) NULL,
	[INTERMED2_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED2_TAX] [numeric](21, 7) NULL,
	[INTERMED2_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED3_PRICE] [numeric](21, 7) NULL,
	[INTERMED3_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED3_TAX] [numeric](21, 7) NULL,
	[INTERMED3_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_PRICE] [numeric](21, 7) NULL,
	[RETAILER_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_TAX] [numeric](21, 7) NULL,
	[RETAILER_TAX_USD] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[X_STANDARD_COST] [numeric](21, 7) NULL,
	[X_STANDARD_COST_USD] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST_USD] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS_USD] [numeric](21, 7) NULL,
	[CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[SALES_TYPE_DESC] [nvarchar](30) NULL,
	[OOS_PRODUCT_WID] [numeric](10, 0) NULL,
	[X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL,
	[INTEGRATION_ID2] [nvarchar](32) NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_F_SK]') AND name = N'[WC_SALES_F_SK_CCSI]')
CREATE CLUSTERED COLUMNSTORE INDEX [WC_SALES_F_SK_CCSI] ON [dbo].[WC_SALES_F_SK] WITH (DROP_EXISTING = OFF)
GO


ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [PROM_MAT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [ACCNT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [TGT_ACCNT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [GEO_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [VENDING_M_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [ACTL_SHIPMENT_QTY_C]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [ACTL_SHIPMENT_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [ACTL_GROSS_SHIPMENT_AMT]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [ACTL_GROSS_SHIPMENT_AMT_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [ACTL_NET_SHIPMENT_AMT]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [ACTL_NET_SHIPMENT_AMT_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MARKET_EXPENDITURE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MARKET_EXPENDITURE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [SALES_EXPENDITURE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [SALES_EXPENDITURE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [TAX_AMOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [TAX_AMOUNT_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [PROM_MAT_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ('Unspecified') FOR [AMT_CURCY]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [CHANNEL_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [SEGMENT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [D_POSTN_WID2]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [QUOTE_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [PERIOD_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MONTH_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [YEAR_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [POSTN_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [OOS_PRODUCT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_F_SK_COUNTRY_CODE] CHECK  (([COUNTRY_CODE]='SK'))
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] CHECK CONSTRAINT [WC_SALES_F_SK_COUNTRY_CODE]
GO

ALTER TABLE [dbo].[WC_SALES_F_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_F_SK_PERIOD_LEVEL] CHECK  (([SALES_TYPE_WID]>=(59000) AND [SALES_TYPE_WID]<=(60999)))
GO

ALTER TABLE [dbo].[WC_SALES_F_SK] CHECK CONSTRAINT [WC_SALES_F_SK_PERIOD_LEVEL]
GO

------------------------- END CREATE TABLE [WC_SALES_F_SK] --------------------------
----------- BEGIN CREATE TABLE [WC_SALES_M_A_BRAND_SK]--------------------------

PRINT 'CREATE TABLE [WC_SALES_M_A_BRAND_SK]'
GO


IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_M_A_BRAND_SK]'))
DROP TABLE [dbo].[WC_SALES_M_A_BRAND_SK]
GO 

CREATE TABLE [dbo].[WC_SALES_M_A_BRAND_SK](
	[ROW_WID] [numeric](10, 0) NOT NULL,
	[COUNTRY_CODE] [nvarchar](2) NOT NULL,
	[MONTH_WID] [numeric](10, 0) NOT NULL,
	[SALES_TYPE_WID] [numeric](10, 0) NOT NULL,
	[PRODUCT_WID] [numeric](10, 0) NULL,
	[PROM_MAT_WID] [numeric](10, 0) NULL,
	[ACCNT_WID] [numeric](10, 0) NULL,
	[TGT_ACCNT_WID] [numeric](10, 0) NULL,
	[GEO_WID] [numeric](10, 0) NULL,
	[VENDING_M_WID] [numeric](10, 0) NULL,
	[CHANNEL_WID] [numeric](10, 0) NULL,
	[SEGMENT_WID] [numeric](10, 0) NULL,
	[D_POSTN_WID2] [numeric](10, 0) NULL,
	[AMT_CURCY] [nvarchar](15) NULL,
	[ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[GROSS_MARGIN] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[NET_MARGIN] [numeric](21, 7) NULL,
	[NET_MARGIN_USD] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[CONTRIBUTION] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[OPERATING_PROFIT] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[TAX_AMOUNT] [numeric](21, 7) NULL,
	[TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[PROM_MAT_QTY] [numeric](15, 0) NULL,
	[YTD_ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[YTD_ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[YTD_ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[YTD_ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[YTD_ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[YTD_ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN_USD] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[YTD_MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[YTD_MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[YTD_SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[YTD_SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[YTD_TAX_AMOUNT] [numeric](21, 7) NULL,
	[YTD_TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[YTD_PROM_MAT_QTY] [numeric](15, 0) NULL,
	[QUOTE_WID] [numeric](10, 0) NULL,
	[X_BU_ID] [nvarchar](30) NULL,
	[ASSMT_ST_DT_WID] [numeric](10, 0) NULL,
	[ETL_PROC_WID] [numeric](10, 0) NULL,
	[MAT_ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[MAT_ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[MAT_ACTL_GROSS_SHIPMENT_AMT] [numeric](22, 7) NULL,
	[MAT_ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](22, 7) NULL,
	[MAT_ACTL_NET_SHIPMENT_AMT] [numeric](22, 7) NULL,
	[MAT_ACTL_NET_SHIPMENT_AMT_USD] [numeric](22, 7) NULL,
	[MAT_GROSS_MARGIN] [numeric](22, 7) NULL,
	[MAT_GROSS_MARGIN_USD] [numeric](22, 7) NULL,
	[MAT_NET_MARGIN] [numeric](22, 7) NULL,
	[MAT_NET_MARGIN_USD] [numeric](22, 7) NULL,
	[MAT_PRODUCT_MARGIN] [numeric](22, 7) NULL,
	[MAT_PRODUCT_MARGIN_USD] [numeric](22, 7) NULL,
	[MAT_MARKET_EXPENDITURE] [numeric](22, 7) NULL,
	[MAT_MARKET_EXPENDITURE_USD] [numeric](22, 7) NULL,
	[MAT_SALES_EXPENDITURE] [numeric](22, 7) NULL,
	[MAT_SALES_EXPENDITURE_USD] [numeric](22, 7) NULL,
	[MAT_CONTRIBUTION] [numeric](22, 7) NULL,
	[MAT_CONTRIBUTION_USD] [numeric](22, 7) NULL,
	[MAT_OPERATING_PROFIT] [numeric](22, 7) NULL,
	[MAT_OPERATING_PROFIT_USD] [numeric](22, 7) NULL,
	[MAT_TAX_AMOUNT] [numeric](22, 7) NULL,
	[MAT_TAX_AMOUNT_USD] [numeric](22, 7) NULL,
	[MAT_PROM_MAT_QTY] [numeric](22, 7) NULL,
	[SALES_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[YTD_SALES_DISCOUNT] [numeric](22, 7) NULL,
	[YTD_CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[MAT_SALES_DISCOUNT] [numeric](22, 7) NULL,
	[MAT_CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[GROSS_SALES] [numeric](38, 7) NULL,
	[GROSS_SALES_USD] [numeric](38, 7) NULL,
	[NET_SALES] [numeric](38, 7) NULL,
	[NET_SALES_USD] [numeric](38, 7) NULL,
	[MANUFACTURER_COGS] [numeric](21, 7) NULL,
	[MANUFACTURER_COGS_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE_USD] [numeric](21, 7) NULL,
	[WHOLESALER_TAX] [numeric](21, 7) NULL,
	[WHOLESALER_TAX_USD] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED1_PRICE] [numeric](21, 7) NULL,
	[INTERMED1_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED1_TAX] [numeric](21, 7) NULL,
	[INTERMED1_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED2_PRICE] [numeric](21, 7) NULL,
	[INTERMED2_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED2_TAX] [numeric](21, 7) NULL,
	[INTERMED2_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED3_PRICE] [numeric](21, 7) NULL,
	[INTERMED3_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED3_TAX] [numeric](21, 7) NULL,
	[INTERMED3_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_PRICE] [numeric](21, 7) NULL,
	[RETAILER_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_TAX] [numeric](21, 7) NULL,
	[RETAILER_TAX_USD] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[X_STANDARD_COST] [numeric](21, 7) NULL,
	[X_STANDARD_COST_USD] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST_USD] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS_USD] [numeric](21, 7) NULL,
	[CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[YTD_CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[YTD_CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[YTD_CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[SALES_TYPE_DESC] [nvarchar](30) NULL,
	[X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[YTD_X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[YTD_X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_M_A_BRAND_SK]') AND name = N'[WC_SALES_M_A_BRAND_SK_CCSI]')
CREATE CLUSTERED COLUMNSTORE INDEX [WC_SALES_M_A_BRAND_SK_CCSI] ON [dbo].[WC_SALES_M_A_BRAND_SK] WITH (DROP_EXISTING = OFF)
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MAT_SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MAT_CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_CUST_FIG1]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_CUST_FIG2]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_CUST_FIG3]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_YTD_CUST_FIG1]  DEFAULT ((0)) FOR [YTD_CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_YTD_CUST_FIG2]  DEFAULT ((0)) FOR [YTD_CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_BRAND_SK_YTD_CUST_FIG3]  DEFAULT ((0)) FOR [YTD_CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] ADD  DEFAULT ((0)) FOR [YTD_OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_M_A_BRAND_SK_CON_SALES_TYPE_WID] CHECK  (([SALES_TYPE_WID]>=(59000) AND [SALES_TYPE_WID]<=(60999)))
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] CHECK CONSTRAINT [WC_SALES_M_A_BRAND_SK_CON_SALES_TYPE_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_M_A_BRAND_SK_COUNTRY_CODE] CHECK  (([COUNTRY_CODE]='SK'))
GO

ALTER TABLE [dbo].[WC_SALES_M_A_BRAND_SK] CHECK CONSTRAINT [WC_SALES_M_A_BRAND_SK_COUNTRY_CODE]
GO

------------------------- END CREATE TABLE [WC_SALES_M_A_BRAND_SK] --------------------------

----------- BEGIN CREATE TABLE [dbo].[WC_SALES_M_A_PRE_SK]--------------------------

PRINT 'CREATE TABLE [WC_SALES_M_A_PRE_SK]'
GO

IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_M_A_PRE_SK]'))
DROP TABLE [dbo].[WC_SALES_M_A_PRE_SK]
GO 

CREATE TABLE [dbo].[WC_SALES_M_A_PRE_SK](
	[COUNTRY_CODE] [nvarchar](2) NULL,
	[MONTH_WID] [numeric](10, 0) NULL,
	[SALES_TYPE_WID] [numeric](10, 0) NULL,
	[PRODUCT_WID] [numeric](10, 0) NULL,
	[PROM_MAT_WID] [numeric](10, 0) NULL,
	[ACCNT_WID] [numeric](10, 0) NULL,
	[TGT_ACCNT_WID] [numeric](10, 0) NULL,
	[GEO_WID] [numeric](10, 0) NULL,
	[VENDING_M_WID] [numeric](10, 0) NULL,
	[CHANNEL_WID] [numeric](10, 0) NULL,
	[SEGMENT_WID] [numeric](10, 0) NULL,
	[D_POSTN_WID2] [numeric](10, 0) NULL,
	[AMT_CURCY] [nvarchar](15) NULL,
	[ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[GROSS_MARGIN] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[NET_MARGIN] [numeric](21, 7) NULL,
	[NET_MARGIN_USD] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[CONTRIBUTION] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[OPERATING_PROFIT] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[TAX_AMOUNT] [numeric](21, 7) NULL,
	[TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[PROM_MAT_QTY] [numeric](15, 0) NULL,
	[QUOTE_WID] [numeric](10, 0) NULL,
	[X_BU_ID] [nvarchar](30) NULL,
	[ASSMT_ST_DT_WID] [numeric](10, 0) NULL,
	[ROW_WID] [numeric](10, 0) IDENTITY(1,1) NOT NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_M_A_PRE_SK]') AND name = N'[WC_SALES_M_A_PRE_SK_IXC]')
CREATE NONCLUSTERED INDEX [WC_SALES_M_A_PRE_SK_IXC] ON [dbo].[WC_SALES_M_A_PRE_SK]
(
	[ROW_WID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO

------------------------- END CREATE TABLE [dbo].[MERGE_WC_RTLAUDIT_F_SK] --------------------------
----------- BEGIN CREATE TABLE [dbo].[WC_SALES_M_A_SK]--------------------------

PRINT 'CREATE TABLE [WC_SALES_M_A_SK]'
GO

IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_M_A_SK]'))
DROP TABLE [dbo].[WC_SALES_M_A_SK]
GO 

CREATE TABLE [dbo].[WC_SALES_M_A_SK](
	[ROW_WID] [numeric](10, 0) NOT NULL,
	[COUNTRY_CODE] [nvarchar](2) NOT NULL,
	[MONTH_WID] [numeric](10, 0) NOT NULL,
	[SALES_TYPE_WID] [numeric](10, 0) NOT NULL,
	[PRODUCT_WID] [numeric](10, 0) NULL,
	[PROM_MAT_WID] [numeric](10, 0) NULL,
	[ACCNT_WID] [numeric](10, 0) NULL,
	[TGT_ACCNT_WID] [numeric](10, 0) NULL,
	[GEO_WID] [numeric](10, 0) NULL,
	[VENDING_M_WID] [numeric](10, 0) NULL,
	[CHANNEL_WID] [numeric](10, 0) NULL,
	[SEGMENT_WID] [numeric](10, 0) NULL,
	[D_POSTN_WID2] [numeric](10, 0) NULL,
	[AMT_CURCY] [nvarchar](15) NULL,
	[ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[GROSS_MARGIN] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[NET_MARGIN] [numeric](21, 7) NULL,
	[NET_MARGIN_USD] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[CONTRIBUTION] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[OPERATING_PROFIT] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[TAX_AMOUNT] [numeric](21, 7) NULL,
	[TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[PROM_MAT_QTY] [numeric](15, 0) NULL,
	[YTD_ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[YTD_ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[YTD_ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[YTD_ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[YTD_ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[YTD_ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN_USD] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[YTD_MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[YTD_MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[YTD_SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[YTD_SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[YTD_TAX_AMOUNT] [numeric](21, 7) NULL,
	[YTD_TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[YTD_PROM_MAT_QTY] [numeric](15, 0) NULL,
	[QUOTE_WID] [numeric](10, 0) NULL,
	[X_BU_ID] [nvarchar](30) NULL,
	[ASSMT_ST_DT_WID] [numeric](10, 0) NULL,
	[ETL_PROC_WID] [numeric](10, 0) NULL,
	[MAT_ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[MAT_ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[MAT_ACTL_GROSS_SHIPMENT_AMT] [numeric](22, 7) NULL,
	[MAT_ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](22, 7) NULL,
	[MAT_ACTL_NET_SHIPMENT_AMT] [numeric](22, 7) NULL,
	[MAT_ACTL_NET_SHIPMENT_AMT_USD] [numeric](22, 7) NULL,
	[MAT_GROSS_MARGIN] [numeric](22, 7) NULL,
	[MAT_GROSS_MARGIN_USD] [numeric](22, 7) NULL,
	[MAT_NET_MARGIN] [numeric](22, 7) NULL,
	[MAT_NET_MARGIN_USD] [numeric](22, 7) NULL,
	[MAT_PRODUCT_MARGIN] [numeric](22, 7) NULL,
	[MAT_PRODUCT_MARGIN_USD] [numeric](22, 7) NULL,
	[MAT_MARKET_EXPENDITURE] [numeric](22, 7) NULL,
	[MAT_MARKET_EXPENDITURE_USD] [numeric](22, 7) NULL,
	[MAT_SALES_EXPENDITURE] [numeric](22, 7) NULL,
	[MAT_SALES_EXPENDITURE_USD] [numeric](22, 7) NULL,
	[MAT_CONTRIBUTION] [numeric](22, 7) NULL,
	[MAT_CONTRIBUTION_USD] [numeric](22, 7) NULL,
	[MAT_OPERATING_PROFIT] [numeric](22, 7) NULL,
	[MAT_OPERATING_PROFIT_USD] [numeric](22, 7) NULL,
	[MAT_TAX_AMOUNT] [numeric](22, 7) NULL,
	[MAT_TAX_AMOUNT_USD] [numeric](22, 7) NULL,
	[MAT_PROM_MAT_QTY] [numeric](22, 7) NULL,
	[SALES_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[YTD_SALES_DISCOUNT] [numeric](22, 7) NULL,
	[YTD_CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[MAT_SALES_DISCOUNT] [numeric](22, 7) NULL,
	[MAT_CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[MANUFACTURER_COGS] [numeric](21, 7) NULL,
	[MANUFACTURER_COGS_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE_USD] [numeric](21, 7) NULL,
	[WHOLESALER_TAX] [numeric](21, 7) NULL,
	[WHOLESALER_TAX_USD] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED1_PRICE] [numeric](21, 7) NULL,
	[INTERMED1_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED1_TAX] [numeric](21, 7) NULL,
	[INTERMED1_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED2_PRICE] [numeric](21, 7) NULL,
	[INTERMED2_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED2_TAX] [numeric](21, 7) NULL,
	[INTERMED2_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED3_PRICE] [numeric](21, 7) NULL,
	[INTERMED3_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED3_TAX] [numeric](21, 7) NULL,
	[INTERMED3_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_PRICE] [numeric](21, 7) NULL,
	[RETAILER_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_TAX] [numeric](21, 7) NULL,
	[RETAILER_TAX_USD] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[X_STANDARD_COST] [numeric](21, 7) NULL,
	[X_STANDARD_COST_USD] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST_USD] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS_USD] [numeric](21, 7) NULL,
	[CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[YTD_CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[YTD_CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[YTD_CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[SALES_TYPE_DESC] [nvarchar](30) NULL,
	[CUSTOM_FIELD_1] [nvarchar](50) NULL,
	[CUSTOM_FIELD_2] [nvarchar](50) NULL,
	[CUSTOM_FIELD_3] [nvarchar](50) NULL,
	[CUSTOM_FIELD_4] [nvarchar](50) NULL,
	[CUSTOM_FIELD_5] [nvarchar](50) NULL,
	[CUSTOM_FIELD_6] [nvarchar](50) NULL,
	[CUSTOM_FIELD_7] [nvarchar](50) NULL,
	[CUSTOM_FIELD_8] [nvarchar](50) NULL,
	[CUSTOM_FIELD_9] [nvarchar](50) NULL,
	[CUSTOM_FIELD_10] [nvarchar](50) NULL,
	[CUSTOM_FIELD_11] [nvarchar](50) NULL,
	[CUSTOM_FIELD_12] [nvarchar](50) NULL,
	[X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[YTD_X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[YTD_X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[YTD_GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[YTD_NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[YTD_PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[YTD_CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[YTD_OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_M_A_SK]') AND name = N'[WC_SALES_M_A_SK_CCSI]')
CREATE CLUSTERED COLUMNSTORE INDEX [WC_SALES_M_A_SK_CCSI] ON [dbo].[WC_SALES_M_A_SK] WITH (DROP_EXISTING = OFF)
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [ProductWid_Default_zero_WC_SALES_M_A_SK]  DEFAULT ((0)) FOR [PRODUCT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [PROM_MAT_WID_Default_zero_WC_SALES_M_A_SK]  DEFAULT ((0)) FOR [PROM_MAT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [ACCNT_WID_Default_zero_WC_SALES_M_A_SK]  DEFAULT ((0)) FOR [ACCNT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [TGT_ACCNT_WID_Default_zero_WC_SALES_M_A_SK]  DEFAULT ((0)) FOR [TGT_ACCNT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [GEO_WID_Default_zero_WC_SALES_M_A_SK]  DEFAULT ((0)) FOR [GEO_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [VENDING_M_WID_Default_zero_WC_SALES_M_A_SK]  DEFAULT ((0)) FOR [VENDING_M_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [QUOTE_WID_Default_zero_WC_SALES_M_A_SK]  DEFAULT ((0)) FOR [QUOTE_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [ASSMT_ST_DT_WID_Default_zero_WC_SALES_M_A_SK]  DEFAULT ((0)) FOR [ASSMT_ST_DT_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MAT_SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MAT_CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_SK_CUST_FIG1]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_SK_CUST_FIG2]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_SK_CUST_FIG3]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_SK_YTD_CUST_FIG1]  DEFAULT ((0)) FOR [YTD_CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_SK_YTD_CUST_FIG2]  DEFAULT ((0)) FOR [YTD_CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  CONSTRAINT [DF_WC_SALES_M_A_SK_YTD_CUST_FIG3]  DEFAULT ((0)) FOR [YTD_CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] ADD  DEFAULT ((0)) FOR [YTD_OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_M_A_SK_CON_SALES_TYPE_WID] CHECK  (([SALES_TYPE_WID]>=(59000) AND [SALES_TYPE_WID]<=(60999)))
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] CHECK CONSTRAINT [WC_SALES_M_A_SK_CON_SALES_TYPE_WID]
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_M_A_SK_COUNTRY_CODE] CHECK  (([COUNTRY_CODE]='SK'))
GO

ALTER TABLE [dbo].[WC_SALES_M_A_SK] CHECK CONSTRAINT [WC_SALES_M_A_SK_COUNTRY_CODE]
GO

------------------------- END CREATE TABLE [dbo].[WC_SALES_M_A_SK] --------------------------

----------- BEGIN CREATE TABLE [dbo].[MERGE_WC_RTLAUDIT_F_SK]--------------------------

PRINT 'CREATE TABLE [WC_SALES_M_DENORM_EIM_SK]'
GO

IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_M_DENORM_EIM_SK]'))
DROP TABLE [dbo].[WC_SALES_M_DENORM_EIM_SK]
GO 

CREATE TABLE [dbo].[WC_SALES_M_DENORM_EIM_SK](
	[ROW_WID] [numeric](10, 0) IDENTITY(1,1) NOT NULL,
	[PERIOD_NAME] [nvarchar](50) NOT NULL,
	[SALES_TYPE] [nvarchar](30) NOT NULL,
	[ACCNT_LOC] [nvarchar](50) NULL,
	[ACCNT_NAME] [nvarchar](100) NOT NULL,
	[PROD_NAME] [nvarchar](100) NOT NULL,
	[PROD_VENDOR_LOC] [nvarchar](50) NULL,
	[PROD_VENDOR_NAME] [nvarchar](100) NULL,
	[ACTL_SHIPMENT_QTY_CASES] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO
------------------------- END CREATE TABLE [WC_SALES_M_DENORM_EIM_SK] --------------------------
----------- BEGIN CREATE TABLE [WC_SALES_Y_A_SK]--------------------------

PRINT 'CREATE TABLE [WC_SALES_Y_A_SK]'
GO

IF  EXISTS (SELECT * FROM sys.tables WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_Y_A_SK]'))
DROP TABLE [dbo].[WC_SALES_Y_A_SK]
GO 

CREATE TABLE [dbo].[WC_SALES_Y_A_SK](
	[ROW_WID] [numeric](10, 0) NOT NULL,
	[COUNTRY_CODE] [nvarchar](2) NOT NULL,
	[MONTH_WID] [numeric](10, 0) NOT NULL,
	[SALES_TYPE_WID] [numeric](10, 0) NOT NULL,
	[PRODUCT_WID] [numeric](10, 0) NULL,
	[PROM_MAT_WID] [numeric](10, 0) NULL,
	[ACCNT_WID] [numeric](10, 0) NULL,
	[TGT_ACCNT_WID] [numeric](10, 0) NULL,
	[GEO_WID] [numeric](10, 0) NULL,
	[VENDING_M_WID] [numeric](10, 0) NULL,
	[CHANNEL_WID] [numeric](10, 0) NULL,
	[SEGMENT_WID] [numeric](10, 0) NULL,
	[D_POSTN_WID2] [numeric](10, 0) NULL,
	[AMT_CURCY] [nvarchar](15) NULL,
	[ACTL_SHIPMENT_QTY_C] [numeric](22, 7) NULL,
	[ACTL_SHIPMENT_QTY] [numeric](22, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_GROSS_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT] [numeric](21, 7) NULL,
	[ACTL_NET_SHIPMENT_AMT_USD] [numeric](21, 7) NULL,
	[GROSS_MARGIN] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[NET_MARGIN] [numeric](21, 7) NULL,
	[NET_MARGIN_USD] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE] [numeric](21, 7) NULL,
	[MARKET_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE] [numeric](21, 7) NULL,
	[SALES_EXPENDITURE_USD] [numeric](21, 7) NULL,
	[CONTRIBUTION] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD] [numeric](21, 7) NULL,
	[OPERATING_PROFIT] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD] [numeric](21, 7) NULL,
	[TAX_AMOUNT] [numeric](21, 7) NULL,
	[TAX_AMOUNT_USD] [numeric](21, 7) NULL,
	[PROM_MAT_QTY] [numeric](15, 0) NULL,
	[QUOTE_WID] [numeric](10, 0) NULL,
	[X_BU_ID] [nvarchar](30) NULL,
	[ASSMT_ST_DT_WID] [numeric](10, 0) NULL,
	[SALES_DISCOUNT] [numeric](22, 7) NULL,
	[CUSTOMER_ORIENTED_DISCOUNT] [numeric](22, 7) NULL,
	[MANUFACTURER_COGS] [numeric](21, 7) NULL,
	[MANUFACTURER_COGS_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE] [numeric](21, 7) NULL,
	[MANUFACTURER_PRICE_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX] [numeric](21, 7) NULL,
	[MANUFACTURER_TAX_USD] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[MANUFACTURER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE] [numeric](21, 7) NULL,
	[WHOLESALER_PRICE_USD] [numeric](21, 7) NULL,
	[WHOLESALER_TAX] [numeric](21, 7) NULL,
	[WHOLESALER_TAX_USD] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[WHOLESALER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED1_PRICE] [numeric](21, 7) NULL,
	[INTERMED1_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED1_TAX] [numeric](21, 7) NULL,
	[INTERMED1_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED1_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED2_PRICE] [numeric](21, 7) NULL,
	[INTERMED2_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED2_TAX] [numeric](21, 7) NULL,
	[INTERMED2_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED2_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[INTERMED3_PRICE] [numeric](21, 7) NULL,
	[INTERMED3_PRICE_USD] [numeric](21, 7) NULL,
	[INTERMED3_TAX] [numeric](21, 7) NULL,
	[INTERMED3_TAX_USD] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN] [numeric](21, 7) NULL,
	[INTERMED3_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE] [numeric](21, 7) NULL,
	[RETAILER_SELLIN_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_PRICE] [numeric](21, 7) NULL,
	[RETAILER_PRICE_USD] [numeric](21, 7) NULL,
	[RETAILER_TAX] [numeric](21, 7) NULL,
	[RETAILER_TAX_USD] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN] [numeric](21, 7) NULL,
	[RETAILER_GROSS_MARGIN_USD] [numeric](21, 7) NULL,
	[X_STANDARD_COST] [numeric](21, 7) NULL,
	[X_STANDARD_COST_USD] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST] [numeric](21, 7) NULL,
	[X_DISTRIBUTION_COST_USD] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS] [numeric](21, 7) NULL,
	[X_OTHER_COSTS_OF_GOODS_USD] [numeric](21, 7) NULL,
	[CUSTOM_SALES_FIGURES_1] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_2] [numeric](18, 7) NULL,
	[CUSTOM_SALES_FIGURES_3] [numeric](18, 7) NULL,
	[SALES_TYPE_DESC] [nvarchar](30) NULL,
	[X_DELIVERED_QTY] [numeric](22, 7) NULL,
	[X_DELIVERED_PACK] [numeric](22, 7) NULL,
	[GROSS_MARGIN_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_CONF] [numeric](21, 7) NULL,
	[GROSS_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[NET_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[PRODUCT_MARGIN_USD_CONF] [numeric](21, 7) NULL,
	[CONTRIBUTION_USD_CONF] [numeric](21, 7) NULL,
	[OPERATING_PROFIT_USD_CONF] [numeric](21, 7) NULL,
	[ETL_PROC_WID] [numeric](10, 0) NULL
) ON [PRIMARY]
WITH
(
DATA_COMPRESSION = PAGE
)
GO

IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[WC_SALES_Y_A_SK]') AND name = N'[WC_SALES_Y_A_SK_CCSI]')
CREATE CLUSTERED COLUMNSTORE INDEX [WC_SALES_Y_A_SK_CCSI] ON [dbo].[WC_SALES_Y_A_SK] WITH (DROP_EXISTING = OFF)
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [SALES_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [CUSTOMER_ORIENTED_DISCOUNT]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_COGS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [MANUFACTURER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [WHOLESALER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED1_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED2_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [INTERMED3_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_SELLIN_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_PRICE_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_TAX_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [RETAILER_GROSS_MARGIN_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [X_STANDARD_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [X_DISTRIBUTION_COST_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [X_OTHER_COSTS_OF_GOODS_USD]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  CONSTRAINT [DF_WC_SALES_Y_A_SK_CUST_FIG1]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_1]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  CONSTRAINT [DF_WC_SALES_Y_A_SK_CUST_FIG2]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_2]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  CONSTRAINT [DF_WC_SALES_Y_A_SK_CUST_FIG3]  DEFAULT ((0)) FOR [CUSTOM_SALES_FIGURES_3]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_QTY]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [X_DELIVERED_PACK]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [GROSS_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [NET_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [PRODUCT_MARGIN_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [CONTRIBUTION_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [OPERATING_PROFIT_USD_CONF]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] ADD  DEFAULT ((0)) FOR [ETL_PROC_WID]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_Y_A_SK_CON_SALES_TYPE_WID] CHECK  (([SALES_TYPE_WID]>=(59000) AND [SALES_TYPE_WID]<=(60999)))
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] CHECK CONSTRAINT [WC_SALES_Y_A_SK_CON_SALES_TYPE_WID]
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK]  WITH CHECK ADD  CONSTRAINT [WC_SALES_Y_A_SK_COUNTRY_CODE] CHECK  (([COUNTRY_CODE]='SK'))
GO

ALTER TABLE [dbo].[WC_SALES_Y_A_SK] CHECK CONSTRAINT [WC_SALES_Y_A_SK_COUNTRY_CODE]
GO

------------------------- END CREATE TABLE [WC_SALES_Y_A_SK] --------------------------
